# Generated by Django 5.1.5 on 2025-04-13 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('ts_last_login_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DMMaster',
            fields=[
                ('dm_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_1_id', models.UUIDField(db_index=True)),
                ('user_2_id', models.UUIDField(db_index=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_1_id', 'user_2_id'), name='unique_dm')],
            },
        ),
        migrations.CreateModel(
            name='GMMaster',
            fields=[
                ('gm_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_gms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(unique=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_team_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('chat_type', models.CharField(blank=True, max_length=5, null=True)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('full_thread_id', models.CharField(blank=True, null=True)),
                ('task_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('parent_task_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(blank=True, null=True)),
                ('effort_level', models.CharField(blank=True, null=True)),
                ('status', models.CharField()),
                ('priority_code', models.BigIntegerField(blank=True, null=True)),
                ('effort_level_code', models.BigIntegerField(blank=True, null=True)),
                ('status_code', models.BigIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('github_url_title', models.CharField(blank=True, null=True)),
                ('general_url', models.URLField(blank=True, null=True)),
                ('general_url_title', models.CharField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_master', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks_master', to='origin.projectmaster')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GMMessages',
            fields=[
                ('message_id', models.IntegerField(db_index=True)),
                ('message_body', models.TextField()),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_thread_created_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_messages', to='origin.gmmaster')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gm_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_task', to='origin.taskmaster')),
            ],
        ),
        migrations.CreateModel(
            name='DMMessages',
            fields=[
                ('message_id', models.IntegerField()),
                ('message_body', models.TextField()),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_thread_created_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_messages', to='origin.dmmaster')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dm_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_task', to='origin.taskmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=20)),
                ('tag_color', models.CharField(max_length=10)),
                ('tag_text_color', models.CharField(max_length=10)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_tags', to='origin.projectmaster')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='origin.taskmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMaster',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(unique=True)),
                ('team_email', models.EmailField(max_length=254, unique=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks_master', to='origin.teammaster'),
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=20)),
                ('tag_color', models.CharField(max_length=10)),
                ('tag_text_color', models.CharField(max_length=10)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='origin.projectmaster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tags', to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_joined_at', models.DateTimeField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='origin.projectmaster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_project_members', to='origin.teammaster')),
            ],
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_master', to='origin.teammaster'),
        ),
        migrations.AddField(
            model_name='gmmaster',
            name='owner_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_in_team', to='origin.teammaster'),
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_joined_at', models.DateTimeField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_attendees', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserDMMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('dm_id', models.IntegerField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'dm_id'), name='unique_dm_user_mapping')],
            },
        ),
        migrations.CreateModel(
            name='DMThreadMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('thread_message_id', models.IntegerField()),
                ('thread_message_body', models.TextField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('foreign_thread_id', models.CharField(editable=False)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_messages', to='origin.dmmaster')),
                ('parent_message_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='origin.dmmessages')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_thread_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dm_thread_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dm_id', 'thread_id', 'thread_message_id'), name='unique_dm_thread_message')],
            },
        ),
        migrations.CreateModel(
            name='GMMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_joined_at', models.DateTimeField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_gms', to=settings.AUTH_USER_MODEL)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_members', to='origin.gmmaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gm', 'attendee'), name='unique_gm_member')],
            },
        ),
        migrations.CreateModel(
            name='GMThreadMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('thread_message_id', models.IntegerField()),
                ('thread_message_body', models.TextField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('foreign_thread_id', models.CharField(editable=False)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_messages', to='origin.gmmaster')),
                ('parent_message_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='origin.gmmessages')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gm_thread_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gm_id', 'thread_id', 'thread_message_id'), name='unique_gm_thread_message')],
            },
        ),
        migrations.CreateModel(
            name='TaskComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('comment_body', models.TextField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='origin.taskmaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'comment_id'), name='unique_task_comment')],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.IntegerField()),
                ('attached_file', models.FileField(upload_to='uploads/')),
                ('attached_type', models.CharField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='origin.taskmaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'attachment_id'), name='unique_task_attachment')],
            },
        ),
        migrations.AddConstraint(
            model_name='gmmessages',
            constraint=models.UniqueConstraint(fields=('gm', 'message_id'), name='unique_gm_message'),
        ),
        migrations.AddConstraint(
            model_name='dmmessages',
            constraint=models.UniqueConstraint(fields=('dm', 'message_id'), name='unique_dm_message'),
        ),
        migrations.AddConstraint(
            model_name='tasktags',
            constraint=models.UniqueConstraint(fields=('task', 'tag_name'), name='unique_task_tag'),
        ),
        migrations.AddConstraint(
            model_name='projecttags',
            constraint=models.UniqueConstraint(fields=('project', 'tag_name'), name='unique_project_tag'),
        ),
        migrations.AddConstraint(
            model_name='projectmembers',
            constraint=models.UniqueConstraint(fields=('project', 'attendee'), name='unique_project_member'),
        ),
        migrations.AddConstraint(
            model_name='gmmaster',
            constraint=models.UniqueConstraint(fields=('group_name', 'owner_team'), name='unique_gm_master'),
        ),
        migrations.AddConstraint(
            model_name='teammembers',
            constraint=models.UniqueConstraint(fields=('team', 'attendee'), name='unique_team_member'),
        ),
    ]
