# Generated by Django 5.1.5 on 2025-03-23 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMMaster',
            fields=[
                ('gm_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('group_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('group_name', models.CharField()),
                ('owner_email', models.EmailField(max_length=254)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMaster',
            fields=[
                ('team_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(unique=True)),
                ('owner_email', models.EmailField(max_length=254)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('ts_last_login_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DMMaster',
            fields=[
                ('dm_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_1_email', models.EmailField(db_index=True, max_length=254)),
                ('user_2_email', models.EmailField(db_index=True, max_length=254)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_1_email', 'user_2_email'), name='unique_dm')],
            },
        ),
        migrations.CreateModel(
            name='DMMessages',
            fields=[
                ('message_id', models.IntegerField()),
                ('message_body', models.TextField()),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_thread_created_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_messages', to='origin.dmmaster')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dm_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='DMThreadMessages',
            fields=[
                ('thread_id', models.IntegerField()),
                ('thread_message_id', models.IntegerField()),
                ('thread_message_body', models.TextField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_messages', to='origin.dmmaster')),
                ('parent_message_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='origin.dmmessages')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_thread_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dm_thread_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='GMMembers',
            fields=[
                ('ts_joined_at', models.DateTimeField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_attendee', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_members', to='origin.gmmaster')),
            ],
        ),
        migrations.CreateModel(
            name='GMMessages',
            fields=[
                ('message_id', models.IntegerField(db_index=True)),
                ('message_body', models.TextField()),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_thread_created_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_messages', to='origin.gmmaster')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gm_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='GMThreadMessages',
            fields=[
                ('thread_id', models.IntegerField()),
                ('thread_message_id', models.IntegerField()),
                ('thread_message_body', models.TextField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_messages', to='origin.gmmaster')),
                ('parent_message_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='origin.gmmessages')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gm_thread_messages', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
        migrations.AddField(
            model_name='gmmaster',
            name='owner_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_in_team', to='origin.teammaster', to_field='team_name'),
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('ts_joined_at', models.DateTimeField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_attendees', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='origin.teammaster', to_field='team_name')),
            ],
        ),
        migrations.CreateModel(
            name='UserDMMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('dm_id', models.IntegerField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_email', 'dm_id'), name='unique_dm_user_mapping')],
            },
        ),
        migrations.AddConstraint(
            model_name='dmmessages',
            constraint=models.UniqueConstraint(fields=('dm', 'message_id'), name='unique_dm_message'),
        ),
        migrations.AddConstraint(
            model_name='dmthreadmessages',
            constraint=models.UniqueConstraint(fields=('dm_id', 'thread_id', 'thread_message_id'), name='unique_dm_thread_message'),
        ),
        migrations.AddConstraint(
            model_name='gmmembers',
            constraint=models.UniqueConstraint(fields=('gm', 'attendee'), name='unique_gm_member'),
        ),
        migrations.AddConstraint(
            model_name='gmmessages',
            constraint=models.UniqueConstraint(fields=('gm', 'message_id'), name='unique_gm_message'),
        ),
        migrations.AddConstraint(
            model_name='gmthreadmessages',
            constraint=models.UniqueConstraint(fields=('gm_id', 'thread_id', 'thread_message_id'), name='unique_gm_thread_message'),
        ),
        migrations.AddConstraint(
            model_name='teammembers',
            constraint=models.UniqueConstraint(fields=('team', 'attendee'), name='unique_team_member'),
        ),
    ]
