# Generated by Django 5.1.5 on 2025-04-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmthreadmessages',
            name='foreign_thread_id',
        ),
        migrations.RemoveField(
            model_name='gmthreadmessages',
            name='foreign_thread_id',
        ),
        migrations.RemoveField(
            model_name='taskmaster',
            name='full_thread_id',
        ),
    ]
