# Generated by Django 5.1.5 on 2025-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
