# Generated by Django 5.1.5 on 2025-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gmmaster',
            constraint=models.UniqueConstraint(fields=('group_name', 'owner_team'), name='unique_gm_master'),
        ),
    ]
