# Generated by Django 5.1.5 on 2025-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='effort_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='general_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='priority',
            field=models.CharField(blank=True, null=True),
        ),
    ]
