# Generated by Django 5.1.5 on 2025-03-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_alter_taskmaster_content_alter_taskmaster_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tasktags',
            name='unique_task_tag',
        ),
        migrations.AddConstraint(
            model_name='tasktags',
            constraint=models.UniqueConstraint(fields=('task', 'tag_name'), name='unique_task_tag'),
        ),
    ]
