# Generated by Django 5.1.5 on 2025-04-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_gmmaster_unique_gm_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='effort_level',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='priority',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='status',
            field=models.BigIntegerField(),
        ),
    ]
