# Generated by Django 5.1.5 on 2025-07-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_alter_taskmaster_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='root_task_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
