# Generated by Django 5.1.5 on 2025-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_alter_taskmaster_effort_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='effort_level_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='priority_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='status_code',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='effort_level',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='priority',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='status',
            field=models.CharField(),
        ),
    ]
