# Generated by Django 5.1.5 on 2025-07-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_taskmaster_root_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='root_task_id',
            field=models.BigIntegerField(),
        ),
    ]
