# Generated by Django 5.1.5 on 2025-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0004_taskmaster_effort_level_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='status_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
