# Generated by Django 5.1.5 on 2025-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_alter_taskmaster_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
