# Generated by Django 5.1.5 on 2025-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0005_alter_taskmaster_root_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='root_task_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
