# Generated by Django 5.1.5 on 2025-04-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0006_taskmaster_attachments_taskmaster_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmaster',
            old_name='general_link',
            new_name='general_url',
        ),
        migrations.RenameField(
            model_name='taskmaster',
            old_name='github_link',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='general_url_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='github_url_title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
