# Generated by Django 5.1.5 on 2025-07-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0006_alter_taskmaster_root_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMMessages',
            fields=[
                ('message_id', models.IntegerField(db_index=True)),
                ('message_body', models.JSONField()),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_thread_created_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_messages', to='origin.projectmaster')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pm_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_thread_task', to='origin.taskmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PMThreadMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('thread_message_id', models.IntegerField()),
                ('thread_message_body', models.JSONField()),
                ('ts_sent_at', models.DateTimeField(auto_now=True)),
                ('ts_edited_at', models.DateTimeField(blank=True, null=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_thread_messages', to='origin.pmmessages')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='origin.projectmaster')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pm_thread_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pmmessages',
            constraint=models.UniqueConstraint(fields=('project', 'message_id'), name='unique_pm_message'),
        ),
        migrations.AddConstraint(
            model_name='pmthreadmessages',
            constraint=models.UniqueConstraint(fields=('project_id', 'thread_id', 'thread_message_id'), name='unique_pm_thread_message'),
        ),
    ]
