# Generated by Django 5.1.5 on 2025-07-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0007_pmmessages_pmthreadmessages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_system_user',
            field=models.BooleanField(default=False),
        ),
    ]
