# Generated by Django 5.1.5 on 2025-04-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0007_rename_general_link_taskmaster_general_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaster',
            name='attachments',
        ),
    ]
