# Generated by Django 5.1.5 on 2025-07-08 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0008_customuser_is_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='project_system_user',
            field=models.ForeignKey(default='93a7721a-6337-4161-9f7a-9f8f83a6dce5', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
