# Generated by Django 5.1.5 on 2025-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0008_remove_taskmaster_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachments',
            name='attached_type',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
