# Generated by Django 5.1.5 on 2025-07-15 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0009_projectmaster_project_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
