# Generated by Django 5.1.5 on 2025-04-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0009_taskattachments_attached_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktags',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='origin.projectmaster'),
            preserve_default=False,
        ),
    ]
