# Generated by Django 5.1.5 on 2025-07-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_alter_dmthreadmessages_ts_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmmaster',
            name='team',
            field=models.ForeignKey(default='686c64db-7e26-4db1-9bd8-566634628535', on_delete=django.db.models.deletion.CASCADE, related_name='team_dm_master', to='origin.teammaster'),
            preserve_default=False,
        ),
    ]
