# Generated by Django 5.1.5 on 2025-04-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_tasktags_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('tag_name', models.CharField(max_length=20)),
                ('tag_color', models.CharField(max_length=10)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='origin.projectmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskTags',
        ),
        migrations.AddConstraint(
            model_name='projecttags',
            constraint=models.UniqueConstraint(fields=('project', 'tag_name'), name='unique_project_tag'),
        ),
    ]
