# Generated by Django 5.1.5 on 2025-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_dmmaster_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdmmapping',
            name='unique_dm_user_mapping',
        ),
        migrations.AddField(
            model_name='userdmmapping',
            name='team_id',
            field=models.UUIDField(db_index=True, default='686c64db-7e26-4db1-9bd8-566634628535'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='userdmmapping',
            constraint=models.UniqueConstraint(fields=('team_id', 'user_id', 'dm_id'), name='unique_dm_user_mapping'),
        ),
    ]
