# Generated by Django 5.1.5 on 2025-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_projecttags_delete_tasktags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttags',
            name='tag_text_color',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
