# Generated by Django 5.1.5 on 2025-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0012_remove_userdmmapping_unique_dm_user_mapping_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dmmaster',
            name='unique_dm',
        ),
        migrations.AddConstraint(
            model_name='dmmaster',
            constraint=models.UniqueConstraint(fields=('team', 'user_1_id', 'user_2_id'), name='unique_dm'),
        ),
    ]
