# Generated by Django 5.1.5 on 2025-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0013_remove_dmmaster_unique_dm_dmmaster_unique_dm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='dmthreadmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='gmmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='gmthreadmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='pmmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='pmthreadmessages',
            name='ts_edited_at',
        ),
        migrations.RemoveField(
            model_name='taskcomments',
            name='ts_edited_at',
        ),
        migrations.AlterField(
            model_name='dmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='ts_sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
