# Generated by Django 5.1.5 on 2025-04-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0013_tasktags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttags',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_tags', to='origin.teammaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='origin.teammaster'),
        ),
    ]
