# Generated by Django 5.1.5 on 2025-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0014_remove_dmmessages_ts_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='gmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pmmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pmthreadmessages',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='ts_sent_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
