# Generated by Django 5.1.5 on 2025-04-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0014_projecttags_team_alter_projectmembers_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmthreadmessages',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_based_task', to='origin.taskmaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmthreadmessages',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_based_task', to='origin.taskmaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_project_members', to='origin.teammaster'),
        ),
    ]
