# Generated by Django 5.1.5 on 2025-04-13 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0016_alter_dmthreadmessages_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_based_task', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_based_task', to='origin.taskmaster'),
        ),
    ]
