# Generated by Django 5.1.5 on 2025-04-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0017_alter_dmthreadmessages_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmthreadmessages',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='gmthreadmessages',
            old_name='task_id',
            new_name='task',
        ),
    ]
