# Generated by Django 5.1.5 on 2025-08-01 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0017_customuser_is_deleted_dmmaster_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionFact',
            fields=[
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('is_thread', models.BooleanField()),
                ('reaction_id', models.IntegerField()),
                ('reaction_emoji', models.CharField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat_type', 'chat_id', 'message_id', 'is_thread', 'reaction_id'), name='unique_reaction')],
            },
        ),
    ]
