# Generated by Django 5.1.5 on 2025-08-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0018_reactionfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionfact',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='origin.teammaster'),
            preserve_default=False,
        ),
    ]
