# Generated by Django 5.1.5 on 2025-04-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0018_rename_task_id_dmthreadmessages_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmthreadmessages',
            name='task',
        ),
        migrations.RemoveField(
            model_name='gmthreadmessages',
            name='task',
        ),
        migrations.AddField(
            model_name='dmmessages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_thread_task', to='origin.taskmaster'),
        ),
        migrations.AddField(
            model_name='gmmessages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm_thread_task', to='origin.taskmaster'),
        ),
    ]
