# Generated by Django 5.1.5 on 2025-08-03 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0019_reactionfact_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentReactionFact',
            fields=[
                ('comment_id', models.IntegerField()),
                ('reaction_id', models.IntegerField()),
                ('reaction_emoji', models.CharField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comment_reactions', to='origin.taskmaster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'comment_id', 'reaction_id'), name='unique_task_comment_reaction')],
            },
        ),
    ]
