# Generated by Django 5.1.5 on 2025-08-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0020_taskcommentreactionfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionFact',
            fields=[
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('is_thread', models.BooleanField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat_type', 'chat_id', 'message_id', 'is_thread', 'mentioned_user'), name='unique_mentioned_user')],
            },
        ),
        migrations.CreateModel(
            name='TaskCommentMentionFact',
            fields=[
                ('comment_id', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.taskmaster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'comment_id', 'mentioned_user'), name='unique_task_comment_mentioned_user')],
            },
        ),
    ]
