# Generated by Django 5.1.5 on 2025-08-30 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0021_mentionfact_taskcommentmentionfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_body', models.CharField()),
                ('item_type', models.IntegerField()),
                ('is_read', models.BooleanField(default=False)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.teammaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
