# Generated by Django 5.1.5 on 2025-08-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0022_inboxitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitems',
            old_name='user',
            new_name='receiver',
        ),
    ]
