# Generated by Django 5.1.5 on 2025-08-30 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0023_rename_user_inboxitems_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitems',
            name='sender',
            field=models.ForeignKey(default='93a7721a-6337-4161-9f7a-9f8f83a6dce5', on_delete=django.db.models.deletion.CASCADE, related_name='sender_inboxes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inboxitems',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_inboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
