# Generated by Django 5.1.5 on 2025-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0024_inboxitems_sender_alter_inboxitems_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitems',
            name='item_optionals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
