# Generated by Django 5.1.5 on 2025-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0025_inboxitems_item_optionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentionfact',
            name='thread_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inboxitems',
            name='item_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
