# Generated by Django 5.1.5 on 2025-09-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0026_mentionfact_thread_id_alter_inboxitems_item_body'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentionfact',
            name='unique_mentioned_user',
        ),
        migrations.AddConstraint(
            model_name='mentionfact',
            constraint=models.UniqueConstraint(fields=('chat_type', 'chat_id', 'thread_id', 'message_id', 'mentioned_user'), name='unique_mentioned_user'),
        ),
    ]
