# Generated by Django 5.1.5 on 2025-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0027_remove_mentionfact_unique_mentioned_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reactionfact',
            name='unique_reaction',
        ),
        migrations.AddField(
            model_name='reactionfact',
            name='thread_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reactionfact',
            constraint=models.UniqueConstraint(fields=('chat_type', 'chat_id', 'thread_id', 'message_id', 'reaction_id'), name='unique_reaction'),
        ),
    ]
