# Generated by Django 5.1.5 on 2025-09-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0028_remove_reactionfact_unique_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
