# Generated by Django 5.1.5 on 2025-09-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0029_customuser_custom_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='base_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_offline_forced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
