# Generated by Django 5.1.5 on 2025-09-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0031_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmmaster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_dm_master', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='dmmessages',
            name='dm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_messages', to='origin.dmmaster'),
        ),
        migrations.AlterField(
            model_name='dmmessages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dmmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dm_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dmmessages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_thread_task', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='dm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_thread_messages', to='origin.dmmaster'),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='parent_message_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='origin.dmmessages'),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_thread_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dmthreadmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dm_thread_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmmaster',
            name='owner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_in_team', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='gmmaster',
            name='owner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_gms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmmembers',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_gms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmmembers',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_members', to='origin.gmmaster'),
        ),
        migrations.AlterField(
            model_name='gmmessages',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_messages', to='origin.gmmaster'),
        ),
        migrations.AlterField(
            model_name='gmmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gm_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gmmessages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_thread_task', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_thread_messages', to='origin.gmmaster'),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='parent_message_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='origin.gmmessages'),
        ),
        migrations.AlterField(
            model_name='gmthreadmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_gm_thread_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitems',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_inboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitems',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_inboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxitems',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='mentionfact',
            name='mentioned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentionfact',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='pmmessages',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_messages', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='pmmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pm_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pmmessages',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_thread_task', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='pmthreadmessages',
            name='parent_message_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_thread_messages', to='origin.pmmessages'),
        ),
        migrations.AlterField(
            model_name='pmthreadmessages',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='pmthreadmessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pm_thread_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_team_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='project_system_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmaster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_master', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_members', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='projectmembers',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_project_members', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tags', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='projecttags',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_tags', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='reactionfact',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reactionfact',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='taskcommentmentionfact',
            name='mentioned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcommentmentionfact',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='taskcommentmentionfact',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='taskcommentreactionfact',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcommentreactionfact',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comment_reactions', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='taskcommentreactionfact',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcomments',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks_master', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tasks_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_tasks_master', to='origin.teammaster'),
        ),
        migrations.AlterField(
            model_name='tasktags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_tags', to='origin.projectmaster'),
        ),
        migrations.AlterField(
            model_name='tasktags',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_tags', to='origin.taskmaster'),
        ),
        migrations.AlterField(
            model_name='teammaster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='origin.teammaster'),
        ),
    ]
