# Generated by Django 5.1.5 on 2025-09-11 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0032_alter_dmmaster_team_alter_dmmessages_dm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('dm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.dmmaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'dm', 'last_read_message_id'), name='unique_read_dm_message')],
            },
        ),
        migrations.CreateModel(
            name='DMThreadReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('last_read_thread_message_id', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('dm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.dmmaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'dm', 'thread_id', 'last_read_thread_message_id'), name='unique_read_dm_thread_message')],
            },
        ),
    ]
