# Generated by Django 5.1.5 on 2025-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0033_dmreadstatus_dmthreadreadstatus'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dmreadstatus',
            name='unique_read_dm_message',
        ),
        migrations.RemoveConstraint(
            model_name='dmthreadreadstatus',
            name='unique_read_dm_thread_message',
        ),
        migrations.AddConstraint(
            model_name='dmreadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'dm'), name='unique_read_dm_message'),
        ),
        migrations.AddConstraint(
            model_name='dmthreadreadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'dm', 'thread_id'), name='unique_read_dm_thread_message'),
        ),
    ]
