# Generated by Django 5.1.5 on 2025-09-11 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0034_remove_dmreadstatus_unique_read_dm_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmthreadreadstatus',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='dmthreadreadstatus',
            name='user',
        ),
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('last_read_message_id', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DMReadStatus',
        ),
        migrations.DeleteModel(
            name='DMThreadReadStatus',
        ),
        migrations.AddConstraint(
            model_name='readstatus',
            constraint=models.UniqueConstraint(fields=('user', 'chat_type', 'chat_id', 'thread_id', 'last_read_message_id'), name='unique_read_status'),
        ),
    ]
