# Generated by Django 5.1.5 on 2025-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0035_remove_dmthreadreadstatus_dm_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readstatus',
            name='unique_read_status',
        ),
        migrations.AddConstraint(
            model_name='readstatus',
            constraint=models.UniqueConstraint(fields=('user', 'chat_type', 'chat_id', 'thread_id'), name='unique_read_status'),
        ),
    ]
