# Generated by Django 5.1.5 on 2025-09-13 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0036_remove_readstatus_unique_read_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFact',
            fields=[
                ('activity_id', models.CharField(primary_key=True, serialize=False)),
                ('activity_type', models.IntegerField()),
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('chat_name', models.CharField(blank=True, null=True)),
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('message_unique_key', models.CharField()),
                ('thread_message_unique_key', models.CharField()),
                ('first_line_content', models.CharField()),
                ('latest_reaction', models.JSONField()),
                ('reactions', models.JSONField()),
                ('mentioned_user_ids', models.JSONField()),
                ('is_read', models.BooleanField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('dm_partner_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_partners_reactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders_reactions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.taskmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
            ],
        ),
    ]
