# Generated by Django 5.1.5 on 2025-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0037_activityfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfact',
            name='thread_message_unique_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
