# Generated by Django 5.1.5 on 2025-09-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0038_alter_activityfact_thread_message_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfact',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to='origin.projectmaster'),
        ),
    ]
