# Generated by Django 5.1.5 on 2025-09-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0039_activityfact_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfact',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.projectmaster'),
        ),
    ]
