# Generated by Django 5.1.5 on 2025-09-14 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0040_alter_activityfact_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfact',
            name='latest_reaction_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacted_users_activity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityfact',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
