# Generated by Django 5.1.5 on 2025-09-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0041_activityfact_latest_reaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attached_file',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
