# Generated by Django 5.1.5 on 2025-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0045_alter_taskattachments_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attached_file',
            field=models.FileField(upload_to='task_attachments/'),
        ),
    ]
