# Generated by Django 5.1.5 on 2025-09-18 17:22

import origin.models.task.task_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0046_alter_taskattachments_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attached_file',
            field=models.FileField(upload_to=origin.models.task.task_models.task_attachment_path),
        ),
    ]
