# Generated by Django 5.1.5 on 2025-09-19 09:38

import origin.models.common.user_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0047_alter_taskattachments_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image_url',
            field=models.FileField(upload_to=origin.models.common.user_models.user_profile_image_path),
        ),
    ]
