# Generated by Django 5.1.5 on 2025-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0048_alter_customuser_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_file_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
