# Generated by Django 5.1.5 on 2025-09-20 02:25

import origin.models.common.team_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0049_customuser_profile_image_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammaster',
            name='profile_image_file',
            field=models.FileField(default="", upload_to=origin.models.common.team_models.profile_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammaster',
            name='profile_image_file_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
