# Generated by Django 5.1.5 on 2025-09-20 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0050_teammaster_profile_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNoteMaster',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('parent_note_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_personal_notes', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_notes', to='origin.teammaster')),
            ],
        ),
    ]
