# Generated by Django 5.1.5 on 2025-09-21 08:28

import django.db.models.deletion
import origin.models.note.personal_note_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0051_notepermissionmaster_personalnotemaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalNoteAttachmentFact",
            fields=[
                (
                    "attachment_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "note_attachment_url",
                    models.FileField(
                        upload_to=origin.models.note.personal_note_models.personal_note_attachment_path
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="origin.personalnotemaster",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
