# Generated by Django 5.1.5 on 2025-09-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0052_personalnoteattachmentfact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalnoteattachmentfact',
            old_name='note_id',
            new_name='note',
        ),
    ]
