# Generated by Django 5.1.5 on 2025-09-21 09:31

import django.db.models.deletion
import origin.models.note.task_note_models
import origin.models.note.chat_note_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0053_rename_note_id_personalnoteattachmentfact_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnotemaster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalnotemaster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.CreateModel(
            name='ChatNoteMaster',
            fields=[
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('note_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('parent_note_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='ChatNoteAttachmentFact',
            fields=[
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.note.chat_note_models.chat_note_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.chatnotemaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNoteMaster',
            fields=[
                ('note_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('parent_note_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.taskmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNoteAttachmentFact',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.note.task_note_models.task_note_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.taskmaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.tasknotemaster')),
            ],
        ),
    ]
