# Generated by Django 5.1.5 on 2025-09-21 09:44

import django.db.models.deletion
import origin.models.chat.dm_models
import origin.models.chat.gm_models
import origin.models.chat.pm_models
import origin.models.task.task_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0054_alter_personalnotemaster_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMAttachmentFact',
            fields=[
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.chat.dm_models.dm_message_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('dm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.dmmaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GMAttachmentFact',
            fields=[
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.chat.gm_models.gm_message_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('gm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.gmmaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMAttachmentFact',
            fields=[
                ('is_thread', models.BooleanField()),
                ('thread_id', models.IntegerField()),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.chat.pm_models.project_message_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.projectmaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBodyAttachmentFact',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('note_attachment_url', models.FileField(upload_to=origin.models.task.task_models.task_body_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.taskmaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
