# Generated by Django 5.1.5 on 2025-09-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0055_dmattachmentfact_gmattachmentfact_pmattachmentfact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepermissionmaster',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
        migrations.AddField(
            model_name='tasknotemaster',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_notes', to='origin.projectmaster'),
        ),
    ]
