# Generated by Django 5.1.5 on 2025-09-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0056_notepermissionmaster_team_tasknotemaster_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notepermissionmaster",
            name="note_id",
            field=models.BigIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="notepermissionmaster",
            constraint=models.UniqueConstraint(
                fields=("user", "note_type", "note_id"), name="unique_note_permission"
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE origin_notepermissionmaster ADD COLUMN id BIGSERIAL PRIMARY KEY;",
            reverse_sql="ALTER TABLE origin_notepermissionmaster DROP COLUMN id;"
        ),
    ]
