# Generated by Django 5.1.5 on 2025-09-27 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0058_notepermissionmaster_id_activityreadstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfact',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='activityreadstatus',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='activityreadstatus',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_read_status', to='origin.activityfact'),
        )
    ]
