# Generated by Django 5.1.5 on 2025-09-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0059_remove_activityfact_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreadstatus',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
    ]
