# Generated by Django 5.1.5 on 2025-09-27 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0060_activityreadstatus_team_notepermissionmaster_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.BigIntegerField()),
                ('note_type', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_note_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'note_type', 'note_id'), name='unique_note_permission')],
            },
        ),
    ]
