# Generated by Django 5.1.5 on 2025-09-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0061_notepermissionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstatus',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster'),
        ),
    ]
