# Generated by Django 5.1.5 on 2025-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0062_readstatus_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmmaster',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
