# Generated by Django 5.1.5 on 2025-09-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0063_gmmaster_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
