# Generated by Django 5.1.5 on 2025-09-28 13:03

import origin.models.chat.gm_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0064_projectmaster_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmmaster',
            name='profile_image_file_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gmmaster',
            name='profile_image_url',
            field=models.FileField(blank=True, null=True, upload_to=origin.models.chat.gm_models.profile_image_path),
        ),
    ]
