# Generated by Django 5.1.5 on 2025-09-29 13:26

import origin.models.project.prj_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0065_gmmaster_profile_image_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='profile_image_file_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='profile_image_url',
            field=models.FileField(blank=True, null=True, upload_to=origin.models.project.prj_models.profile_image_path),
        ),
    ]
