# Generated by Django 5.1.5 on 2025-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0066_projectmaster_profile_image_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskbodyattachmentfact',
            old_name='note_attachment_url',
            new_name='body_attachment_url',
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='is_init_table',
            field=models.BooleanField(default=False),
        ),
    ]
