# Generated by Django 5.1.5 on 2025-10-04 09:46

import django.db.models.deletion
import origin.models.chat.chat_attachment_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0067_rename_note_attachment_url_taskbodyattachmentfact_body_attachment_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachmentFact',
            fields=[
                ('chat_type', models.IntegerField()),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('thread_id', models.IntegerField()),
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('body_attachment_url', models.FileField(upload_to=origin.models.chat.chat_attachment_models.chat_attachment_path)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
