# Generated by Django 5.1.5 on 2025-10-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0068_chatattachmentfact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatattachmentfact',
            old_name='body_attachment_url',
            new_name='chat_attachment_url',
        ),
    ]
