# Generated by Django 5.1.5 on 2025-10-05 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0069_rename_body_attachment_url_chatattachmentfact_chat_attachment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoFact',
            fields=[
                ('todo_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('todo_content', models.JSONField()),
                ('is_completed', models.BooleanField()),
                ('dt_created_on', models.DateField(auto_now_add=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'todo_id'), name='unique_todo')],
            },
        ),
    ]
