# Generated by Django 5.1.5 on 2025-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0071_alter_todofact_is_completed_userchatmaster'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todofact',
            name='unique_todo',
        ),
        migrations.RenameField(
            model_name='todofact',
            old_name='dt_created_on',
            new_name='local_dt_created_on',
        ),
        migrations.AddConstraint(
            model_name='todofact',
            constraint=models.UniqueConstraint(fields=('team', 'user', 'todo_id'), name='unique_todo'),
        ),
    ]
