# Generated by Django 5.1.5 on 2025-10-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0072_remove_todofact_unique_todo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmaster',
            old_name='is_init_table',
            new_name='is_init_task',
        ),
    ]
