# Generated by Django 5.1.5 on 2025-10-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0073_rename_is_init_table_taskmaster_is_init_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='chat_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
