# Generated by Django 5.1.5 on 2025-10-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0074_alter_taskmaster_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmaster',
            name='flagged_messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
