# Generated by Django 5.1.5 on 2025-10-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0075_userchatmaster_flagged_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='mentioned_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
