# Generated by Django 5.1.5 on 2025-11-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0076_taskmaster_mentioned_user_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaster',
            name='general_url',
        ),
        migrations.RemoveField(
            model_name='taskmaster',
            name='general_url_title',
        ),
        migrations.RemoveField(
            model_name='taskmaster',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='taskmaster',
            name='github_url_title',
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
