# Generated by Django 5.1.5 on 2026-01-18 14:44

import django.db.models.deletion
import origin.models.chat.legacy_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0078_notefavoritemaster"),
    ]

    operations = [
        migrations.CreateModel(
            name="MDMMaster",
            fields=[
                ("mdm_id", models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mdms_in_team",
                        to="origin.teammaster",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="own_mdms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MDMAttachmentFact",
            fields=[
                ("is_thread", models.BooleanField()),
                ("thread_id", models.IntegerField()),
                (
                    "attachment_id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "note_attachment_url",
                    models.FileField(
                        upload_to=origin.models.chat.legacy_paths.mdm_message_attachment_path
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mdm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="origin.mdmmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MDMMessages",
            fields=[
                ("message_id", models.IntegerField(db_index=True)),
                ("message_body", models.JSONField()),
                ("thread_id", models.IntegerField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_sent_at", models.DateTimeField(auto_now_add=True)),
                ("ts_thread_created_at", models.DateTimeField(blank=True, null=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "mdm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mdm_messages",
                        to="origin.mdmmaster",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mdm_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mdm_thread_task",
                        to="origin.taskmaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MDMThreadMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("thread_id", models.IntegerField()),
                ("thread_message_id", models.IntegerField()),
                ("thread_message_body", models.JSONField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_sent_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mdm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mdm_thread_messages",
                        to="origin.mdmmaster",
                    ),
                ),
                (
                    "parent_message_uid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_messages",
                        to="origin.mdmmessages",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mdm_thread_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MDMMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ts_joined_at", models.DateTimeField(auto_now_add=True)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attending_mdms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mdm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mdm_members",
                        to="origin.mdmmaster",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mdm", "attendee"), name="unique_mdm_member")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mdmmessages",
            constraint=models.UniqueConstraint(
                fields=("mdm", "message_id"), name="unique_mdm_message"
            ),
        ),
        migrations.AddConstraint(
            model_name="mdmthreadmessages",
            constraint=models.UniqueConstraint(
                fields=("mdm_id", "thread_id", "thread_message_id"),
                name="unique_mdm_thread_message",
            ),
        ),
    ]
