# Generated by Django 5.1.5

import origin.models.common.team_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0078_notefavoritemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammaster',
            name='profile_image_file',
            field=models.FileField(blank=True, null=True, upload_to=origin.models.common.team_models.profile_image_path),
        ),
    ]
