# Generated by Django 5.1.5 on 2026-04-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0079_mdmmaster_mdmattachmentfact_mdmmessages_and_more'),
        ('origin', '0079_teammaster_profile_image_file_nullable'),
    ]

    operations = [
    ]
