# Generated by Django 5.1.5 on 2026-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0080_merge_20260425_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitems',
            name='request_status',
            field=models.CharField(blank=True, default='pending', max_length=10),
        ),
    ]
