# Generated by Django 5.1.5 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0081_inboxitems_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attached_type',
            field=models.CharField(blank=True, default=''),
        ),
    ]
