# Generated by Django 5.1.5 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0082_alter_taskattachments_attached_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachments',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
