# Generated by Django 5.1.5 on 2026-05-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0083_taskattachments_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRecentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.BigIntegerField()),
                ('note_type', models.IntegerField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_opened_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recent_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts_opened_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'note_type', 'note_id'), name='unique_user_note_recent')],
            },
        ),
    ]
