# Generated by Django 5.1.5 on 2026-05-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0084_noterecentmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneMaster',
            fields=[
                ('milestone_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Open')),
                ('status_code', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, null=True)),
                ('priority_code', models.BigIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='origin.projectmaster')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_milestones', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_milestones', to='origin.teammaster')),
            ],
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_tasks', to='origin.milestonemaster'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('sprint_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sequence_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='upcoming', max_length=16)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sprints', to='origin.projectmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_sprints', to='origin.teammaster')),
            ],
            options={
                'ordering': ['project_id', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='milestonemaster',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_milestones', to='origin.sprint'),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_tasks', to='origin.sprint'),
        ),
        migrations.CreateModel(
            name='SprintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(default=14)),
                ('anchor_date', models.DateField()),
                ('auto_roll', models.BooleanField(default=True)),
                ('upcoming_horizon', models.IntegerField(default=6)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_config', to='origin.projectmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_sprint_configs', to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_milestone_assignees', to='origin.teammaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestone_assignments', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_assignees', to='origin.milestonemaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('milestone', 'user'), name='unique_milestone_assignee')],
            },
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_number'), name='unique_project_sprint_sequence'),
        ),
    ]
