# Generated by Django 5.1.5 on 2026-05-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0085_milestonemaster_taskmaster_milestone_sprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonemaster',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backed_milestone', to='origin.taskmaster'),
        ),
        migrations.AddField(
            model_name='taskmaster',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
    ]
