# Generated by Django 5.1.5 on 2026-05-02 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0087_milestonemaster_effort_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('title_changed', 'Title changed'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('effort_changed', 'Effort changed'), ('assignee_changed', 'Assignee changed'), ('reporter_changed', 'Reporter changed'), ('due_date_changed', 'Due date changed'), ('description_edited', 'Description edited'), ('tags_changed', 'Tags changed'), ('parent_changed', 'Parent changed'), ('milestone_changed', 'Milestone changed'), ('sprint_changed', 'Sprint changed'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('deleted', 'Deleted'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('comment_added', 'Comment added'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('milestone_assignee_added', 'Milestone assignee added'), ('milestone_assignee_removed', 'Milestone assignee removed')], max_length=48)),
                ('field_name', models.CharField(blank=True, max_length=64, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_task_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_activities', to='origin.projectmaster')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='origin.taskmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_task_activities', to='origin.teammaster')),
            ],
            options={
                'indexes': [models.Index(fields=['task', '-ts_created_at'], name='taskact_task_created_idx')],
            },
        ),
    ]
