# Generated by Django 5.1.5 on 2026-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0093_userfeatureaccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeatureaccess",
            name="feature",
            field=models.CharField(
                choices=[
                    ("web_search", "Web Search (Tavily)"),
                    ("unlimited_agent", "Unlimited AI Agent asks (no daily cap)"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
