# Generated by Django 5.1.5 on 2026-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0096_add_is_demo_flags"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dmmessages",
            index=models.Index(
                fields=["dm", "message_id", "is_deleted"], name="dm_msg_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dmthreadmessages",
            index=models.Index(
                fields=["dm", "thread_id", "thread_message_id", "is_deleted"],
                name="dm_thread_msg_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gmmessages",
            index=models.Index(
                fields=["gm", "message_id", "is_deleted"], name="gm_msg_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmthreadmessages",
            index=models.Index(
                fields=["gm", "thread_id", "thread_message_id", "is_deleted"],
                name="gm_thread_msg_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mdmmessages",
            index=models.Index(
                fields=["mdm", "message_id", "is_deleted"], name="mdm_msg_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mdmthreadmessages",
            index=models.Index(
                fields=["mdm", "thread_id", "thread_message_id", "is_deleted"],
                name="mdm_thread_msg_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pmmessages",
            index=models.Index(
                fields=["project", "message_id", "is_deleted"], name="pm_msg_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pmthreadmessages",
            index=models.Index(
                fields=["project", "thread_id", "thread_message_id", "is_deleted"],
                name="pm_thread_msg_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reactionfact",
            index=models.Index(
                fields=["chat_type", "chat_id", "message_id", "is_thread", "thread_id"],
                name="reaction_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reactionfact",
            index=models.Index(
                fields=["team", "chat_type", "chat_id", "message_id", "is_thread"],
                name="reaction_team_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="readstatus",
            index=models.Index(
                fields=["user", "chat_type", "chat_id", "is_thread"],
                name="read_status_user_chat_idx",
            ),
        ),
    ]
