# Generated by Django 5.1.5 on 2026-05-20 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0102_remove_taskmaster_linked_pr_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubWebhookRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("owner", models.CharField(max_length=255)),
                ("repo", models.CharField(max_length=255)),
                ("hook_id", models.BigIntegerField()),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "repo"), name="github_webhook_unique_per_repo"
                    )
                ],
            },
        ),
    ]
