# Generated by Django 5.1.5 on 2026-05-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0104_project_code_task_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auto_close_on_pr_merge",
            field=models.BooleanField(default=False),
        ),
    ]
