# Generated by Django 5.1.5 on 2026-05-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0107_user_auto_sync_tasks_to_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_dependencies",
                        to="origin.taskmaster",
                    ),
                ),
                (
                    "blocker_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_dependencies",
                        to="origin.taskmaster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_dependencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_task_dependencies",
                        to="origin.teammaster",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["blocker_task"], name="origin_task_blocker_71c22b_idx"),
                    models.Index(fields=["blocked_task"], name="origin_task_blocked_69781e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker_task", "blocked_task"), name="unique_task_dependency_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker_task", models.F("blocked_task")), _negated=True
                        ),
                        name="task_dependency_no_self_block",
                    ),
                ],
            },
        ),
    ]
