# Generated by Django 5.1.5 on 2026-05-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0108_taskmaster_team_proj_init_idx"),
        ("origin", "0109_task_dependency"),
    ]

    operations = []
