# Generated by Django 5.1.5 on 2026-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0111_alter_taskactivity_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmaster",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
