# Generated by Django 5.1.5 on 2026-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0112_taskmaster_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestonemaster",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
