# Generated by Django 5.1.5 on 2026-05-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0113_milestonemaster_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentionGroupMaster",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, default="", max_length=120)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mention_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mention_groups",
                        to="origin.teammaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentionGroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="origin.mentiongroupmaster",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mention_group_member_team",
                        to="origin.teammaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mention_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mentiongroupmaster",
            constraint=models.UniqueConstraint(
                fields=("team", "group_name"), name="uniq_mention_group_name_per_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentiongroupmembers",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="uniq_user_per_mention_group"
            ),
        ),
    ]
