# Generated by Django 5.1.5 on 2026-05-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0114_mention_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatnotemaster",
            name="mentioned_user_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="personalnotemaster",
            name="mentioned_user_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tasknotemaster",
            name="mentioned_user_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
