# Generated by Django 5.1.5 on 2026-05-25 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0117_activityfact_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_llm_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model id within the chosen provider; '' = provider default.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_llm_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="'gemini', 'claude', or '' to use the server default.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userfeatureaccess",
            name="feature",
            field=models.CharField(
                choices=[
                    ("web_search", "Web Search (Tavily)"),
                    ("unlimited_agent", "Unlimited AI Agent asks (no daily cap)"),
                    ("paid_tier", "Paid tier (raised per-model daily quotas)"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ModelUsageCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=128)),
                ("usage_date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_usage_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Usage Counter",
                "verbose_name_plural": "Model Usage Counters",
                "indexes": [
                    models.Index(
                        fields=["user", "usage_date"], name="origin_mode_user_id_ef7276_idx"
                    )
                ],
                "unique_together": {("user", "model_name", "usage_date")},
            },
        ),
    ]
