# Generated by Django 5.1.5 on 2026-05-25 12:12

from django.db import migrations, models


def _delete_paid_tier_rows(apps, schema_editor):
    """Drop any UserFeatureAccess rows for the obsolete `paid_tier`
    feature — replaced by `CustomUser.tier`. Defensive: in greenfield
    deploys this is a no-op."""
    UserFeatureAccess = apps.get_model("origin", "UserFeatureAccess")
    UserFeatureAccess.objects.filter(feature="paid_tier").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0118_customuser_preferred_llm_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tier",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("max", "Max")],
                db_index=True,
                default="free",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="userfeatureaccess",
            name="feature",
            field=models.CharField(
                choices=[
                    ("web_search", "Web Search (Tavily) [deprecated]"),
                    ("unlimited_agent", "Unlimited AI Agent asks [deprecated]"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.RunPython(_delete_paid_tier_rows, migrations.RunPython.noop),
    ]
