# Generated by Django 5.1.5 on 2026-05-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0120_activityfact_mentioned_via_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoCategory",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("sort_order", models.IntegerField(default=0)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todo_categories",
                        to="origin.teammaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToDoGroup",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("local_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="todo_groups",
                        to="origin.teammaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("notes", models.JSONField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                ("ts_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="origin.todocategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="origin.todogroup",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ToDoFact",
        ),
        migrations.AddConstraint(
            model_name="todocategory",
            constraint=models.UniqueConstraint(
                fields=("team", "user", "name"), name="uniq_todo_category_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="todogroup",
            index=models.Index(fields=["user", "-local_date"], name="todo_group_user_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="todogroup",
            constraint=models.UniqueConstraint(
                fields=("team", "user", "local_date"), name="uniq_todo_group_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(fields=["group", "sort_order"], name="todo_item_group_order_idx"),
        ),
    ]
