# Generated by Django 5.1.5 on 2026-05-28 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0121_todocategory_todogroup_todoitem_delete_todofact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subitems",
                to="origin.todoitem",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(fields=["parent_item"], name="todo_item_parent_idx"),
        ),
    ]
