# Generated by Django 5.1.5 on 2026-05-28 16:52

import django.db.models.deletion
import origin.models.chat.unified_models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0122_todoitem_parent_item_todoitem_todo_item_parent_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "dm"), (2, "gm"), (3, "pm"), (4, "mdm")]
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("profile_image_url", models.CharField(blank=True, default="", max_length=512)),
                ("is_private", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to="origin.projectmaster",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="channels",
                        to="origin.teammaster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("role", models.CharField(default="member", max_length=16)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ts_joined_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="origin.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("seq", models.BigIntegerField()),
                ("body", models.JSONField()),
                ("body_text", models.TextField(blank=True, default="")),
                ("is_thread_reply", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reply_count", models.IntegerField(default=0)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("ts_sent_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="origin.channel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_replies",
                        to="origin.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="origin.taskmaster",
                    ),
                ),
                (
                    "thread_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_descendants",
                        to="origin.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagged_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="origin.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=origin.models.chat.unified_models._message_attachment_path
                    ),
                ),
                ("mime", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="origin.message",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("via_group_id", models.UUIDField(blank=True, null=True)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="origin.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("emoji", models.CharField(max_length=64)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="origin.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="origin.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadCursor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_cursors",
                        to="origin.channel",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="origin.message",
                    ),
                ),
                (
                    "thread_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_read_cursors",
                        to="origin.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_cursors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelDirectPair",
            fields=[
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="direct_pair",
                        serialize=False,
                        to="origin.channel",
                    ),
                ),
                ("user_lo", models.UUIDField()),
                ("user_hi", models.UUIDField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user_lo"], name="dm_pair_lo_idx"),
                    models.Index(fields=["user_hi"], name="dm_pair_hi_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user_lo", "user_hi"), name="uniq_dm_pair")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["team", "kind", "is_deleted"], name="channel_team_kind_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["project"], name="channel_project_idx"),
        ),
        migrations.AddConstraint(
            model_name="channel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", 3)),
                fields=("project",),
                name="uniq_pm_channel_per_project",
            ),
        ),
        migrations.AddIndex(
            model_name="channelmember",
            index=models.Index(fields=["user", "channel"], name="member_user_channel_idx"),
        ),
        migrations.AddIndex(
            model_name="channelmember",
            index=models.Index(fields=["channel", "is_deleted"], name="member_channel_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="channelmember",
            constraint=models.UniqueConstraint(
                fields=("channel", "user"), name="uniq_channel_member"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["channel", "ts_sent_at"], name="msg_channel_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["thread_root", "ts_sent_at"], name="msg_thread_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["channel", "ts_updated_at"], name="msg_channel_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["channel", "task"], name="msg_channel_task_idx"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(fields=("channel", "seq"), name="uniq_channel_seq"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_thread_reply", False), ("thread_root__isnull", False), _connector="OR"
                ),
                name="thread_reply_has_root",
            ),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["user", "ts_created_at"], name="flag_user_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.UniqueConstraint(fields=("user", "message"), name="uniq_flag"),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["message"], name="attachment_message_idx"),
        ),
        migrations.AddIndex(
            model_name="messagemention",
            index=models.Index(
                fields=["mentioned_user", "ts_created_at"], name="mention_user_ts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagemention",
            index=models.Index(fields=["message"], name="mention_message_idx"),
        ),
        migrations.AddConstraint(
            model_name="messagemention",
            constraint=models.UniqueConstraint(
                fields=("message", "mentioned_user"), name="uniq_message_mention"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["message"], name="reaction_message_idx"),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "ts_updated_at"], name="reaction_msg_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                fields=("message", "user", "emoji"), name="uniq_message_reaction"
            ),
        ),
        migrations.AddIndex(
            model_name="pin",
            index=models.Index(fields=["user", "ts_created_at"], name="pin_user_ts_idx"),
        ),
        migrations.AddConstraint(
            model_name="pin",
            constraint=models.UniqueConstraint(fields=("user", "channel"), name="uniq_pin"),
        ),
        migrations.AddIndex(
            model_name="readcursor",
            index=models.Index(fields=["user", "channel"], name="cursor_user_channel_idx"),
        ),
        migrations.AddConstraint(
            model_name="readcursor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("thread_root__isnull", True)),
                fields=("user", "channel"),
                name="uniq_main_cursor",
            ),
        ),
        migrations.AddConstraint(
            model_name="readcursor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("thread_root__isnull", False)),
                fields=("user", "channel", "thread_root"),
                name="uniq_thread_cursor",
            ),
        ),
    ]
