# Generated by Django 5.1.5 on 2026-05-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0123_unified_messaging_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="thread_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_descendants",
                to="origin.message",
            ),
        ),
    ]
