# Generated by Django 5.1.5 on 2026-05-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0133_alter_activity_actor_alter_activity_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="surface_type",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="origin.channel",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="origin.message",
            ),
        ),
    ]
