# Generated by Django 5.2.13 on 2026-05-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0134_activity_surface_type_alter_activity_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatnoteattachmentfact",
            name="chat_id",
        ),
        migrations.RemoveField(
            model_name="chatnoteattachmentfact",
            name="thread_id",
        ),
        migrations.RemoveField(
            model_name="chatnotemaster",
            name="chat_id",
        ),
        migrations.RemoveField(
            model_name="chatnotemaster",
            name="thread_id",
        ),
        migrations.AddField(
            model_name="chatnoteattachmentfact",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_note_attachments",
                to="origin.channel",
            ),
        ),
        migrations.AddField(
            model_name="chatnoteattachmentfact",
            name="thread_root_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatnotemaster",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_notes",
                to="origin.channel",
            ),
        ),
        migrations.AddField(
            model_name="chatnotemaster",
            name="thread_root_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
