# Generated by Django 5.2.13 on 2026-06-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0135_chat_note_channel_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="category_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="muted_targets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
