# Generated by Django 5.1.5 on 2026-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origin", "0138_teaminvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskactivity",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("title_changed", "Title changed"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("effort_changed", "Effort changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("reporter_changed", "Reporter changed"),
                    ("due_date_changed", "Due date changed"),
                    ("description_edited", "Description edited"),
                    ("tags_changed", "Tags changed"),
                    ("parent_changed", "Parent changed"),
                    ("milestone_changed", "Milestone changed"),
                    ("sprint_changed", "Sprint changed"),
                    ("closed", "Closed"),
                    ("reopened", "Reopened"),
                    ("deleted", "Deleted"),
                    ("attachment_added", "Attachment added"),
                    ("attachment_removed", "Attachment removed"),
                    ("comment_added", "Comment added"),
                    ("comment_edited", "Comment edited"),
                    ("comment_deleted", "Comment deleted"),
                    ("milestone_assignee_added", "Milestone assignee added"),
                    ("milestone_assignee_removed", "Milestone assignee removed"),
                    ("pr_comment_added", "PR comment added"),
                    ("pr_linked", "PR linked"),
                ],
                max_length=48,
            ),
        ),
    ]
