# Generated by Django 5.2.15 on 2026-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0142_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskmaster',
            index=models.Index(fields=['team', 'project', 'parent_task_id'], name='taskmaster_parent_task_idx'),
        ),
    ]
