# Generated by Django 5.2.15 on 2026-07-07 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0143_taskmaster_taskmaster_parent_task_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnotemaster',
            name='folder_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonalNoteFolder',
            fields=[
                ('folder_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('parent_folder_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
            ],
        ),
    ]
