# Generated by Django 5.2.15 on 2026-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0144_personalnotemaster_folder_id_personalnotefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spotlight_web_search_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
