# Generated by Django 5.2.15 on 2026-07-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("origin", "0146_flag_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembers",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_members",
                to="origin.projectmaster",
            ),
        ),
        migrations.AlterField(
            model_name="projecttags",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_tags",
                to="origin.projectmaster",
            ),
        ),
        migrations.AlterField(
            model_name="taskattachments",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_attachments",
                to="origin.taskmaster",
            ),
        ),
        migrations.AlterField(
            model_name="taskbodyattachmentfact",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="origin.taskmaster"
            ),
        ),
        migrations.AlterField(
            model_name="taskcommentmentionfact",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="origin.taskmaster"
            ),
        ),
        migrations.AlterField(
            model_name="taskcommentreactionfact",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comment_reactions",
                to="origin.taskmaster",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomments",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comments",
                to="origin.taskmaster",
            ),
        ),
        migrations.AlterField(
            model_name="taskmaster",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_tasks_master",
                to="origin.projectmaster",
            ),
        ),
        migrations.AlterField(
            model_name="tasknoteattachmentfact",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="origin.taskmaster"
            ),
        ),
        migrations.AlterField(
            model_name="tasknotemaster",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_task_notes",
                to="origin.projectmaster",
            ),
        ),
        migrations.AlterField(
            model_name="tasknotemaster",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="origin.taskmaster"
            ),
        ),
        migrations.AlterField(
            model_name="tasktags",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_tags",
                to="origin.taskmaster",
            ),
        ),
    ]
