# Generated by Django 5.2.15 on 2026-07-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0147_project_delete_cascades_task_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammaster',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('max', 'Max'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('max', 'Max'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=16),
        ),
    ]
