# Generated by Django 5.2.15 on 2026-07-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0148_teammaster_plan_alter_customuser_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
