# Generated by Django 5.2.16 on 2026-07-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0149_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammaster',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
