# Generated by Django 5.2.16 on 2026-07-17 15:54

import django.db.models.deletion
import origin.models.common.team_emoji_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0150_teammaster_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEmojiMaster',
            fields=[
                ('emoji_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=500, upload_to=origin.models.common.team_emoji_models._team_emoji_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_emoji', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_emoji', to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('team', 'name'), name='uniq_active_team_emoji_name')],
            },
        ),
    ]
