# Generated by Django 5.2.16 on 2026-07-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0151_teamemojimaster'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teamemojimaster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('team__isnull', True)), fields=('name',), name='uniq_active_global_emoji_name'),
        ),
    ]
