# Generated by Django 5.2.16 on 2026-07-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0154_message_sender_ts_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=60)),
                ('body', models.JSONField()),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_task_templates', to='origin.projectmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_task_templates', to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'template_name'), name='unique_project_task_template')],
            },
        ),
    ]
