# Generated by Django 5.2.16 on 2026-07-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0155_projecttasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='default_milestone_template',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='default_task_template',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
