# Generated by Django 5.2.16 on 2026-07-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0156_projectmaster_default_milestone_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='task_field_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
