# Generated by Django 5.2.16 on 2026-07-20 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0157_projectmaster_task_field_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('label_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('text_color', models.CharField(max_length=10)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_labels', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_labels', to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLabelAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='origin.projectlabel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assignments', to='origin.projectmaster')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectlabel',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='uniq_project_label'),
        ),
        migrations.AddConstraint(
            model_name='projectlabelassignment',
            constraint=models.UniqueConstraint(fields=('label', 'project'), name='uniq_project_label_assignment'),
        ),
    ]
