# Generated by Django 5.2.16 on 2026-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0158_projectlabel_projectlabelassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='member_role',
            field=models.CharField(default='viewer', max_length=16),
        ),
    ]
