# Generated by Django 5.2.16 on 2026-07-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0159_teammembers_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembers',
            name='member_role',
            field=models.CharField(default='viewer', max_length=16),
        ),
    ]
