# Generated by Django 5.2.16 on 2026-07-24 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0160_projectmembers_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='custom_field_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectCustomField',
            fields=[
                ('field_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=40)),
                ('field_type', models.CharField(max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_fields', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_custom_fields', to='origin.projectmaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_custom_fields', to='origin.teammaster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'field_name'), name='unique_project_custom_field')],
            },
        ),
    ]
