# Generated by Django 5.2.16 on 2026-07-24 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0161_taskmaster_custom_field_values_projectcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborating_tasks_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
