# Generated by Django 5.2.16 on 2026-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0164_alter_preferred_llm_provider_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_llm_effort',
            field=models.CharField(blank=True, default='', help_text="'low', 'medium', 'high', or '' to derive from the legacy model pref.", max_length=16),
        ),
    ]
