# Generated by Django 5.2.16 on 2026-07-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0166_connectedaccount_multi_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
