# Generated by Django 5.2.16 on 2026-07-30 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("origin", "0167_pushsubscription_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSavedTaskFilter",
            fields=[
                ("filter_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("filter_name", models.CharField(max_length=60)),
                ("filters", models.JSONField(default=dict)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_saved_task_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_saved_task_filters",
                        to="origin.projectmaster",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_saved_task_filters",
                        to="origin.teammaster",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "filter_name"), name="unique_project_saved_task_filter"
                    )
                ],
            },
        ),
    ]
