# Generated by Django 5.2.16 on 2026-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0168_projectsavedtaskfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
