# Generated by Django 5.2.16 on 2026-07-31 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0169_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnotefolder',
            name='scope',
            field=models.CharField(db_index=True, default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='personalnotefolder',
            name='visibility',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='NoteFolderTag',
            fields=[
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFolderTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='origin.personalnotefolder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_links', to='origin.notefoldertag')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('via_group_type', models.CharField(blank=True, max_length=16, null=True)),
                ('via_group_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='origin.personalnotefolder')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_note_folder_permissions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='origin.teammaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_note_folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('folder', 'user'), name='uniq_note_folder_permission')],
            },
        ),
        migrations.AddConstraint(
            model_name='notefoldertag',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='uniq_note_folder_tag_per_team'),
        ),
        migrations.AddConstraint(
            model_name='notefoldertaglink',
            constraint=models.UniqueConstraint(fields=('folder', 'tag'), name='uniq_note_folder_tag_link'),
        ),
    ]
