# Generated by Django 5.2.16 on 2026-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0170_note_team_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefoldertag',
            name='text_color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
