# Generated by Django 5.2.16 on 2026-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0172_migrate_team_note_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='digest_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
