# Generated by Django 5.2.16 on 2026-08-01 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0173_user_digest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailNotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='origin.activity')),
                ('inbox_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='origin.inboxitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'ts_created_at'], name='origin_emai_status_85823f_idx'), models.Index(fields=['user', 'status'], name='origin_emai_user_id_3fc4bf_idx'), models.Index(fields=['user', 'status', 'sent_at'], name='origin_emai_user_id_1ca565_idx')],
            },
        ),
    ]
