# Generated by Django 5.2.16 on 2026-08-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0174_email_channel_foundations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(max_length=16)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
