# Generated by Django 5.2.16 on 2026-08-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0175_email_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_digest_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
