# Generated by Django 5.2.16 on 2026-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0176_user_email_digest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='guide_seeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
