# Generated by Django 5.2.16 on 2026-08-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0177_team_member_guide_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='member_role',
            field=models.CharField(default='viewer', max_length=16),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_invites', to='origin.projectmaster'),
        ),
    ]
