# Generated by Django 5.2.16 on 2026-08-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0180_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='channel_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='project_ids',
            field=models.JSONField(default=list),
        ),
    ]
