# Generated by Django 5.2.16 on 2026-08-04 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0182_tier_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('declined', 'declined'), ('revoked', 'revoked')], db_index=True, default='pending', max_length=16)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_connection_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_connection_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_requests_sent', to='origin.teammaster')),
                ('team_hi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_as_hi', to='origin.teammaster')),
                ('team_lo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections_as_lo', to='origin.teammaster')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('channel', 'channel'), ('project', 'project'), ('note_folder', 'note folder')], max_length=16)),
                ('object_id', models.CharField(max_length=64)),
                ('role_ceiling', models.CharField(default='viewer', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('declined', 'declined'), ('revoked', 'revoked')], db_index=True, default='pending', max_length=16)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_grants_accepted', to=settings.AUTH_USER_MODEL)),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_grants_received', to='origin.teammaster')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_grants_offered', to=settings.AUTH_USER_MODEL)),
                ('owner_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_grants_given', to='origin.teammaster')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='origin.teamconnection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamconnection',
            constraint=models.UniqueConstraint(fields=('team_lo', 'team_hi'), name='uniq_team_connection'),
        ),
        migrations.AddConstraint(
            model_name='teamconnection',
            constraint=models.CheckConstraint(condition=models.Q(('team_lo', models.F('team_hi')), _negated=True), name='team_connection_not_self'),
        ),
        migrations.AddIndex(
            model_name='externalgrant',
            index=models.Index(fields=['object_type', 'object_id', 'status'], name='external_grant_object_idx'),
        ),
        migrations.AddIndex(
            model_name='externalgrant',
            index=models.Index(fields=['guest_team', 'status'], name='external_grant_guest_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalgrant',
            constraint=models.UniqueConstraint(fields=('guest_team', 'object_type', 'object_id'), name='uniq_external_grant'),
        ),
        migrations.AddConstraint(
            model_name='externalgrant',
            constraint=models.CheckConstraint(condition=models.Q(('owner_team', models.F('guest_team')), _negated=True), name='external_grant_not_self'),
        ),
    ]
