# Generated by Django 5.2.16 on 2026-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0183_team_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
