# Generated by Django 5.2.16 on 2026-08-05 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0184_channel_is_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='origin.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('cancelled_at__isnull', True), ('fired_at__isnull', True)), fields=['remind_at'], name='reminder_due_idx'), models.Index(fields=['user', 'remind_at'], name='reminder_user_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True), ('fired_at__isnull', True)), fields=('user', 'message'), name='uniq_pending_reminder')],
            },
        ),
    ]
