# Generated by Django 5.2.16 on 2026-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0185_messagereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
