# Generated by Django 5.2.16 on 2026-08-08 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0186_profile_location_and_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoSchedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('rrule', models.CharField(max_length=512)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_materialized_date', models.DateField(blank=True, null=True)),
                ('ts_created_at', models.DateTimeField(auto_now_add=True)),
                ('ts_updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='origin.todocategory')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_schedules', to='origin.teammaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='todo_sched_user_active_idx')],
            },
        ),
    ]
