"""
Unified serializers for the new chat schema.

One canonical `MessageSerializer` for all channel kinds (DM=1, GM=2, PM=3,
MDM=4). PM-specific fields (taskId, displayId, taskStatus, taskCommentCount)
are top-level, derived off the `task` FK — the legacy `pm_serializers` vs
`dm_serializers` divergence (where PM had extra fields and DM/GM/MDM returned
slightly different timestamp shapes) does not exist here.

DRF's default DateTimeField already emits ISO 8601 strings, so no explicit
DATETIME_FORMAT setting is required. The legacy code's `str(msg.ts_sent_at)`
calls were a regression that this rewrite eliminates by going back to the
DRF default.
"""

from django.db.models import Count, IntegerField, OuterRef, Subquery
from django.db.models.functions import Coalesce
from rest_framework import serializers

from origin.models.chat.unified_models import (
    Activity,
    Channel,
    ChannelKind,
    ChannelMember,
    Flag,
    Message,
    MessageAttachment,
    MessageMention,
    MessageReaction,
    Pin,
    ReadCursor,
)


class UserLiteSerializer(serializers.Serializer):
    """Compact user representation embedded in messages/reactions/etc.

    Mirrors the legacy wire shape so frontends rendering avatars don't
    need to re-fetch user info. Not a ModelSerializer because it draws
    from `CustomUser` but exposes a stable contract: just userId/name/
    email/avatar. Other fields (`tsLastSeen`, etc.) the legacy DM
    serializer returned as empty strings — keep them for compatibility
    while the FE finishes migrating.
    """

    userId = serializers.UUIDField(source="id", read_only=True)
    userName = serializers.CharField(source="username", read_only=True)
    userEmail = serializers.EmailField(source="email", read_only=True)
    avatarImgPath = serializers.CharField(source="profile_image_file_name", read_only=True)
    isSystemUser = serializers.BooleanField(source="is_system_user", read_only=True)


class MessageReactionSerializer(serializers.ModelSerializer):
    """One reaction row, embedded inside `MessageSerializer.reactions`.

    The legacy ReactionFact serializer keyed reactions by an integer
    `reaction_id` that auto-incremented per message. The new shape uses
    the row UUID directly — simpler and conflict-free.
    """

    id = serializers.UUIDField(read_only=True)
    user = UserLiteSerializer(read_only=True)
    emoji = serializers.CharField()
    tsSent = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageReaction
        fields = ["id", "user", "emoji", "tsSent"]


class MessageMentionSerializer(serializers.ModelSerializer):
    """One mention row.

    `viaGroup` is the UUID of a mention-group (`@engineering`, `@everyone`),
    null for direct `@user` mentions. The frontend uses this to render
    `@you via @engineering` in the inbox.
    """

    id = serializers.UUIDField(read_only=True)
    mentionedUserId = serializers.UUIDField(source="mentioned_user_id", read_only=True)
    viaGroupId = serializers.UUIDField(source="via_group_id", read_only=True, allow_null=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageMention
        fields = ["id", "mentionedUserId", "viaGroupId", "tsCreated"]


class MessageAttachmentSerializer(serializers.ModelSerializer):
    """One attachment row. The file URL is generated by DRF from the
    storage backend (S3 / disk / etc) at request time."""

    id = serializers.UUIDField(read_only=True)
    fileUrl = serializers.FileField(source="file", read_only=True)
    mime = serializers.CharField()
    sizeBytes = serializers.IntegerField(source="size_bytes")
    uploader = UserLiteSerializer(read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageAttachment
        fields = ["id", "fileUrl", "mime", "sizeBytes", "uploader", "tsCreated"]


class MessageSerializer(serializers.ModelSerializer):
    """ONE serializer for every channel kind.

    Wire-shape contract (camelCase, ISO 8601 timestamps, UUIDs as strings):

        {
          "id": "<uuid>",                  // primary stable id
          "channelId": "<uuid>",
          "channelKind": 1|2|3|4,
          "seq": <int>,                    // legacy per-channel message_id
          "sender": <UserLite>,
          "body": <JSON>,                  // blocknote-style block array
          "bodyText": <str>,               // first-line preview
          "parentId": "<uuid>" | null,
          "threadRootId": "<uuid>" | null,
          "isThreadReply": <bool>,
          "replyCount": <int>,
          "reactions": [<MessageReaction>, ...],
          "mentions": [<MessageMention>, ...],
          "attachments": [<MessageAttachment>, ...],
          "metadata": { ... },             // PM: {taskId, displayId, taskStatus, taskCommentCount}
          "editedAt": "<iso>" | null,
          "deletedAt": "<iso>" | null,
          "tsSent": "<iso>",
          "tsUpdated": "<iso>",
        }

    PM-specific fields are in `metadata`. No per-kind divergence anywhere.
    """

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    # SerializerMethodField rather than `source="channel.kind"` to avoid a
    # gratuitous join when the channel is already loaded via select_related.
    channelKind = serializers.SerializerMethodField()
    sender = UserLiteSerializer(read_only=True)
    seq = serializers.IntegerField(read_only=True)
    body = serializers.JSONField()
    bodyText = serializers.CharField(source="body_text")
    parentId = serializers.UUIDField(source="parent_id", read_only=True, allow_null=True)
    threadRootId = serializers.UUIDField(source="thread_root_id", read_only=True, allow_null=True)
    isThreadReply = serializers.BooleanField(source="is_thread_reply", read_only=True)
    replyCount = serializers.IntegerField(source="reply_count", read_only=True)
    reactions = MessageReactionSerializer(many=True, read_only=True)
    mentions = MessageMentionSerializer(many=True, read_only=True)
    attachments = MessageAttachmentSerializer(many=True, read_only=True)
    metadata = serializers.JSONField()
    # PM-only FK to the legacy `TaskMaster` row this message renders.
    # The FE PM bubble path (MessageBubble.handleOpenTaskClick,
    # BubbleUnderBar's task-status chip, `cursor: pointer` on the body)
    # gates on this being non-null. Other kinds leave it null.
    taskId = serializers.IntegerField(source="task_id", read_only=True, allow_null=True)
    # PM task display fields derived off the `task` FK. `displayId` is
    # the human-readable code ("PRJ-42") the legacy PM views also
    # emit; `taskStatus` mirrors the colored-chip text in the bubble
    # under-bar ("Open" / "Closed" / etc.). Both null when the message
    # isn't linked to a task. Use SerializerMethodField so we can
    # null-coalesce without forcing a DB hit when `task` is unset.
    displayId = serializers.SerializerMethodField()
    taskStatus = serializers.SerializerMethodField()
    # Number of LIVE (non-deleted) task comments on the PM task this
    # header renders — the authoritative count the thread's "Comments"
    # tab shows (`loadTaskComments` filters `is_deleted=False`). The FE
    # bubble chip uses this instead of `replyCount`: `reply_count`
    # counts every thread reply, so it over-counts legacy free-form
    # replies that were never task comments AND under-counts when a
    # comment→thread-reply mirror failed. Null unless the view annotated
    # `task_comment_count` (see `annotate_task_comment_count`); the FE
    # falls back to `replyCount` for un-annotated / pre-change rows.
    taskCommentCount = serializers.SerializerMethodField()
    editedAt = serializers.DateTimeField(source="edited_at", read_only=True, allow_null=True)
    deletedAt = serializers.DateTimeField(source="deleted_at", read_only=True, allow_null=True)
    tsSent = serializers.DateTimeField(source="ts_sent_at", read_only=True)
    tsUpdated = serializers.DateTimeField(source="ts_updated_at", read_only=True)

    class Meta:
        model = Message
        fields = [
            "id",
            "channelId",
            "channelKind",
            "sender",
            "seq",
            "body",
            "bodyText",
            "parentId",
            "threadRootId",
            "isThreadReply",
            "replyCount",
            "reactions",
            "mentions",
            "attachments",
            "metadata",
            "taskId",
            "displayId",
            "taskStatus",
            "taskCommentCount",
            "editedAt",
            "deletedAt",
            "tsSent",
            "tsUpdated",
        ]

    def get_channelKind(self, obj):
        # `obj.channel` may be a deferred FK; channel_id_kind cache would
        # be ideal, but for now we accept the second column read. Views
        # using select_related("channel") avoid the extra query.
        return obj.channel.kind if obj.channel else None

    def get_displayId(self, obj):
        # `TaskMaster.display_id` is a property: "<project.code>-<n>"
        # when both are present, else "#<task_id>". Views serving PM
        # messages should `select_related("task", "task__project")` so
        # this doesn't N+1 the project lookup.
        return obj.task.display_id if getattr(obj, "task", None) else None

    def get_taskStatus(self, obj):
        return obj.task.status if getattr(obj, "task", None) else None

    @staticmethod
    def annotate_task_comment_count(qs):
        """Annotate `task_comment_count` = live (non-deleted) `TaskComments`
        for each message's linked PM task, via ONE correlated subquery so
        `get_taskCommentCount` reads it without an N+1.

        Every view that serializes PM task-header messages must apply this:
        the message-delta + single-message endpoints (through
        `_prefetched_messages`) and the channel list/detail
        `_latest_message`. Harmlessly 0 for non-task rows (`task_id` NULL →
        empty subquery), and only surfaced on top-level task headers.
        """
        from origin.models.task.task_models import TaskComments

        comment_count_sq = (
            TaskComments.objects.filter(task_id=OuterRef("task_id"), is_deleted=False)
            .order_by()
            .values("task_id")
            .annotate(c=Count("id"))
            .values("c")
        )
        return qs.annotate(
            task_comment_count=Coalesce(
                Subquery(comment_count_sq, output_field=IntegerField()), 0
            )
        )

    def get_taskCommentCount(self, obj):
        # Only meaningful on a top-level PM task-header message (the one
        # the FE renders the "N comments" chip on). Thread replies —
        # including the mirrored comments themselves, which carry
        # `task_id` — return None so no per-reply chip is implied, and
        # non-task rows (DM/GM/MDM) return None. When the serving view
        # didn't annotate (`getattr` default), also None so the FE falls
        # back to `replyCount`.
        if obj.is_thread_reply or obj.task_id is None:
            return None
        return getattr(obj, "task_comment_count", None)


class ChannelMemberSerializer(serializers.ModelSerializer):
    """One member row. Used inside ChannelSerializer and for the
    POST/DELETE /api/v3/channels/{id}/members/ endpoints."""

    id = serializers.UUIDField(read_only=True)
    userId = serializers.UUIDField(source="user_id", read_only=True)
    role = serializers.CharField()
    tsJoined = serializers.DateTimeField(source="ts_joined_at", read_only=True)
    # User display fields denormalized into the member row so the FE
    # sidebar / DM partner resolution doesn't need a parallel
    # `/api/v2/team/getTeamMembers/` fetch to render avatars + names.
    # The legacy `AllChatProps.dmPartnerUser` shape carried these
    # inline; keep parity here so the v3 → legacy adapter can populate
    # them without a join.
    user = UserLiteSerializer(read_only=True)

    class Meta:
        model = ChannelMember
        fields = ["id", "userId", "role", "tsJoined", "user"]


class ChannelSerializer(serializers.ModelSerializer):
    """One channel row. The chat-list endpoint returns a list of these.

    `latestMessage` is denormalized at serialize-time (via the view's
    annotated queryset) so the chat-list rows render without per-row
    follow-up queries. `unreadCount` derives from the user's ReadCursor;
    see ChannelListView for the prefetch wiring.
    """

    id = serializers.UUIDField(read_only=True)
    kind = serializers.IntegerField(read_only=True)
    title = serializers.CharField()
    profileImageUrl = serializers.CharField(source="profile_image_url")
    projectId = serializers.IntegerField(source="project_id", read_only=True, allow_null=True)
    ownerId = serializers.UUIDField(source="owner_id", read_only=True, allow_null=True)
    isPrivate = serializers.BooleanField(source="is_private")
    # The legacy per-kind integer chat id this channel was backfilled
    # from. Exposed during the v3 cutover so FE entry points that still
    # carry legacy ids (Spotlight / ChatSearch / activity & flagged
    # sidebars whose data still flows through `/api/v2/...`) can resolve
    # the v3 UUID via a client-side `legacyChatId === N` lookup against
    # the cached channel list. Null for v3-native channels created
    # post-cutover.
    legacyChatId = serializers.IntegerField(
        source="legacy_chat_id", read_only=True, allow_null=True
    )
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)
    tsUpdated = serializers.DateTimeField(source="ts_updated_at", read_only=True)

    # Populated by the view's annotated queryset; see ChannelListView.
    latestMessage = serializers.SerializerMethodField()
    unreadCount = serializers.SerializerMethodField()
    # DM partner identity + MDM member avatars are resolved client-side
    # from this roster (FE `resolveDmPartner` / `membersToMdmMembers`).
    # Without it on the chat-list payload, DM rows can't render the
    # partner's name/avatar until the channel is opened (which lazily
    # fetches members). Only emitted for DM/MDM — GM/PM rows render from
    # `title`, and GM rosters can be large, so they're skipped on this
    # hot path. The view attaches `active_members` (one batched query for
    # all DM/MDM rows); falls back to a per-channel query otherwise.
    members = serializers.SerializerMethodField()
    # DM partner identity resolved SERVER-SIDE from request.user. The
    # client-side `resolveDmPartner(members, currentUserId)` needs both a
    # members snapshot AND a non-null current-user id at the moment the
    # chat list is built — both racy on first load (the loader fires
    # before `myself.userId` hydrates, and stale-closure re-fires can
    # clobber a good result), which left DM rows with a blank name while
    # GM/PM (title-based) rendered fine. Resolving it here makes the DM
    # row's name + avatar deterministic regardless of FE timing. Null for
    # non-DM kinds.
    dmPartner = serializers.SerializerMethodField()

    class Meta:
        model = Channel
        fields = [
            "id",
            "kind",
            "title",
            "profileImageUrl",
            "projectId",
            "ownerId",
            "isPrivate",
            "legacyChatId",
            "latestMessage",
            "unreadCount",
            "members",
            "dmPartner",
            "tsCreated",
            "tsUpdated",
        ]

    def _active_members(self, obj):
        members = getattr(obj, "active_members", None)
        if members is None:
            members = list(obj.members.filter(is_deleted=False).select_related("user"))
        return members

    def get_dmPartner(self, obj):
        if obj.kind != ChannelKind.DM:
            return None
        members = self._active_members(obj)
        if not members:
            return None
        request = self.context.get("request")
        me = getattr(request, "user", None) if request else None
        me_id = str(me.id) if me is not None else None
        # The partner is the member who isn't the viewer; for a self-DM
        # (only member is the viewer) it's the viewer themselves, so the
        # row renders the user's own name + "(you)" badge client-side.
        partner = next((m for m in members if str(m.user_id) != me_id), None) or members[0]
        u = partner.user
        if u is None:
            return None
        return {
            "userId": str(partner.user_id),
            "userName": u.username or "",
            "userEmail": u.email or "",
            "avatarImgPath": getattr(u, "profile_image_file_name", "") or "",
        }

    def get_latestMessage(self, obj):
        msg = getattr(obj, "_latest_message", None)
        if msg is None:
            return None
        return MessageSerializer(msg, context=self.context).data

    def get_members(self, obj):
        if obj.kind not in (ChannelKind.DM, ChannelKind.MDM):
            return []
        members = getattr(obj, "active_members", None)
        if members is None:
            members = list(obj.members.filter(is_deleted=False).select_related("user"))
        return ChannelMemberSerializer(members, many=True, context=self.context).data

    def get_unreadCount(self, obj):
        # Annotated by the view as the number of messages whose `seq` is
        # greater than the user's last_read seq. Falls back to 0 if the
        # view didn't annotate (e.g. anonymous / non-member access).
        return getattr(obj, "_unread_count", 0)


class ReadCursorSerializer(serializers.ModelSerializer):
    """One cursor. `threadRootId` is null for the main-timeline cursor."""

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    threadRootId = serializers.UUIDField(source="thread_root_id", read_only=True, allow_null=True)
    lastReadMessageId = serializers.UUIDField(
        source="last_read_message_id", read_only=True, allow_null=True
    )
    lastReadAt = serializers.DateTimeField(source="last_read_at", read_only=True)

    class Meta:
        model = ReadCursor
        fields = ["id", "channelId", "threadRootId", "lastReadMessageId", "lastReadAt"]


class PinSerializer(serializers.ModelSerializer):
    """One pin row."""

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = Pin
        fields = ["id", "channelId", "tsCreated"]


class FlagSerializer(serializers.ModelSerializer):
    """One flag row."""

    id = serializers.UUIDField(read_only=True)
    messageId = serializers.UUIDField(source="message_id", read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)
    # Null while active; set when the user marks the flag done.
    completedAt = serializers.DateTimeField(source="completed_at", read_only=True)

    class Meta:
        model = Flag
        fields = ["id", "messageId", "tsCreated", "completedAt"]


class ActivitySerializer(serializers.ModelSerializer):
    """One activity-feed entry. Surfaces the recipient's view of an
    event triggered by `actor` (someone reacted / replied / @mentioned).

    Wire fields stay camelCase to match the message/reaction shape the
    FE already consumes. `message` and `actor` are embedded so the
    sidebar can render the row without a follow-up fetch.
    """

    id = serializers.UUIDField(read_only=True)
    activityType = serializers.IntegerField(source="activity_type", read_only=True)
    recipientUserId = serializers.UUIDField(source="recipient_id", read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    channelKind = serializers.SerializerMethodField()
    messageId = serializers.UUIDField(source="message_id", read_only=True)
    # Null for channel-backed activities; the legacy chat_type namespace
    # (5=task body, 6/7/8=notes) for channel-less surface mentions. The
    # FE derives the row's chat_type from `surfaceType ?? channelKind`,
    # and reads the routing ids (taskId / projectId / noteId / chatId)
    # from `meta`.
    surfaceType = serializers.IntegerField(source="surface_type", read_only=True, allow_null=True)
    actor = UserLiteSerializer(read_only=True, allow_null=True)
    # `allow_null`: surface activities have no backing Message.
    message = MessageSerializer(read_only=True, allow_null=True)
    isRead = serializers.BooleanField(source="is_read", read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = Activity
        fields = [
            "id",
            "activityType",
            "recipientUserId",
            "channelId",
            "channelKind",
            "messageId",
            "surfaceType",
            "actor",
            "message",
            "meta",
            "isRead",
            "tsCreated",
        ]

    def get_channelKind(self, obj):
        return obj.channel.kind if obj.channel else None


class DeltaEnvelopeSerializer(serializers.Serializer):
    """Wraps a delta-sync response.

    The frontend persists `serverTime` as the `since` for the next sync
    request. `forceFullReload=True` tells the client to clear its IDB
    for this channel before applying `data`. `data` shape is endpoint-
    specific — `MessagesDeltaView` returns
        {messages: [...], deletes: [...], reactions_changed: [...]}
    while `ChannelListView` returns
        {channels: [...]}
    """

    serverTime = serializers.DateTimeField()
    forceFullReload = serializers.BooleanField(default=False)
    data = serializers.JSONField()
