"""
Unified serializers for the new chat schema.

One canonical `MessageSerializer` for all channel kinds (DM=1, GM=2, PM=3,
MDM=4). PM-specific fields (taskId, displayId, taskStatus, taskCommentCount)
ride in `metadata` JSON instead of top-level columns — the legacy
`pm_serializers` vs `dm_serializers` divergence (where PM had extra fields
and DM/GM/MDM returned slightly different timestamp shapes) does not exist
here.

DRF's default DateTimeField already emits ISO 8601 strings, so no explicit
DATETIME_FORMAT setting is required. The legacy code's `str(msg.ts_sent_at)`
calls were a regression that this rewrite eliminates by going back to the
DRF default.
"""

from rest_framework import serializers

from origin.models.chat.unified_models import (
    Channel,
    ChannelMember,
    Flag,
    Message,
    MessageAttachment,
    MessageMention,
    MessageReaction,
    Pin,
    ReadCursor,
)


class UserLiteSerializer(serializers.Serializer):
    """Compact user representation embedded in messages/reactions/etc.

    Mirrors the legacy wire shape so frontends rendering avatars don't
    need to re-fetch user info. Not a ModelSerializer because it draws
    from `CustomUser` but exposes a stable contract: just userId/name/
    email/avatar. Other fields (`tsLastSeen`, etc.) the legacy DM
    serializer returned as empty strings — keep them for compatibility
    while the FE finishes migrating.
    """

    userId = serializers.UUIDField(source="id", read_only=True)
    userName = serializers.CharField(source="username", read_only=True)
    userEmail = serializers.EmailField(source="email", read_only=True)
    avatarImgPath = serializers.CharField(source="profile_image_file_name", read_only=True)
    isSystemUser = serializers.BooleanField(source="is_system_user", read_only=True)


class MessageReactionSerializer(serializers.ModelSerializer):
    """One reaction row, embedded inside `MessageSerializer.reactions`.

    The legacy ReactionFact serializer keyed reactions by an integer
    `reaction_id` that auto-incremented per message. The new shape uses
    the row UUID directly — simpler and conflict-free.
    """

    id = serializers.UUIDField(read_only=True)
    user = UserLiteSerializer(read_only=True)
    emoji = serializers.CharField()
    tsSent = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageReaction
        fields = ["id", "user", "emoji", "tsSent"]


class MessageMentionSerializer(serializers.ModelSerializer):
    """One mention row.

    `viaGroup` is the UUID of a mention-group (`@engineering`, `@everyone`),
    null for direct `@user` mentions. The frontend uses this to render
    `@you via @engineering` in the inbox.
    """

    id = serializers.UUIDField(read_only=True)
    mentionedUserId = serializers.UUIDField(source="mentioned_user_id", read_only=True)
    viaGroupId = serializers.UUIDField(source="via_group_id", read_only=True, allow_null=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageMention
        fields = ["id", "mentionedUserId", "viaGroupId", "tsCreated"]


class MessageAttachmentSerializer(serializers.ModelSerializer):
    """One attachment row. The file URL is generated by DRF from the
    storage backend (S3 / disk / etc) at request time."""

    id = serializers.UUIDField(read_only=True)
    fileUrl = serializers.FileField(source="file", read_only=True)
    mime = serializers.CharField()
    sizeBytes = serializers.IntegerField(source="size_bytes")
    uploader = UserLiteSerializer(read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = MessageAttachment
        fields = ["id", "fileUrl", "mime", "sizeBytes", "uploader", "tsCreated"]


class MessageSerializer(serializers.ModelSerializer):
    """ONE serializer for every channel kind.

    Wire-shape contract (camelCase, ISO 8601 timestamps, UUIDs as strings):

        {
          "id": "<uuid>",                  // primary stable id
          "channelId": "<uuid>",
          "channelKind": 1|2|3|4,
          "seq": <int>,                    // legacy per-channel message_id
          "sender": <UserLite>,
          "body": <JSON>,                  // blocknote-style block array
          "bodyText": <str>,               // first-line preview
          "parentId": "<uuid>" | null,
          "threadRootId": "<uuid>" | null,
          "isThreadReply": <bool>,
          "replyCount": <int>,
          "reactions": [<MessageReaction>, ...],
          "mentions": [<MessageMention>, ...],
          "attachments": [<MessageAttachment>, ...],
          "metadata": { ... },             // PM: {taskId, displayId, taskStatus, taskCommentCount}
          "editedAt": "<iso>" | null,
          "deletedAt": "<iso>" | null,
          "tsSent": "<iso>",
          "tsUpdated": "<iso>",
        }

    PM-specific fields are in `metadata`. No per-kind divergence anywhere.
    """

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    # SerializerMethodField rather than `source="channel.kind"` to avoid a
    # gratuitous join when the channel is already loaded via select_related.
    channelKind = serializers.SerializerMethodField()
    sender = UserLiteSerializer(read_only=True)
    seq = serializers.IntegerField(read_only=True)
    body = serializers.JSONField()
    bodyText = serializers.CharField(source="body_text")
    parentId = serializers.UUIDField(source="parent_id", read_only=True, allow_null=True)
    threadRootId = serializers.UUIDField(source="thread_root_id", read_only=True, allow_null=True)
    isThreadReply = serializers.BooleanField(source="is_thread_reply", read_only=True)
    replyCount = serializers.IntegerField(source="reply_count", read_only=True)
    reactions = MessageReactionSerializer(many=True, read_only=True)
    mentions = MessageMentionSerializer(many=True, read_only=True)
    attachments = MessageAttachmentSerializer(many=True, read_only=True)
    metadata = serializers.JSONField()
    editedAt = serializers.DateTimeField(source="edited_at", read_only=True, allow_null=True)
    deletedAt = serializers.DateTimeField(source="deleted_at", read_only=True, allow_null=True)
    tsSent = serializers.DateTimeField(source="ts_sent_at", read_only=True)
    tsUpdated = serializers.DateTimeField(source="ts_updated_at", read_only=True)

    class Meta:
        model = Message
        fields = [
            "id",
            "channelId",
            "channelKind",
            "sender",
            "seq",
            "body",
            "bodyText",
            "parentId",
            "threadRootId",
            "isThreadReply",
            "replyCount",
            "reactions",
            "mentions",
            "attachments",
            "metadata",
            "editedAt",
            "deletedAt",
            "tsSent",
            "tsUpdated",
        ]

    def get_channelKind(self, obj):
        # `obj.channel` may be a deferred FK; channel_id_kind cache would
        # be ideal, but for now we accept the second column read. Views
        # using select_related("channel") avoid the extra query.
        return obj.channel.kind if obj.channel else None


class ChannelMemberSerializer(serializers.ModelSerializer):
    """One member row. Used inside ChannelSerializer and for the
    POST/DELETE /api/v3/channels/{id}/members/ endpoints."""

    id = serializers.UUIDField(read_only=True)
    userId = serializers.UUIDField(source="user_id", read_only=True)
    role = serializers.CharField()
    tsJoined = serializers.DateTimeField(source="ts_joined_at", read_only=True)

    class Meta:
        model = ChannelMember
        fields = ["id", "userId", "role", "tsJoined"]


class ChannelSerializer(serializers.ModelSerializer):
    """One channel row. The chat-list endpoint returns a list of these.

    `latestMessage` is denormalized at serialize-time (via the view's
    annotated queryset) so the chat-list rows render without per-row
    follow-up queries. `unreadCount` derives from the user's ReadCursor;
    see ChannelListView for the prefetch wiring.
    """

    id = serializers.UUIDField(read_only=True)
    kind = serializers.IntegerField(read_only=True)
    title = serializers.CharField()
    profileImageUrl = serializers.CharField(source="profile_image_url")
    projectId = serializers.IntegerField(source="project_id", read_only=True, allow_null=True)
    ownerId = serializers.UUIDField(source="owner_id", read_only=True, allow_null=True)
    isPrivate = serializers.BooleanField(source="is_private")
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)
    tsUpdated = serializers.DateTimeField(source="ts_updated_at", read_only=True)

    # Populated by the view's annotated queryset; see ChannelListView.
    latestMessage = serializers.SerializerMethodField()
    unreadCount = serializers.SerializerMethodField()

    class Meta:
        model = Channel
        fields = [
            "id",
            "kind",
            "title",
            "profileImageUrl",
            "projectId",
            "ownerId",
            "isPrivate",
            "latestMessage",
            "unreadCount",
            "tsCreated",
            "tsUpdated",
        ]

    def get_latestMessage(self, obj):
        msg = getattr(obj, "_latest_message", None)
        if msg is None:
            return None
        return MessageSerializer(msg, context=self.context).data

    def get_unreadCount(self, obj):
        # Annotated by the view as the number of messages whose `seq` is
        # greater than the user's last_read seq. Falls back to 0 if the
        # view didn't annotate (e.g. anonymous / non-member access).
        return getattr(obj, "_unread_count", 0)


class ReadCursorSerializer(serializers.ModelSerializer):
    """One cursor. `threadRootId` is null for the main-timeline cursor."""

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    threadRootId = serializers.UUIDField(source="thread_root_id", read_only=True, allow_null=True)
    lastReadMessageId = serializers.UUIDField(
        source="last_read_message_id", read_only=True, allow_null=True
    )
    lastReadAt = serializers.DateTimeField(source="last_read_at", read_only=True)

    class Meta:
        model = ReadCursor
        fields = ["id", "channelId", "threadRootId", "lastReadMessageId", "lastReadAt"]


class PinSerializer(serializers.ModelSerializer):
    """One pin row."""

    id = serializers.UUIDField(read_only=True)
    channelId = serializers.UUIDField(source="channel_id", read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = Pin
        fields = ["id", "channelId", "tsCreated"]


class FlagSerializer(serializers.ModelSerializer):
    """One flag row."""

    id = serializers.UUIDField(read_only=True)
    messageId = serializers.UUIDField(source="message_id", read_only=True)
    tsCreated = serializers.DateTimeField(source="ts_created_at", read_only=True)

    class Meta:
        model = Flag
        fields = ["id", "messageId", "tsCreated"]


class DeltaEnvelopeSerializer(serializers.Serializer):
    """Wraps a delta-sync response.

    The frontend persists `serverTime` as the `since` for the next sync
    request. `forceFullReload=True` tells the client to clear its IDB
    for this channel before applying `data`. `data` shape is endpoint-
    specific — `MessagesDeltaView` returns
        {messages: [...], deletes: [...], reactions_changed: [...]}
    while `ChannelListView` returns
        {channels: [...]}
    """

    serverTime = serializers.DateTimeField()
    forceFullReload = serializers.BooleanField(default=False)
    data = serializers.JSONField()
