"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-1=c=z%cqhlgi$@+w8x3ees)q*q!hosc2lvv^=_dpln(%wipz08",
)

# Default to True so local dev (where the env var isn't set) gets
# Django's normal development behavior: relaxed cookie attrs, open
# CORS, served `/media/`, full tracebacks. Production must
# *explicitly* opt out by setting `DJANGO_DEBUG=false` (the Railway
# config already does — see docs/RAILWAY_DEPLOY.md).
#
# This matches Django's own `django-admin startproject` default and
# is what every dependent setting below assumes when it derives from
# DEBUG (AUTH_COOKIE_SECURE, CORS_ALLOW_ALL_ORIGINS, etc.).
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Required for `BLACKLIST_AFTER_ROTATION` in SIMPLE_JWT to actually
    # do anything: this app provides the OutstandingToken /
    # BlacklistedToken tables that simplejwt writes to when a refresh
    # token is rotated or a user signs out. Without it, every
    # "blacklist" call is a silent no-op and old refresh tokens stay
    # valid until natural expiration.
    "rest_framework_simplejwt.token_blacklist",
    "origin",
    "origin.search_engine",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add this line at the top
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Stashes request.user in a thread-local so post_save / post_delete
    # signals on tasks/comments/attachments can attribute activity rows
    # to the acting user. Must run AFTER AuthenticationMiddleware so
    # `request.user` is already resolved.
    "origin.middleware.current_user.CurrentUserMiddleware",
]

# CORS policy.
#
# `CORS_ALLOW_ALL_ORIGINS=True` combined with `CORS_ALLOW_CREDENTIALS=True`
# would let any site on the internet trigger credentialed requests
# against this API and have the browser attach our refresh cookie. We
# only want that during local development; in production we restrict
# to the explicit list in `CORS_ALLOWED_ORIGINS` (env-driven) so only
# our actual frontend host can talk to the API with credentials.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

# Allow credentials (cookies, authentication)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "authorization",
# ]


ROOT_URLCONF = "apis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apis.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "origin",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "172.29.30.3",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SECRET_KEY", "your_secret_key"),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

AUTH_USER_MODEL = "origin.CustomUser"


CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to the session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # Adjust as needed: "Lax", "Strict", or "None"
CSRF_COOKIE_NAME = "csrftoken"  # Default cookie name
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = (
    False  # CSRF cookie should be accessible by JavaScript (for CSRF protection)
)
CSRF_COOKIE_SAMESITE = "Lax"

# Refresh-token cookie attributes.
#
# The frontend and backend are deployed to *different* hostnames in
# production (e.g. on Railway), so every API call is a cross-site
# request from the browser's point of view. For the browser to accept
# `Set-Cookie` on those responses *and* replay the cookie on the next
# `/user/signin/refresh/` fetch, the cookie must be sent with
# `SameSite=None; Secure`. In local dev we keep `SameSite=Lax` and
# `Secure=False` because Chrome won't set a `Secure` cookie over plain
# HTTP localhost.
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"


MEDIA_URL = "/media/"  # URL prefix
# Folder where uploaded files go. Made env-driven so the production
# container can point this at a Railway Volume mount path (e.g.
# `/app/backend_django/uploads` backed by a persistent disk) without
# touching code. The default keeps local dev working unchanged.
#
# This is the MVP setup: Django serves the files directly from this
# directory (see `apis/urls.py`). When the app outgrows a single
# replica or needs CDN-quality delivery, swap the storage backend to
# `django-storages` + Cloudflare R2 / AWS S3 and drop the volume.
MEDIA_ROOT = os.environ.get(
    "DJANGO_MEDIA_ROOT",
    os.path.join(BASE_DIR, "uploads"),
)


# Search engine (OpenSearch + OpenAI embeddings).
#
# Used by `origin.search_engine` for chunk-based hybrid search across
# chats, tasks, and notes. The OpenSearch index is created by
# `python manage.py opensearch_setup` and (re)populated by
# `python manage.py opensearch_reindex`.
SEARCH_ENGINE = {
    "OPENSEARCH_HOST": os.environ.get("OPENSEARCH_HOST", "opensearch"),
    "OPENSEARCH_PORT": int(os.environ.get("OPENSEARCH_PORT", "9200")),
    "OPENSEARCH_USE_SSL": os.environ.get("OPENSEARCH_USE_SSL", "false").lower() == "true",
    # Physical index name. Increment the suffix when changing the
    # mapping or embedding model and reindexing.
    "OPENSEARCH_INDEX": os.environ.get("OPENSEARCH_INDEX", "knowledge_chunks_v1"),
    # Stable alias the app queries. Repointed at a new physical index
    # during zero-downtime migrations.
    "OPENSEARCH_ALIAS": os.environ.get("OPENSEARCH_ALIAS", "knowledge_chunks_current"),
    # OpenAI embedding configuration. `text-embedding-3-small` is the
    # MVP default: 1536-dim, cheap, multilingual-decent. If you change
    # the model or dimension, bump the index suffix and reindex.
    "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", ""),
    "OPENAI_EMBEDDING_MODEL": os.environ.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small"),
    "OPENAI_EMBEDDING_DIMENSIONS": int(os.environ.get("OPENAI_EMBEDDING_DIMENSIONS", "1536")),
    # Bulk-indexing batch size for OpenSearch _bulk requests.
    "BULK_BATCH_SIZE": int(os.environ.get("SEARCH_BULK_BATCH_SIZE", "200")),
    # OpenAI embedding batch size (max items per /v1/embeddings request).
    "EMBEDDING_BATCH_SIZE": int(os.environ.get("SEARCH_EMBEDDING_BATCH_SIZE", "100")),
    # Gemini configuration for the RAG-answer endpoint
    # (POST /api/v2/agent/ask). `gemini-2.5-flash` is the MVP default
    # — fast, cheap, supports streaming + function calling for Phase 3.
    #
    # TWO authentication modes (pick exactly one):
    #
    # Mode A — Gemini AI Studio API key (simplest):
    #   GEMINI_API_KEY=AIza...  (from https://aistudio.google.com/apikey)
    #   Leave GEMINI_USE_VERTEX unset / false.
    #
    # Mode B — Google Cloud service account (Vertex AI):
    #   GEMINI_USE_VERTEX=true
    #   GEMINI_PROJECT=your-gcp-project-id
    #   GEMINI_LOCATION=us-central1  (or another region)
    #   GEMINI_SERVICE_ACCOUNT_FILE=/path/to/service-account.json
    #     OR set GOOGLE_APPLICATION_CREDENTIALS instead of the file path.
    #
    # Mode B is for enterprise / GCP billing. The service account must
    # have the `roles/aiplatform.user` IAM role.
    "GEMINI_API_KEY": os.environ.get("GEMINI_API_KEY", ""),
    "GEMINI_USE_VERTEX": os.environ.get("GEMINI_USE_VERTEX", "false").lower() == "true",
    "GEMINI_PROJECT": os.environ.get("GEMINI_PROJECT", ""),
    "GEMINI_LOCATION": os.environ.get("GEMINI_LOCATION", "us-central1"),
    "GEMINI_SERVICE_ACCOUNT_FILE": os.environ.get("GEMINI_SERVICE_ACCOUNT_FILE", ""),
    "GEMINI_MODEL": os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"),
    # How many retrieved chunks to stuff into the Gemini prompt as
    # grounding. Larger = better recall, more cost / latency.
    "AGENT_CONTEXT_CHUNKS": int(os.environ.get("AGENT_CONTEXT_CHUNKS", "12")),
    # Phase 3 agent loop — hard cap on tool calls per request. The
    # roadmap recommends 5–8; we default to the conservative end.
    # The controller stops + emits an error if the model hasn't
    # produced a final answer by then.
    "AGENT_MAX_STEPS": int(os.environ.get("AGENT_MAX_STEPS", "5")),
}
