"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-1=c=z%cqhlgi$@+w8x3ees)q*q!hosc2lvv^=_dpln(%wipz08",
)

# Default to True so local dev (where the env var isn't set) gets
# Django's normal development behavior: relaxed cookie attrs, open
# CORS, served `/media/`, full tracebacks. Production must
# *explicitly* opt out by setting `DJANGO_DEBUG=false` (the Railway
# config already does — see docs/RAILWAY_DEPLOY.md).
#
# This matches Django's own `django-admin startproject` default and
# is what every dependent setting below assumes when it derives from
# DEBUG (AUTH_COOKIE_SECURE, CORS_ALLOW_ALL_ORIGINS, etc.).
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Required for `BLACKLIST_AFTER_ROTATION` in SIMPLE_JWT to actually
    # do anything: this app provides the OutstandingToken /
    # BlacklistedToken tables that simplejwt writes to when a refresh
    # token is rotated or a user signs out. Without it, every
    # "blacklist" call is a silent no-op and old refresh tokens stay
    # valid until natural expiration.
    "rest_framework_simplejwt.token_blacklist",
    "origin",
    "origin.search_engine",
    "corsheaders",
    "anymail",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add this line at the top
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Stashes request.user in a thread-local so post_save / post_delete
    # signals on tasks/comments/attachments can attribute activity rows
    # to the acting user. Must run AFTER AuthenticationMiddleware so
    # `request.user` is already resolved.
    "origin.middleware.current_user.CurrentUserMiddleware",
]

# CORS policy.
#
# `CORS_ALLOW_ALL_ORIGINS=True` combined with `CORS_ALLOW_CREDENTIALS=True`
# would let any site on the internet trigger credentialed requests
# against this API and have the browser attach our refresh cookie. We
# only want that during local development; in production we restrict
# to the explicit list in `CORS_ALLOWED_ORIGINS` (env-driven) so only
# our actual frontend host can talk to the API with credentials.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

# Allow credentials (cookies, authentication)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "authorization",
# ]


ROOT_URLCONF = "apis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apis.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "origin",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "172.29.30.3",
            "PORT": "5432",
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Explicit logging config — defaults to INFO so hot-path debug calls
# (per-request `logger.debug(...)`) don't pay the f-string + I/O cost.
# Override via env: LOG_LEVEL=DEBUG for local debugging.
_LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "default",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": _LOG_LEVEL, "propagate": False},
        "django.request": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.db.backends": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "origin": {"handlers": ["console"], "level": _LOG_LEVEL, "propagate": False},
    },
    "root": {"handlers": ["console"], "level": _LOG_LEVEL},
}

# Cache backend — Redis when available; falls back transparently to
# "no cache" on Redis outages thanks to IGNORE_EXCEPTIONS. Keep timeouts
# tight (2s) so a slow Redis can't cascade into slow Django responses.
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 2,
            "SOCKET_TIMEOUT": 2,
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "origin",
    }
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SECRET_KEY", "your_secret_key"),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

AUTH_USER_MODEL = "origin.CustomUser"


CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to the session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # Adjust as needed: "Lax", "Strict", or "None"
CSRF_COOKIE_NAME = "csrftoken"  # Default cookie name
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = (
    False  # CSRF cookie should be accessible by JavaScript (for CSRF protection)
)
CSRF_COOKIE_SAMESITE = "Lax"

# Refresh-token cookie attributes.
#
# The frontend and backend are deployed to *different* hostnames in
# production (e.g. on Railway), so every API call is a cross-site
# request from the browser's point of view. For the browser to accept
# `Set-Cookie` on those responses *and* replay the cookie on the next
# `/user/signin/refresh/` fetch, the cookie must be sent with
# `SameSite=None; Secure`. In local dev we keep `SameSite=Lax` and
# `Secure=False` because Chrome won't set a `Secure` cookie over plain
# HTTP localhost.
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"


MEDIA_URL = "/media/"  # URL prefix
# Folder where uploaded files go. Made env-driven so the production
# container can point this at a Railway Volume mount path (e.g.
# `/app/backend_django/uploads` backed by a persistent disk) without
# touching code. The default keeps local dev working unchanged.
#
# This is the MVP setup: Django serves the files directly from this
# directory (see `apis/urls.py`). When the app outgrows a single
# replica or needs CDN-quality delivery, swap the storage backend to
# `django-storages` + Cloudflare R2 / AWS S3 and drop the volume.
MEDIA_ROOT = os.environ.get(
    "DJANGO_MEDIA_ROOT",
    os.path.join(BASE_DIR, "uploads"),
)


# Search engine (OpenSearch + OpenAI embeddings).
#
# Used by `origin.search_engine` for chunk-based hybrid search across
# chats, tasks, and notes. The OpenSearch index is created by
# `python manage.py opensearch_setup` and (re)populated by
# `python manage.py opensearch_reindex`.
SEARCH_ENGINE = {
    "OPENSEARCH_HOST": os.environ.get("OPENSEARCH_HOST", "opensearch"),
    "OPENSEARCH_PORT": int(os.environ.get("OPENSEARCH_PORT", "9200")),
    "OPENSEARCH_USE_SSL": os.environ.get("OPENSEARCH_USE_SSL", "false").lower() == "true",
    # Physical index name. Increment the suffix when changing the
    # mapping or embedding model and reindexing.
    "OPENSEARCH_INDEX": os.environ.get("OPENSEARCH_INDEX", "knowledge_chunks_v1"),
    # Stable alias the app queries. Repointed at a new physical index
    # during zero-downtime migrations.
    "OPENSEARCH_ALIAS": os.environ.get("OPENSEARCH_ALIAS", "knowledge_chunks_current"),
    # OpenAI embedding configuration. `text-embedding-3-small` is the
    # MVP default: 1536-dim, cheap, multilingual-decent. If you change
    # the model or dimension, bump the index suffix and reindex.
    "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", ""),
    "OPENAI_EMBEDDING_MODEL": os.environ.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small"),
    "OPENAI_EMBEDDING_DIMENSIONS": int(os.environ.get("OPENAI_EMBEDDING_DIMENSIONS", "1536")),
    # Embedding provider selection. "openai" (default) keeps existing
    # behavior. "vertex" routes embeddings through Vertex AI using the
    # same GCP auth as the Gemini LLM client below (GEMINI_USE_VERTEX,
    # GEMINI_PROJECT, GEMINI_LOCATION, GEMINI_SERVICE_ACCOUNT_FILE).
    # Switching providers automatically re-embeds all chunks on the
    # next opensearch_reindex (the RagChunk.embedding_model mismatch
    # check in ingestion.py picks it up). Switching to a model with a
    # different dimension also requires bumping OPENSEARCH_INDEX
    # (e.g. v1 -> v2) and re-running opensearch_setup.
    "EMBEDDING_PROVIDER": (os.environ.get("EMBEDDING_PROVIDER", "openai") or "openai").lower(),
    # Vertex embedding configuration (only used when
    # EMBEDDING_PROVIDER=vertex). Default uses gemini-embedding-001
    # truncated to 1536 dims via Matryoshka so it drops into the
    # existing 1536-dim OpenSearch index without recreating it. Bump
    # VERTEX_EMBEDDING_DIMENSIONS (and the index) if you want full 3072.
    "VERTEX_EMBEDDING_MODEL": os.environ.get("VERTEX_EMBEDDING_MODEL", "gemini-embedding-001"),
    "VERTEX_EMBEDDING_DIMENSIONS": int(os.environ.get("VERTEX_EMBEDDING_DIMENSIONS", "1536")),
    # Bulk-indexing batch size for OpenSearch _bulk requests.
    "BULK_BATCH_SIZE": int(os.environ.get("SEARCH_BULK_BATCH_SIZE", "200")),
    # Embedding batch size (max items per provider /embeddings request).
    "EMBEDDING_BATCH_SIZE": int(os.environ.get("SEARCH_EMBEDDING_BATCH_SIZE", "100")),
    # Gemini configuration for the RAG-answer endpoint
    # (POST /api/v2/agent/ask). `gemini-2.5-flash` is the MVP default
    # — fast, cheap, supports streaming + function calling for Phase 3.
    #
    # TWO authentication modes (pick exactly one):
    #
    # Mode A — Gemini AI Studio API key (simplest):
    #   GEMINI_API_KEY=AIza...  (from https://aistudio.google.com/apikey)
    #   Leave GEMINI_USE_VERTEX unset / false.
    #
    # Mode B — Google Cloud service account (Vertex AI):
    #   GEMINI_USE_VERTEX=true
    #   GEMINI_PROJECT=your-gcp-project-id
    #   GEMINI_LOCATION=us-central1  (or another region)
    #   GEMINI_SERVICE_ACCOUNT_FILE=/path/to/service-account.json
    #     OR set GOOGLE_APPLICATION_CREDENTIALS instead of the file path.
    #
    # Mode B is for enterprise / GCP billing. The service account must
    # have the `roles/aiplatform.user` IAM role.
    "GEMINI_API_KEY": os.environ.get("GEMINI_API_KEY", ""),
    "GEMINI_USE_VERTEX": os.environ.get("GEMINI_USE_VERTEX", "false").lower() == "true",
    "GEMINI_PROJECT": os.environ.get("GEMINI_PROJECT", ""),
    "GEMINI_LOCATION": os.environ.get("GEMINI_LOCATION", "us-central1"),
    "GEMINI_SERVICE_ACCOUNT_FILE": os.environ.get("GEMINI_SERVICE_ACCOUNT_FILE", ""),
    "GEMINI_MODEL": os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"),
    # How many retrieved chunks to stuff into the Gemini prompt as
    # grounding. Larger = better recall, more cost / latency.
    "AGENT_CONTEXT_CHUNKS": int(os.environ.get("AGENT_CONTEXT_CHUNKS", "12")),
    # Phase 3 agent loop — hard cap on tool calls per request. The
    # roadmap recommends 5–8; we default to the conservative end.
    # The controller stops + emits an error if the model hasn't
    # produced a final answer by then.
    "AGENT_MAX_STEPS": int(os.environ.get("AGENT_MAX_STEPS", "10")),
    # Phase 5 — provider selection. "gemini" (default) or "claude".
    # `get_model_client()` in origin.search_engine.llm reads this at
    # request time; an unknown value raises rather than silently
    # falling back.
    "LLM_PROVIDER": (os.environ.get("LLM_PROVIDER", "gemini") or "gemini").lower(),
    # Anthropic Claude config (only used when LLM_PROVIDER=claude).
    "CLAUDE_API_KEY": os.environ.get("CLAUDE_API_KEY", ""),
    "CLAUDE_MODEL": os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-6"),
    # Anthropic requires max_tokens to be set explicitly on every
    # call (unlike Gemini, which has a sensible server-side default).
    "CLAUDE_MAX_TOKENS": int(os.environ.get("CLAUDE_MAX_TOKENS", "4096")),
    # Phase 6 — RAG quality knobs.
    # Exponential decay half-life (in days) for freshness scoring.
    # Each hit's RRF score is multiplied by exp(-age_days / half_life).
    # Set to 0 to disable freshness boosting entirely.
    "RAG_FRESHNESS_HALF_LIFE_DAYS": float(os.environ.get("RAG_FRESHNESS_HALF_LIFE_DAYS", "90")),
    # Drop duplicate chunks (same text_hash) before entity grouping.
    "RAG_DEDUP_BY_HASH": (os.environ.get("RAG_DEDUP_BY_HASH", "true").lower() == "true"),
    # LLM-as-judge reranker. OFF by default during rollout; enable per
    # request via the env var. When on, after hybrid retrieval the top
    # INPUT_K entities are sent to the active ModelClient for reranking
    # and only the reranked OUTPUT_K are returned.
    "RAG_USE_RERANKER": (os.environ.get("RAG_USE_RERANKER", "false").lower() == "true"),
    "RAG_RERANK_INPUT_K": int(os.environ.get("RAG_RERANK_INPUT_K", "20")),
    "RAG_RERANK_OUTPUT_K": int(os.environ.get("RAG_RERANK_OUTPUT_K", "10")),
    # Reranker provider — "llm" (default, uses the configured LLM
    # provider as a judge) or "cohere" (purpose-built cross-encoder
    # via the Cohere v2 Rerank API, requires COHERE_API_KEY). Future
    # stubs in reranker.py: "jina" / "local" / "vertex_ranking".
    "RAG_RERANKER_PROVIDER": (os.environ.get("RAG_RERANKER_PROVIDER", "llm") or "llm").lower(),
    # Optional: per-call model override for the "llm" reranker — point
    # at a smaller/faster model (e.g. "gemini-2.5-flash") than the main
    # GEMINI_MODEL/CLAUDE_MODEL used for answer generation. Empty =
    # use the provider's default.
    "RAG_RERANKER_MODEL": os.environ.get("RAG_RERANKER_MODEL", ""),
    # "rerank but never drop" mode for the LLM reranker — keep items
    # the model omitted, append in pre-rerank order. Off by default.
    "RAG_RERANK_KEEP_DROPPED": (
        os.environ.get("RAG_RERANK_KEEP_DROPPED", "false").lower() == "true"
    ),
    # Cohere Rerank — used when RAG_RERANKER_PROVIDER=cohere.
    # Get an API key at https://dashboard.cohere.com/api-keys
    # Pricing as of late 2025 is ~$2 / 1k queries.
    "COHERE_API_KEY": os.environ.get("COHERE_API_KEY", ""),
    "COHERE_RERANK_MODEL": os.environ.get("COHERE_RERANK_MODEL", "rerank-v3.5"),
    "COHERE_RERANK_BASE_URL": os.environ.get(
        "COHERE_RERANK_BASE_URL", "https://api.cohere.com/v2/rerank"
    ),
    # Network timeout for the rerank call. Cohere's p95 is ~300 ms;
    # we cap at 10 s so a hung call falls back to pre-rerank order
    # instead of dominating turn latency.
    "COHERE_RERANK_TIMEOUT_S": float(os.environ.get("COHERE_RERANK_TIMEOUT_S", "10")),
    # Phase 8 — conversation session memory.
    # How many prior (query, answer) pairs to prepend into the model
    # context on follow-up /ask/ calls within the same session.
    "SESSION_MAX_PRIOR_TURNS": int(os.environ.get("SESSION_MAX_PRIOR_TURNS", "3")),
    # Minutes of inactivity before a session is considered expired.
    # An expired session ID silently creates a fresh session.
    "SESSION_TTL_MINUTES": int(os.environ.get("SESSION_TTL_MINUTES", "30")),
    # Phase 9 — chunking refinement.
    # How many preceding messages to fold into each chat_message
    # chunk's `search_text` for embedding context. Set to 0 to
    # disable (back to Phase-3 behavior). Requires an
    # `opensearch_reindex` after change to take effect on existing
    # chunks.
    "RAG_CHAT_CONTEXT_WINDOW": int(os.environ.get("RAG_CHAT_CONTEXT_WINDOW", "2")),
    # Phase 10 — LLM query rewriting (opt-in, agent path only).
    # When on, the agent's `search_knowledge_base` tool expands the
    # query into N variants via the active ModelClient before hitting
    # OpenSearch, then RRF-fuses results across all variants. Adds one
    # LLM call + N embedding calls per agent search. Off by default
    # during rollout. Does NOT affect the Spotlight typeahead
    # endpoint — it never passes `rewrite=True`.
    "RAG_USE_QUERY_REWRITE": (os.environ.get("RAG_USE_QUERY_REWRITE", "false").lower() == "true"),
    "RAG_REWRITE_NUM_VARIANTS": int(os.environ.get("RAG_REWRITE_NUM_VARIANTS", "3")),
    # Phase 3.2 — self-critique reflection step. When True, after the
    # agent produces its draft final answer, a second LLM call re-reads
    # the draft against the captured tool results and may produce a
    # revised final answer (precision-tightening only — no extra tool
    # rounds). Adds +1 LLM call per ask that reaches a final answer.
    # Off by default; opt-in via env or per-call settings override.
    "RAG_AGENT_SELF_CRITIQUE": (
        os.environ.get("RAG_AGENT_SELF_CRITIQUE", "false").lower() == "true"
    ),
    # Observability for Gemini implicit-cache hit rate. When True,
    # gemini_client._log_usage emits one INFO log per `generate_step`
    # call with `prompt_tokens`, `cached_tokens`, and a cache-hit %.
    # Flip on (`LLM_LOG_USAGE_METADATA=true`) to verify that the system
    # prompt + tool declarations are being served from cache after the
    # first request of a session — Gemini 2.5+/3.x caches stable
    # prefixes of ≥1024 (Flash) / ≥4096 (Pro) tokens automatically.
    # Off by default to keep production logs quiet.
    "LLM_LOG_USAGE_METADATA": (
        os.environ.get("LLM_LOG_USAGE_METADATA", "false").lower() == "true"
    ),
    # Phase 3.5 — rolling-summary multi-turn context. When True AND a
    # session has more than `SESSION_MAX_PRIOR_TURNS` prior turns, the
    # earliest turns are condensed into a single short summary that is
    # prepended to the messages alongside the last `SESSION_MAX_PRIOR_TURNS`
    # turns verbatim. Lets long conversations retain early-turn context
    # the verbatim window would otherwise drop. Costs one summary LLM
    # call per turn that triggers the summary path (i.e. only when the
    # session already has > N prior turns). Off by default.
    "RAG_SESSION_ROLLING_SUMMARY": (
        os.environ.get("RAG_SESSION_ROLLING_SUMMARY", "false").lower() == "true"
    ),
    # Phase 4.2 — re-sort source chips by citation density at end-of-turn.
    # When True, the final `sources` event (emitted just before `done`)
    # reorders chips so entities the answer actually cites surface
    # leftmost. Stable for ties (preserves tool-emission order).
    # Default True — clean UX win, low risk. Flip to False if the chip
    # reshuffle at done-time turns out to be jarring.
    "RAG_RANK_SOURCES_BY_CITATION": (
        os.environ.get("RAG_RANK_SOURCES_BY_CITATION", "true").lower() == "true"
    ),
    # Phase 5.1 — L2 Redis cache for query-side embeddings. Sits BEHIND
    # the existing per-worker LRU (L1) in `embeddings/__init__.py`, so
    # the typeahead hot path keeps its zero-network L1 hits AND a
    # cross-worker / post-restart hit also skips the embedding API.
    # Key = (model_name, sha256(text)); value = the float vector.
    # TTL in seconds — set to 0 to disable L2 entirely (L1 LRU stays).
    "RAG_EMBEDDING_CACHE_TTL_S": int(os.environ.get("RAG_EMBEDDING_CACHE_TTL_S", "600")),
    # Phase 14 — live web search via Tavily.
    # Sign up at https://tavily.com to get a free API key (1 000 req/month).
    # Set TAVILY_API_KEY in .env (local) and Railway env vars (production).
    # Leave empty to disable web search — the agent will surface a clean
    # error rather than crashing when the key is absent.
    "TAVILY_API_KEY": os.environ.get("TAVILY_API_KEY", ""),
    # User-selectable LLM provider/model catalog. Each entry is shown
    # in the Settings → Spotlight → AI Model picker. `note` is a short
    # one-liner shown beneath the model dropdown ("Slower — uses
    # extended thinking" etc.). When a user removes their selection
    # (or an admin removes a model from this list), `resolve_user_choice`
    # in llm/choice.py falls back to the server default and logs a
    # warning — no silent SDK error.
    "MODEL_CATALOG": [
        # {
        #     "provider": "gemini",
        #     "model": "gemini-2.5-flash",
        #     "label": "Gemini 2.5 Flash",
        #     "note": "Fast responses, good for simple questions.",
        # },
        # {
        #     "provider": "gemini",
        #     "model": "gemini-2.5-pro",
        #     "label": "Gemini 2.5 Pro",
        #     "note": "Slower — uses extended thinking for hard questions.",
        # },
        {
            "provider": "gemini",
            "model": "gemini-3.5-flash",
            "label": "Gemini 3.5 Flash",
            "note": "Fast responses, good for most questions.",
        },
        {
            "provider": "gemini",
            "model": "gemini-3.1-pro-preview",
            "label": "Gemini 3.1 Pro Preview",
            "note": "Slower — uses extended thinking for hard questions.",
        },
        {
            "provider": "claude",
            "model": "claude-haiku-4-5",
            "label": "Claude Haiku 4.5",
            "note": "Fast and economical.",
        },
        {
            "provider": "claude",
            "model": "claude-sonnet-4-6",
            "label": "Claude Sonnet 4.6",
            "note": "Higher quality, slower.",
        },
        {
            "provider": "claude",
            "model": "claude-opus-4-7",
            "label": "Claude Opus 4.7",
            "note": "Very slow, but best for very complex questions.",
        },
    ],
    # Daily quotas by user tier. Three tiers — free / pro / max —
    # resolved from `CustomUser.tier` by `origin.search_engine.quota`.
    # Each tier sets three independent daily quotas (all reset at
    # UTC midnight):
    #   - `llm_ask_daily`: total agent asks per day (counted on first
    #     answer_delta).
    #   - `web_search_daily`: Tavily searches per day (counted on
    #     successful tool execution).
    #   - `model_daily[<model>]`: per-model asks per day. A model
    #     missing from a tier's dict is treated as unlimited for that
    #     tier.
    # A limit value of `None` means unlimited. Numbers below are
    # placeholders — tune as needed.
    "TIER_QUOTAS": {
        "free": {
            "llm_ask_daily": 20,
            "web_search_daily": 10,
            "model_daily": {
                # "gemini-2.5-flash": 10,
                # "gemini-2.5-pro": 5,
                "gemini-3.5-flash": 20,
                "gemini-3.1-pro-preview": 10,
                "claude-haiku-4-5": 20,
                "claude-sonnet-4-6": 10,
                "claude-opus-4-7": 0,
            },
        },
        "pro": {
            "llm_ask_daily": 100,
            "web_search_daily": 50,
            "model_daily": {
                # "gemini-2.5-flash": 100,
                # "gemini-2.5-pro": 30,
                "gemini-3.5-flash": 100,
                "gemini-3.1-pro-preview": 50,
                "claude-haiku-4-5": 100,
                "claude-sonnet-4-6": 50,
                "claude-opus-4-7": 20,
            },
        },
        "max": {
            "llm_ask_daily": 1000,
            "web_search_daily": 500,
            "model_daily": {
                # "gemini-2.5-flash": 1000,
                # "gemini-2.5-pro": 500,
                "gemini-3.5-flash": 1000,
                "gemini-3.1-pro-preview": 500,
                "claude-haiku-4-5": 1000,
                "claude-sonnet-4-6": 500,
                "claude-opus-4-7": 200,
            },
        },
    },
}

# --- Email ---
# Dev default: print emails to the runserver console so engineers don't
# need credentials locally. In production, send via Resend's HTTPS API
# (django-anymail) — Railway blocks/filters outbound SMTP, so SMTP to
# Gmail times out from the deployed container. To enable:
#   EMAIL_BACKEND=anymail.backends.resend.EmailBackend
#   RESEND_API_KEY=re_xxx                 (from resend.com/api-keys)
#   DEFAULT_FROM_EMAIL=Genos <noreply@your-verified-domain>
# Sender domain must be verified at resend.com/domains, or use
# `onboarding@resend.dev` for self-testing (only delivers to the
# Resend account owner's verified address).
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Genos <noreply@example.com>")

ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY", ""),
}

# Public origin used to build absolute URLs in outgoing emails (e.g.
# password-reset links). Default matches the dockerised dev frontend
# (see docker/docker-compose.yml, react service on :3000). Override in
# deployed environments to the actual frontend host.
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000")

# How long a password-reset URL is valid for, in minutes. Short enough
# that a leaked link is unlikely to still work, long enough that users
# can finish reading the email and clicking.
PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = int(
    os.environ.get("PASSWORD_RESET_TOKEN_EXPIRY_MINUTES", "60")
)

# How long an email-verification URL is valid for, in minutes. Longer
# than password-reset because the user just opened their inbox at signup
# and the cost of expiry is mild (they request a resend).
EMAIL_VERIFICATION_TOKEN_EXPIRY_MINUTES = int(
    os.environ.get("EMAIL_VERIFICATION_TOKEN_EXPIRY_MINUTES", "1440")
)

# --- OAuth (Google, GitHub) ---
# Fernet key used to encrypt third-party access / refresh tokens at
# rest in the ConnectedAccount table. Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Required in production. In dev it can be left empty as long as you
# don't exercise OAuth flows — the crypto helper raises a clear error
# only when actually used (see origin/services/crypto.py).
OAUTH_TOKEN_ENCRYPTION_KEY = os.environ.get("OAUTH_TOKEN_ENCRYPTION_KEY", "")

# Per-provider OAuth client credentials. Empty defaults so the rest of
# Django still imports cleanly when these aren't configured yet; the
# OAuth views check for them and 503 with a helpful message.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GITHUB_OAUTH_CLIENT_ID = os.environ.get("GITHUB_OAUTH_CLIENT_ID", "")
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get("GITHUB_OAUTH_CLIENT_SECRET", "")

# Shared secret for GitHub repo webhook payload verification. Generate
# any random string (e.g. `openssl rand -hex 32`), set the SAME value
# both here AND in the GitHub repo's Webhook settings (under "Secret")
# so the signed payload's `X-Hub-Signature-256` header validates.
# When empty, the webhook endpoint rejects all incoming requests.
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET", "")

# Public-facing URL of THIS backend, used to build OAuth callback URLs
# that match what's registered in the Google / GitHub OAuth app config.
# Defaults to the dockerised dev Django port (see docker/docker-compose.yml;
# 8889 is Flask's websocket, 8890 is Django REST — confirmed by
# `python manage.py runserver 127.0.0.1:8890` in docs/setup.sh).
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL", "http://localhost:8890")
