"""
Django settings for apis project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import json
import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url

from apis.credit_policy import load_credit_policy
from apis.llm_catalog import load_llm_catalog

BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-1=c=z%cqhlgi$@+w8x3ees)q*q!hosc2lvv^=_dpln(%wipz08",
)

# Default to True so local dev (where the env var isn't set) gets
# Django's normal development behavior: relaxed cookie attrs, open
# CORS, served `/media/`, full tracebacks. Production must
# *explicitly* opt out by setting `DJANGO_DEBUG=false` (the Railway
# config already does — see docs/RAILWAY_DEPLOY.md).
#
# This matches Django's own `django-admin startproject` default and
# is what every dependent setting below assumes when it derives from
# DEBUG (AUTH_COOKIE_SECURE, CORS_ALLOW_ALL_ORIGINS, etc.).
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "localhost").split(",") if h.strip()
]
# Railway's deploy healthcheck probes `healthcheckPath` with
# Host: healthcheck.railway.app. Prod's env var lists only the public API
# domain, so without this DisallowedHost 400s every probe and a deploy
# gated on the healthcheck would NEVER go live. Appended in code (not the
# env var) so the healthcheck can't be broken by env drift; harmless
# everywhere else.
if "healthcheck.railway.app" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("healthcheck.railway.app")


# -- Unified messaging dual-write (Track B Phase 1) --------------------------
#
# When True, every legacy `(dm|gm|pm|mdm)/message/` write path also inserts
# a matching row into the unified `Message` / `Channel` schema via
# `origin.services.unified_writer`. Default off: requires the Phase 2 backfill
# to have run first (so `Channel.legacy_chat_id` is populated for every
# existing legacy row), otherwise dual-write would silently lazy-create
# channels for pre-backfill rows and the drift cron would surface spurious
# divergence between old and new tables.
#
# Flip on via env: `UNIFIED_MESSAGING_DUAL_WRITE=true`. See Track B in
# /Users/kamikenpro/.claude/plans/chat-rewrite-remaining-phases.md.
UNIFIED_MESSAGING_DUAL_WRITE = (
    os.environ.get("UNIFIED_MESSAGING_DUAL_WRITE", "false").lower() == "true"
)


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Required for `BLACKLIST_AFTER_ROTATION` in SIMPLE_JWT to actually
    # do anything: this app provides the OutstandingToken /
    # BlacklistedToken tables that simplejwt writes to when a refresh
    # token is rotated or a user signs out. Without it, every
    # "blacklist" call is a silent no-op and old refresh tokens stay
    # valid until natural expiration.
    "rest_framework_simplejwt.token_blacklist",
    "origin",
    "origin.search_engine",
    "corsheaders",
    "anymail",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Add this line at the top
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Stashes request.user in a thread-local so post_save / post_delete
    # signals on tasks/comments/attachments can attribute activity rows
    # to the acting user. Must run AFTER AuthenticationMiddleware so
    # `request.user` is already resolved.
    "origin.middleware.current_user.CurrentUserMiddleware",
]

# CORS policy.
#
# `CORS_ALLOW_ALL_ORIGINS=True` combined with `CORS_ALLOW_CREDENTIALS=True`
# would let any site on the internet trigger credentialed requests
# against this API and have the browser attach our refresh cookie. We
# only want that during local development; in production we restrict
# to the explicit list in `CORS_ALLOWED_ORIGINS` (env-driven) so only
# our actual frontend host can talk to the API with credentials.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

# Allow credentials (cookies, authentication)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

# CORS_ALLOW_HEADERS = [
#     "content-type",
#     "authorization",
# ]


ROOT_URLCONF = "apis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apis.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=False,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "origin",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "172.29.30.3",
            "PORT": "5432",
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Explicit logging config — defaults to INFO so hot-path debug calls
# (per-request `logger.debug(...)`) don't pay the f-string + I/O cost.
# Override via env: LOG_LEVEL=DEBUG for local debugging.
_LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "default",
        },
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": _LOG_LEVEL, "propagate": False},
        "django.request": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "django.db.backends": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "origin": {"handlers": ["console"], "level": _LOG_LEVEL, "propagate": False},
    },
    "root": {"handlers": ["console"], "level": _LOG_LEVEL},
}

# Cache backend — Redis when available; falls back transparently to
# "no cache" on Redis outages thanks to IGNORE_EXCEPTIONS. Keep timeouts
# tight (2s) so a slow Redis can't cascade into slow Django responses.
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 2,
            "SOCKET_TIMEOUT": 2,
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": "origin",
    }
}
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

# Under `manage.py test`, swap the shared Redis cache for an isolated
# in-process one. Redis persists across runs (and is shared with the
# running dev server), so tests would otherwise (a) leak DRF throttle
# history between runs — a suite re-run within the hour trips the
# per-hour auth throttles with spurious 429s — and (b) poison the live
# dev app's caches (e.g. the 60s project-list cache) with test-fixture
# data.
if len(sys.argv) > 1 and sys.argv[1] == "test":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "django-tests",
        }
    }

# Web Push (VAPID). Generate a keypair with
# `python manage.py generate_vapid_keys` (or `npx web-push
# generate-vapid-keys`). The PRIVATE key is a secret — set it via env,
# never commit it. The PUBLIC key is also handed to the frontend as
# `VITE_VAPID_PUBLIC_KEY` (identical value). When unset, push delivery is
# simply skipped (the in-app notification path is unaffected).
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_ADMIN_EMAIL = os.environ.get("WEBPUSH_VAPID_ADMIN_EMAIL", "admin@example.com")
# Optional absolute base URL for push-notification icons (the sender's
# avatar). Same value as the frontend's VITE_MEDIA_ROOT_DJANGO, e.g.
# "http://localhost:8890/media". When unset, push cards use the app icon.
WEBPUSH_MEDIA_BASE_URL = os.environ.get("WEBPUSH_MEDIA_BASE_URL", "")

# GIF search (the chat composers' GIF picker) via the GIPHY API.
# Create an app at https://developers.giphy.com to get a key.
# Set GIPHY_API_KEY in .env (local) and Railway env vars (production);
# GCP mirrors it as a tfvars feature secret. Leave empty to disable —
# the proxy endpoint answers a clean 503 rather than crashing, and the
# frontend hides the picker's results accordingly.
GIPHY_API_KEY = os.environ.get("GIPHY_API_KEY", "")

REST_FRAMEWORK = {
    # Order matters, but not for correctness: the API-key class returns
    # None unless the header actually says `ApiKey`, so the two never
    # compete for the same credential. JWT stays first because it is the
    # overwhelmingly common case and short-circuits sooner.
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "origin.views.common.api_key_auth.ApiKeyAuthentication",
    ),
    # Per-IP throttling behind a proxy: both prod edges (Railway, Cloud
    # Run's front end) sit exactly one hop in front of gunicorn and
    # append the real client address to X-Forwarded-For. NUM_PROXIES=1
    # makes DRF's AnonRateThrottle key on that address instead of the
    # proxy's — without it every visitor shares one bucket and a single
    # attacker can 429 the whole login page. Client-supplied XFF entries
    # sit EARLIER in the list, so this stays spoof-proof. Local dev has
    # no proxy: keep None so REMOTE_ADDR is used directly.
    **({"NUM_PROXIES": 1} if not DEBUG else {}),
}

SIMPLE_JWT = {
    # NOT shortened, deliberately. A shorter access token would be the
    # normal hardening move, but the frontend has no proactive refresh:
    # `AuthContext` only refreshes when `accessToken` is null, and
    # nothing nulls it on expiry (no `exp` watcher, and the axios
    # interceptor deliberately skips 401 because it assumes AuthContext
    # owns that path). So an expired access token silently breaks the
    # session until the user reloads the page. At 24h almost everyone
    # reloads first; at 30 minutes it would happen to everyone, twice an
    # hour. Shortening this is blocked on adding proactive refresh
    # frontend-side — see operations/AUTH_SECURITY_PLAN.md §3.1.
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Bind every token to the password it was minted under. simplejwt
    # stamps an md5 of `user.password` into the token as a
    # `hash_password` claim (see REVOKE_TOKEN_CLAIM) and rejects any
    # token whose claim no longer matches on every authenticated
    # request.
    #
    # This is what makes a password reset actually evict an attacker.
    # Without it, resetting your password terminates NOTHING: the only
    # `.blacklist()` call in this codebase is in LogoutView, acting on
    # the one refresh token in the cookie it was handed. Because
    # ROTATE_REFRESH_TOKENS mints a fresh 7-day token on every refresh,
    # a stolen session survived a password reset indefinitely — which
    # is the exact scenario a password reset exists to end.
    #
    # Safe for OAuth users: `set_unusable_password()` is called only in
    # the signup branch of the OAuth callback, never on later logins,
    # so their password field is stable and so is the claim.
    "CHECK_REVOKE_TOKEN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SECRET_KEY", "your_secret_key"),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


def _validate_prod_secrets(*, debug: bool, secret_key: str, jwt_signing_key: str) -> None:
    """Refuse to boot a production process on the known dev-fallback
    signing keys.

    Both fallbacks above exist so local dev works with no env file, but
    they are PUBLIC values (this file is on GitHub). If env drift ever
    dropped DJANGO_SECRET_KEY or JWT_SECRET_KEY in prod, the app would
    silently sign sessions / password-reset state / every JWT with a
    key an attacker can read — i.e. anyone could mint a valid token for
    any user. Failing the deploy loudly (the healthcheck gate catches
    it before traffic shifts) is strictly better than that.

    Extracted as a function so tests can exercise it without re-importing
    the settings module.
    """
    if debug:
        return
    from django.core.exceptions import ImproperlyConfigured

    if not secret_key or secret_key.startswith("django-insecure-"):
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is unset (or the public dev fallback) with "
            "DJANGO_DEBUG=false. Set a real secret before deploying."
        )
    if not jwt_signing_key or jwt_signing_key == "your_secret_key":
        raise ImproperlyConfigured(
            "JWT_SECRET_KEY is unset (or the public dev fallback) with "
            "DJANGO_DEBUG=false. Set a real secret before deploying."
        )


_validate_prod_secrets(
    debug=DEBUG, secret_key=SECRET_KEY, jwt_signing_key=SIMPLE_JWT["SIGNING_KEY"]
)

AUTH_USER_MODEL = "origin.CustomUser"


CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://localhost:8890",
    ).split(",")
    if o.strip()
]

# -- Security headers / proxy TLS ------------------------------------------
#
# Both prod deployments terminate TLS at the edge (Railway, Cloud Run)
# and forward plain HTTP with `X-Forwarded-Proto: https`. Trusting that
# header makes `request.is_secure()` true behind the proxy, which HSTS
# emission (and anything else keyed on is_secure) depends on. Safe
# because clients cannot reach gunicorn directly in either environment
# — the edge always overwrites the header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Deliberately NOT setting SECURE_SSL_REDIRECT: the edges only publish
# HTTPS endpoints, and Railway's deploy healthcheck probes over plain
# internal HTTP — a 301 there would hang every deploy (same trap as the
# ALLOWED_HOSTS healthcheck host, see above).

# Browsers pin HTTPS for a year after the first visit — defeats
# SSL-stripping on later visits. Scoped to this exact host (no
# subdomain/preload ambitions for an API domain). DEBUG-gated so plain
# http://localhost dev never caches a pin.
if not DEBUG:
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Django defaults, pinned explicitly so a version bump can't silently
# relax them: refuse MIME sniffing, refuse framing (clickjacking), and
# keep referrers on-origin.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True  # Prevents JavaScript access to the session cookie
SESSION_COOKIE_SAMESITE = "Lax"  # Adjust as needed: "Lax", "Strict", or "None"
CSRF_COOKIE_NAME = "csrftoken"  # Default cookie name
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # CSRF cookie should be accessible by JavaScript (for CSRF protection)
CSRF_COOKIE_SAMESITE = "Lax"

# Refresh-token cookie attributes.
#
# The frontend and backend are deployed to *different* hostnames in
# production (e.g. on Railway), so every API call is a cross-site
# request from the browser's point of view. For the browser to accept
# `Set-Cookie` on those responses *and* replay the cookie on the next
# `/user/signin/refresh/` fetch, the cookie must be sent with
# `SameSite=None; Secure`. In local dev we keep `SameSite=Lax` and
# `Secure=False` because Chrome won't set a `Secure` cookie over plain
# HTTP localhost.
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"


MEDIA_URL = "/media/"  # URL prefix
# Folder where uploaded files go. Made env-driven so the production
# container can point this at a Railway Volume mount path (e.g.
# `/app/backend_django/uploads` backed by a persistent disk) without
# touching code. The default keeps local dev working unchanged.
#
# This is the MVP setup: Django serves the files directly from this
# directory (see `apis/urls.py`). When the app outgrows a single
# replica or needs CDN-quality delivery, swap the storage backend to
# `django-storages` + Cloudflare R2 / AWS S3 and drop the volume.
MEDIA_ROOT = os.environ.get(
    "DJANGO_MEDIA_ROOT",
    os.path.join(BASE_DIR, "uploads"),
)


# Search engine (OpenSearch + OpenAI embeddings).
#
# Used by `origin.search_engine` for chunk-based hybrid search across
# chats, tasks, and notes. The OpenSearch index is created by
# `python manage.py opensearch_setup` and (re)populated by
# `python manage.py opensearch_reindex`.
SEARCH_ENGINE = {
    "OPENSEARCH_HOST": os.environ.get("OPENSEARCH_HOST", "opensearch"),
    "OPENSEARCH_PORT": int(os.environ.get("OPENSEARCH_PORT", "9200")),
    "OPENSEARCH_USE_SSL": os.environ.get("OPENSEARCH_USE_SSL", "false").lower() == "true",
    # Physical index name. Increment the suffix when changing the
    # mapping or embedding model and reindexing.
    "OPENSEARCH_INDEX": os.environ.get("OPENSEARCH_INDEX", "knowledge_chunks_v1"),
    # Stable alias the app queries. Repointed at a new physical index
    # during zero-downtime migrations.
    "OPENSEARCH_ALIAS": os.environ.get("OPENSEARCH_ALIAS", "knowledge_chunks_current"),
    # OpenAI embedding configuration. `text-embedding-3-small` is the
    # MVP default: 1536-dim, cheap, multilingual-decent. If you change
    # the model or dimension, bump the index suffix and reindex.
    "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", ""),
    "OPENAI_EMBEDDING_MODEL": os.environ.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small"),
    "OPENAI_EMBEDDING_DIMENSIONS": int(os.environ.get("OPENAI_EMBEDDING_DIMENSIONS", "1536")),
    # Embedding provider selection. "openai" (default) keeps existing
    # behavior. "vertex" routes embeddings through Vertex AI using the
    # same GCP auth as the Gemini LLM client below (GEMINI_USE_VERTEX,
    # GEMINI_PROJECT, GEMINI_LOCATION, GEMINI_SERVICE_ACCOUNT_FILE).
    # Switching providers automatically re-embeds all chunks on the
    # next opensearch_reindex (the RagChunk.embedding_model mismatch
    # check in ingestion.py picks it up). Switching to a model with a
    # different dimension also requires bumping OPENSEARCH_INDEX
    # (e.g. v1 -> v2) and re-running opensearch_setup.
    "EMBEDDING_PROVIDER": (os.environ.get("EMBEDDING_PROVIDER", "openai") or "openai").lower(),
    # Vertex embedding configuration (only used when
    # EMBEDDING_PROVIDER=vertex). Default uses gemini-embedding-001
    # truncated to 1536 dims via Matryoshka so it drops into the
    # existing 1536-dim OpenSearch index without recreating it. Bump
    # VERTEX_EMBEDDING_DIMENSIONS (and the index) if you want full 3072.
    "VERTEX_EMBEDDING_MODEL": os.environ.get("VERTEX_EMBEDDING_MODEL") or "gemini-embedding-001",
    # NB `... or "1536"`, not a get() default. `os.environ.get(k, d)` returns
    # the default only when the key is ABSENT — a key that is present but
    # EMPTY yields "" and int("") raises at import, taking the whole process
    # down before Django starts. docker-compose passes every optional var as
    # `${VAR:-}`, which always sets the key, so an unset var in .env arrives
    # as "". Any int()/float() of an env var here needs the `or` form.
    "VERTEX_EMBEDDING_DIMENSIONS": int(os.environ.get("VERTEX_EMBEDDING_DIMENSIONS") or "1536"),
    # Bulk-indexing batch size for OpenSearch _bulk requests.
    "BULK_BATCH_SIZE": int(os.environ.get("SEARCH_BULK_BATCH_SIZE", "200")),
    # Embedding batch size (max items per provider /embeddings request).
    "EMBEDDING_BATCH_SIZE": int(os.environ.get("SEARCH_EMBEDDING_BATCH_SIZE", "100")),
    # Refresh-policy for bulk writes. When False (the default during
    # ingestion runs), each `_bulk()` ships without `?refresh`, and
    # `ingest_all` issues one explicit `indices.refresh()` at the end
    # of the full run. Cuts ~1s-per-batch refresh overhead during big
    # reindexes. Switch to True for one-off writes that need to be
    # searchable immediately (e.g. manual `manage.py shell` upserts).
    "RAG_BULK_REFRESH": (os.environ.get("RAG_BULK_REFRESH", "false").lower() == "true"),
    # Gemini configuration for the RAG-answer endpoint
    # (POST /api/v2/agent/ask). `gemini-2.5-flash` is the MVP default
    # — fast, cheap, supports streaming + function calling for Phase 3.
    #
    # TWO authentication modes (pick exactly one):
    #
    # Mode A — Gemini AI Studio API key (simplest):
    #   GEMINI_API_KEY=AIza...  (from https://aistudio.google.com/apikey)
    #   Leave GEMINI_USE_VERTEX unset / false.
    #
    # Mode B — Google Cloud service account (Vertex AI):
    #   GEMINI_USE_VERTEX=true
    #   GEMINI_PROJECT=your-gcp-project-id
    #   GEMINI_LOCATION=us-central1  (or another region)
    #   GEMINI_SERVICE_ACCOUNT_FILE=/path/to/service-account.json
    #     OR set GOOGLE_APPLICATION_CREDENTIALS instead of the file path.
    #
    # Mode B is for enterprise / GCP billing. The service account must
    # have the `roles/aiplatform.user` IAM role.
    "GEMINI_API_KEY": os.environ.get("GEMINI_API_KEY", ""),
    "GEMINI_USE_VERTEX": os.environ.get("GEMINI_USE_VERTEX", "false").lower() == "true",
    "GEMINI_PROJECT": os.environ.get("GEMINI_PROJECT", ""),
    "GEMINI_LOCATION": os.environ.get("GEMINI_LOCATION") or "us-central1",
    # Optional per-role Vertex region override for the LLM (agent /
    # reranker / rewriter) client ONLY. Falls back to GEMINI_LOCATION
    # when unset, so existing single-region deploys are unchanged. This
    # exists because GEMINI_LOCATION is shared with the Vertex EMBEDDER
    # (embeddings/vertex_embedder.py) and the reindex job — some Gemini
    # models (e.g. *-preview) are served on the `global` endpoint or in
    # us-central1 but NOT in every regional endpoint (e.g. Tokyo /
    # asia-northeast1), while gemini-embedding-001 is regional. Point
    # this at `global` (or us-central1) to reach a preview LLM model
    # while embeddings stay on the region their index was built in —
    # avoiding a region change that would silently break retrieval
    # (see genos-platform infra/gcp/README.md "Vertex model + region").
    "GEMINI_LLM_LOCATION": os.environ.get("GEMINI_LLM_LOCATION", ""),
    "GEMINI_SERVICE_ACCOUNT_FILE": os.environ.get("GEMINI_SERVICE_ACCOUNT_FILE", ""),
    # Transient-error retry for the Gemini LLM client (google-genai's
    # built-in tenacity retry). Total attempts INCLUDING the first call;
    # 0 or 1 disables retrying. The SDK retries request initiation only
    # (never mid-stream, so no duplicated chunks) on 408/429/500/502/
    # 503/504 + connect/timeout errors, with exponential backoff +
    # jitter (~1s/2s/4s waits at the default 4 attempts). Added after a
    # Vertex 429 RESOURCE_EXHAUSTED blip hard-failed an agent step and
    # fired the nightly tool_recall drift alarm (issue #46).
    "GEMINI_RETRY_ATTEMPTS": int(os.environ.get("GEMINI_RETRY_ATTEMPTS", "4")),
    # Default agent model for users with no saved preference. MUST be a
    # model present in MODEL_CATALOG below — `_server_default_choice()` in
    # llm/choice.py intentionally does NOT catalog-validate the server
    # default (it's an operator escape hatch), so a stale default here ships
    # silently: the loop runs it while the Settings picker only offers the
    # catalog. `test_default_models_are_in_catalog` guards against that drift.
    "GEMINI_MODEL": os.environ.get("GEMINI_MODEL") or "gemini-3.6-flash",
    # (AGENT_CONTEXT_CHUNKS used to live here — removed as dead code.
    # Nothing ever read it; the real context budget is search()'s
    # max_chunks_per_entity × the per-tool entity limit.)
    # Phase 3 agent loop — hard cap on tool calls per request. The
    # roadmap recommends 5–8; we default to the conservative end.
    # When the cap is hit without a final answer, the controller forces
    # one last tool-less "answer with what you have" synthesis call
    # (AGENT_STEP_CAP_WRAPUP below) instead of erroring.
    "AGENT_MAX_STEPS": int(os.environ.get("AGENT_MAX_STEPS", "10")),
    # Kill switch for that step-cap wrap-up call. Default ON: a run
    # that spent its whole budget on tools is holding real retrieved
    # material, and "did not reach a final answer" throws it away.
    # Setting this to false restores the historical hard error exactly.
    "AGENT_STEP_CAP_WRAPUP": os.environ.get("AGENT_STEP_CAP_WRAPUP", "true").lower() == "true",
    # Ops kill-switch for individual agent tools: comma-separated tool
    # names to hide from the model (e.g. "search_web,create_task"), so a
    # risky new tool can ship dark / be switched off per environment with
    # no code change (SPOTLIGHT_AGENT_CHANGE_SAFETY.md §4.4, genos-docs).
    # FAIL-OPEN by design: unset/empty disables NOTHING. Env vars are
    # configured per service (Railway) and per environment, so a service
    # that misses the var must run at full capability rather than
    # silently losing tools. Unknown names are logged and ignored by the
    # controller (typo guard).
    "AGENT_DISABLED_TOOLS": frozenset(
        t.strip() for t in os.environ.get("AGENT_DISABLED_TOOLS", "").split(",") if t.strip()
    ),
    # Phase 5 — provider selection. "gemini" (default), "claude", or
    # "openai". `get_model_client()` in origin.search_engine.llm reads
    # this at request time; an unknown value raises rather than silently
    # falling back.
    "LLM_PROVIDER": (os.environ.get("LLM_PROVIDER", "gemini") or "gemini").lower(),
    # Anthropic Claude config (only used when LLM_PROVIDER=claude).
    "CLAUDE_API_KEY": os.environ.get("CLAUDE_API_KEY", ""),
    # `or`, not a get() default — compose passes unset vars as "", which
    # shadows a get() default (see VERTEX_EMBEDDING_DIMENSIONS above).
    "CLAUDE_MODEL": os.environ.get("CLAUDE_MODEL") or "claude-sonnet-5",
    # Anthropic requires max_tokens to be set explicitly on every
    # call (unlike Gemini, which has a sensible server-side default).
    "CLAUDE_MAX_TOKENS": int(os.environ.get("CLAUDE_MAX_TOKENS", "4096")),
    # OpenAI chat config (only used when the resolved provider is
    # "openai"). Reuses the SAME `OPENAI_API_KEY` as the embedder above —
    # one OpenAI account, one key, one bill. Unlike gemini/claude this
    # does NOT route through Vertex (there is no GPT path on Model
    # Garden), so it is a third billable LLM line outside GCP; see
    # genos-docs operations/LLM_SPEND_MAP.md §1.
    # `or`, not a get() default — see the VERTEX_EMBEDDING_DIMENSIONS note
    # above: compose passes unset vars as "", which shadows a get() default.
    "OPENAI_MODEL": os.environ.get("OPENAI_MODEL") or "gpt-5.6-terra",
    # Mirrors CLAUDE_MAX_TOKENS: bound the per-call output ceiling so a
    # runaway generation can't blow past the per-ask cost class the tier
    # limits were sized against (output is the dominant cost term).
    "OPENAI_MAX_TOKENS": int(os.environ.get("OPENAI_MAX_TOKENS") or "4096"),
    # Phase 6 — RAG quality knobs.
    # Exponential decay half-life (in days) for freshness scoring.
    # Each hit's RRF score is multiplied by exp(-age_days / half_life).
    # Set to 0 to disable freshness boosting entirely.
    "RAG_FRESHNESS_HALF_LIFE_DAYS": float(os.environ.get("RAG_FRESHNESS_HALF_LIFE_DAYS", "90")),
    # Drop duplicate chunks (same text_hash) before entity grouping.
    "RAG_DEDUP_BY_HASH": (os.environ.get("RAG_DEDUP_BY_HASH", "true").lower() == "true"),
    # Mentions v2 — soft boost for chunks matching the ask's resolved
    # @/# mentions (member fields / entity ids). Inactive on every
    # call without mentions, so it only shapes mention-carrying asks.
    "RAG_MENTION_BOOST": (os.environ.get("RAG_MENTION_BOOST", "true").lower() == "true"),
    "RAG_MENTION_BOOST_WEIGHT": float(os.environ.get("RAG_MENTION_BOOST_WEIGHT", "1.5")),
    # LLM-as-judge reranker. ON by default (Q2.1) for the agent / ai_search
    # path: score-fusion measured +0.118 recall / +5 behavior cases / ZERO
    # regressions on gemini-3.1-pro-preview (SPOTLIGHT_Q0_Q2_PROGRESS.md).
    # NEVER runs in typeahead mode (search.py guards it — typeahead's
    # sub-100 ms budget can't afford an LLM rerank call). Cost: ~+50%
    # retrieval latency on the agent path. Set RAG_USE_RERANKER=false to
    # disable; point RAG_RERANKER_MODEL at a faster model to cut the tax
    # (the strong result used the main pro model as the reranker).
    "RAG_USE_RERANKER": (os.environ.get("RAG_USE_RERANKER", "true").lower() == "true"),
    "RAG_RERANK_INPUT_K": int(os.environ.get("RAG_RERANK_INPUT_K", "20")),
    "RAG_RERANK_OUTPUT_K": int(os.environ.get("RAG_RERANK_OUTPUT_K", "10")),
    # Reranker provider — "llm" (default, uses the configured LLM
    # provider as a judge) or "cohere" (purpose-built cross-encoder
    # via the Cohere v2 Rerank API, requires COHERE_API_KEY). Future
    # stubs in reranker.py: "jina" / "local" / "vertex_ranking".
    "RAG_RERANKER_PROVIDER": (os.environ.get("RAG_RERANKER_PROVIDER", "llm") or "llm").lower(),
    # Optional: per-call model override for the "llm" reranker — point
    # at a smaller/faster model (e.g. "gemini-2.5-flash") than the main
    # GEMINI_MODEL/CLAUDE_MODEL used for answer generation. Empty =
    # use the provider's default.
    "RAG_RERANKER_MODEL": os.environ.get("RAG_RERANKER_MODEL", ""),
    # "rerank but never drop" mode for the LLM reranker — keep items
    # the model omitted, append in pre-rerank order. Off by default.
    "RAG_RERANK_KEEP_DROPPED": (
        os.environ.get("RAG_RERANK_KEEP_DROPPED", "false").lower() == "true"
    ),
    # Score fusion (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.4 / D2). When on
    # (with RAG_USE_RERANKER), the reranker does NOT replace the hybrid
    # order — instead each candidate's final score is a weighted blend of
    # its (min-max normalized) RRF score and the reranker's relevance
    # (Cohere's real cross-encoder relevance_score; a positional proxy for
    # the LLM judge). Replacing RRF wholesale was measured net-zero
    # (roadmap §2.2 — paraphrase wins cancelled by exact-phrase losses);
    # fusion is the path that keeps RRF's exact-phrase strength while
    # adding the reranker's paraphrase lift. A reranker-dropped candidate
    # is NOT removed — it degrades gracefully to its weighted RRF share
    # (so a high-RRF hit the reranker ignored can still rank, though a
    # strongly-reranked paraphrase can still displace it). When on, the
    # hard RAG_RERANK_LOCK_TOP_N split is bypassed (fusion is its soft
    # form). Off by default.
    "RAG_RERANK_FUSION": (os.environ.get("RAG_RERANK_FUSION", "true").lower() == "true"),
    # Reranker's share of the fused score in [0,1]; (1 - weight) is RRF's.
    # 0.5 is an UNTUNED placeholder — D2 is "hard to calibrate" and the
    # per-query-type weight is the actual work: sweep it against the
    # retrieval-suite MRR/recall_at_n metric. w=0 reproduces pure-RRF
    # order; w=1 is pure reranker relevance.
    "RAG_RERANK_FUSION_WEIGHT": float(os.environ.get("RAG_RERANK_FUSION_WEIGHT", "0.6")),
    # Q2.1 — per-query-type fusion weights (the "actual work" the comment
    # above names). An empty string means "fall back to RAG_RERANK_FUSION_WEIGHT"
    # so the mechanism is INERT until calibrated. Rationale (roadmap §2.2 +
    # §4.4): exact-phrase queries are RRF/keyword's strength — give the
    # reranker a SMALL share so it can't displace an exact hit; paraphrase
    # queries are where the cross-encoder lifts recall — give it a LARGER
    # share. `_classify_query_type` (reranker.py) picks the lane from the raw
    # query (quoted / short / title-cased ⇒ exact; longer NL ⇒ paraphrase).
    # Calibrate by sweeping each against the retrieval-suite precision_at_k /
    # mrr / recall_at_n, then set the winners here.
    "RAG_RERANK_FUSION_WEIGHT_EXACT": (os.environ.get("RAG_RERANK_FUSION_WEIGHT_EXACT", "") or ""),
    "RAG_RERANK_FUSION_WEIGHT_PARAPHRASE": (
        os.environ.get("RAG_RERANK_FUSION_WEIGHT_PARAPHRASE", "") or ""
    ),
    # Q2.4 — GraphRAG ranking-fusion (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.3 / A1).
    # After hybrid retrieval, inject one-hop TaskDependency neighbours of the top
    # task hits into the result set with a decayed score, so a relational query
    # ("what's blocked by the framer-motion spike?") surfaces the graph-related
    # task even when it shares no text with the query. NEVER runs on typeahead
    # (search.py mode guard). Cost: one extra DB query + one OpenSearch fetch on
    # the agent retrieval path. ACL is inherited (neighbours fetched through the
    # same acl_user_ids filter).
    "RAG_GRAPH_EXPANSION": (os.environ.get("RAG_GRAPH_EXPANSION", "true").lower() == "true"),
    # Injected neighbour score = source-hit score × this decay (keeps the
    # pulled-in task just below the hit that pulled it).
    "RAG_GRAPH_WEIGHT": float(os.environ.get("RAG_GRAPH_WEIGHT", "0.9")),
    # Bound the work: expand at most N top task hits, inject at most M neighbours.
    "RAG_GRAPH_MAX_SOURCES": int(os.environ.get("RAG_GRAPH_MAX_SOURCES", "5")),
    "RAG_GRAPH_MAX_NEIGHBORS": int(os.environ.get("RAG_GRAPH_MAX_NEIGHBORS", "5")),
    # A1-ext — multi-hop traversal depth. 1 = the original one-hop
    # behavior; 2 surfaces transitive dependencies ("what's downstream of
    # the spike?" reaches what the blocked task itself gates) at
    # score × RAG_GRAPH_WEIGHT**2 and one extra TaskDependency query.
    # **Default 2** per the measured A/B on
    # graph_native_2hop_downstream_of_framer_spike (hops=1: recall 0.0 →
    # hops=2: recall 1.0, one-hop + gibberish guards unaffected — the
    # source gate is hop-independent). Set 1 to restore the Q2.4 radius.
    "RAG_GRAPH_MAX_HOPS": int(os.environ.get("RAG_GRAPH_MAX_HOPS", "2")),
    # A1-ext — extra multiplier for REVERSE steps (traversing
    # blocked→blocker, i.e. surfacing an upstream blocker). 1.0 = the
    # original undirected behavior; < 1.0 biases toward downstream
    # neighbours without hiding upstream ones. A/B-able per query class
    # via agent_eval_compare before any default change.
    "RAG_GRAPH_REVERSE_WEIGHT": float(os.environ.get("RAG_GRAPH_REVERSE_WEIGHT", "1.0")),
    # A1-ext — vector-only relational entry. Empty (default) = OFF: the
    # keyword-anchor gate stands and vector-only hits never seed
    # expansion (the gibberish guard). Set to a post-fusion score floor
    # to let a strong vector-only hit (e.g. a cross-lingual relational
    # query sharing no token with the task) seed expansion too.
    # **Calibration warning (measured 2026-07):** on the current RRF
    # scale this floor CANNOT be tuned safely — rank-based fusion
    # flattens similarity, so gibberish vector noise at rank 1 scores
    # exactly like a genuine cross-lingual rank-1 hit (both 0.0328 on
    # the fixture). Leave OFF until raw kNN cosine similarity is plumbed
    # through fusion; the red `graph_native_crosslingual_vector_entry`
    # retrieval case is the standing target for that follow-up.
    "RAG_GRAPH_VECTOR_FLOOR": os.environ.get("RAG_GRAPH_VECTOR_FLOOR", ""),
    # Cohere Rerank — used when RAG_RERANKER_PROVIDER=cohere.
    # Get an API key at https://dashboard.cohere.com/api-keys
    # Pricing as of late 2025 is ~$2 / 1k queries.
    "COHERE_API_KEY": os.environ.get("COHERE_API_KEY", ""),
    "COHERE_RERANK_MODEL": os.environ.get("COHERE_RERANK_MODEL", "rerank-v3.5"),
    "COHERE_RERANK_BASE_URL": os.environ.get(
        "COHERE_RERANK_BASE_URL", "https://api.cohere.com/v2/rerank"
    ),
    # Network timeout for the rerank call. Cohere's p95 is ~300 ms;
    # we cap at 10 s so a hung call falls back to pre-rerank order
    # instead of dominating turn latency.
    "COHERE_RERANK_TIMEOUT_S": float(os.environ.get("COHERE_RERANK_TIMEOUT_S", "10")),
    # Phase 8 — conversation session memory.
    # How many prior (query, answer) pairs to prepend into the model
    # context on follow-up /ask/ calls within the same session.
    "SESSION_MAX_PRIOR_TURNS": int(os.environ.get("SESSION_MAX_PRIOR_TURNS", "3")),
    # Minutes of inactivity before a session is considered expired.
    # An expired session ID silently creates a fresh session.
    "SESSION_TTL_MINUTES": int(os.environ.get("SESSION_TTL_MINUTES", "30")),
    # Phase 9 — chunking refinement.
    # How many preceding messages to fold into each chat_message
    # chunk's `search_text` for embedding context. Set to 0 to
    # disable (back to Phase-3 behavior). Requires an
    # `opensearch_reindex` after change to take effect on existing
    # chunks.
    "RAG_CHAT_CONTEXT_WINDOW": int(os.environ.get("RAG_CHAT_CONTEXT_WINDOW", "2")),
    # Phase 10 — LLM query rewriting (agent path only).
    # When on, the agent's `search_knowledge_base` tool expands the
    # query into N variants via the active ModelClient before hitting
    # OpenSearch, then RRF-fuses results across all variants. Adds one
    # LLM call + N embedding calls per agent search. Does NOT affect the
    # Spotlight typeahead endpoint — it never passes `rewrite=True`.
    #
    # Enabled by default as of this rollout: measured +2 net pass / 0
    # regressions on the agent eval suite (SPOTLIGHT_OPTIMIZATION_ROADMAP.md
    # §1.1) with the tuned RAG_REWRITE_ORIGINAL_WEIGHT=2.0. The rewriter
    # inherits the active synthesis model unless RAG_REWRITE_MODEL (below)
    # points it at a faster one. Set RAG_USE_QUERY_REWRITE=false to
    # disable per-deploy.
    "RAG_USE_QUERY_REWRITE": (os.environ.get("RAG_USE_QUERY_REWRITE", "true").lower() == "true"),
    "RAG_REWRITE_NUM_VARIANTS": int(os.environ.get("RAG_REWRITE_NUM_VARIANTS", "3")),
    # Optional fast-model override for the query rewriter — decouples it
    # from the synthesis model (the first concrete piece of the B3
    # planner/synthesiser tier split). Producing a few keyword variants
    # is trivial, so on a heavy-synthesis deploy (GEMINI_MODEL=*-pro,
    # CLAUDE_MODEL=*-sonnet) pointing this at a fast model
    # ("gemini-2.5-flash", a Haiku) drops the rewrite's latency tax
    # without changing the answer model. Must name a model of the ACTIVE
    # provider (same constraint as RAG_RERANKER_MODEL). Empty → client
    # default (today's GEMINI_MODEL is already flash, so this is inert
    # until synthesis is upgraded). Changing it changes the measured
    # config — re-run the §1.1 A/B before relying on a new value.
    "RAG_REWRITE_MODEL": os.environ.get("RAG_REWRITE_MODEL", ""),
    # E1 — parallel tool execution (SPOTLIGHT_FUTURE_ARCHITECTURE.md §6,
    # Tier 1; roadmap §5.5). When True and the model returns a batch of
    # >1 function calls in one step, the controller dispatches them
    # concurrently on a bounded ThreadPoolExecutor instead of the serial
    # for-loop — a compound query fanning out into 3 searches pays the
    # slowest call, not the sum. Guard rails: only batches where EVERY
    # call is a known, read-only tool (any `requires_approval` write or
    # unknown tool keeps the serial path byte-for-byte, preserving the
    # approval-pause semantics); all events/DB writes stay on the
    # controller thread in call order, so AgentStep rows and the message
    # transcript are byte-identical to serial; each worker closes its DB
    # connections. **Default false** (concurrency + ORM-in-threads is
    # gate-first territory): flip criterion is behavior-suite parity via
    # `agent_eval_compare --judge --b-overrides '{"RAG_PARALLEL_TOOLS":
    # true}'` plus a duration_ms win on the compound cases
    # (complete_four_part_wrd / complete_cross_project_five_facts). Note
    # the win is model-dependent — it only pays when the model actually
    # emits parallel batches.
    "RAG_PARALLEL_TOOLS": (os.environ.get("RAG_PARALLEL_TOOLS", "false").lower() == "true"),
    # Executor cap per batch — bounds the per-request DB-connection burst.
    "RAG_PARALLEL_TOOLS_MAX_WORKERS": int(os.environ.get("RAG_PARALLEL_TOOLS_MAX_WORKERS", "4")),
    # B3 — provider tier split for the AGENT LOOP itself
    # (SPOTLIGHT_FUTURE_ARCHITECTURE.md §3, Tier 1): run the loop's
    # PLANNING steps (tool selection) on this fast model while the final
    # SYNTHESIS keeps the user's chosen model. A step is only known to be
    # synthesis after the model responds, so the controller buffers the
    # planning pass's text and, when it turns out to be a final answer,
    # DISCARDS that draft and re-generates it once on the user's model
    # (cost: same one smart call + N cheap planning calls + one wasted
    # draft; win: every planning round-trip at fast latency — the doc's
    # "cheapest big TTFT lever", ~3-5s/step on pro → ~1s on flash).
    # Guards in `_resolve_planning_override`: inert when empty, when equal
    # to the effective synthesis model (the server default GEMINI_MODEL is
    # already flash, so this only bites for users who picked pro), or when
    # the provider prefix doesn't match the active provider (preventive —
    # a mid-loop model error kills the run).
    # **Default OFF (empty)**: the doc warns fast planners can pick worse
    # tools; flip criterion is an `agent_eval_compare --judge` A/B with
    # GEMINI_MODEL=gemini-3.1-pro-preview as baseline showing behavior
    # parity + the TTFT win. Intended production value: "gemini-3.5-flash".
    "RAG_PLANNING_MODEL": os.environ.get("RAG_PLANNING_MODEL", ""),
    # C3 — session working memory / tool-result cache
    # (SPOTLIGHT_FUTURE_ARCHITECTURE.md §4, Tier 1). When True, a
    # follow-up turn in the SAME AgentSession that re-calls a read-only
    # tool with identical args reuses the cached result instead of
    # re-executing it ("list my tasks" → "which of those is highest
    # priority?" stops re-fetching the list). Redis-backed via
    # django.core.cache (embeddings-L2 pattern: never raises, degrades
    # to re-execution); write tools are never cached and a successful
    # APPROVED write invalidates the whole session (generation bump).
    # Freshness tradeoff: same-user agent writes invalidate, the TTL
    # bounds everything else — but ANOTHER user's edit within the TTL
    # can serve a stale read. That documented window is why this ships
    # **default false**; flip criterion: multi-turn behavior parity
    # (evals pass no session_id, so the suite is unaffected either way),
    # a manual two-turn hit check (`cached: true` on the second turn's
    # tool_call_result), and no staleness complaints in dogfood.
    "RAG_SESSION_TOOL_CACHE": (os.environ.get("RAG_SESSION_TOOL_CACHE", "false").lower() == "true"),
    # Per-entry TTL. 300 s covers the "rapid follow-ups in one sitting"
    # window without letting stale workspace reads live long.
    "RAG_SESSION_TOOL_CACHE_TTL_S": int(os.environ.get("RAG_SESSION_TOOL_CACHE_TTL_S", "300")),
    # Phase 3.2 — self-critique reflection step. When True, after the
    # agent produces its draft final answer, a second LLM call re-reads
    # the draft against the captured tool results and may produce a
    # revised final answer (precision-tightening only — no extra tool
    # rounds). Adds +1 LLM call per ask that reaches a final answer.
    # Off by default; opt-in via env or per-call settings override.
    "RAG_AGENT_SELF_CRITIQUE": (
        os.environ.get("RAG_AGENT_SELF_CRITIQUE", "false").lower() == "true"
    ),
    # Critique-with-retrieval (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.1/§4.2).
    # Sub-flag of RAG_AGENT_SELF_CRITIQUE: when BOTH are True, the critique
    # pass may issue ONE more round of read-only retrieval to fix a
    # *completeness* gap (the shipped precision-only critique can't
    # re-retrieve), then write an improved final answer. When this is
    # False the critique behaves exactly as before (precision-tightening
    # only) — so the measured precision path is untouched. The critique
    # only replaces the draft if it actually retrieved AND produced an
    # answer; otherwise the draft is preserved verbatim.
    "RAG_CRITIQUE_RETRIEVAL": (os.environ.get("RAG_CRITIQUE_RETRIEVAL", "false").lower() == "true"),
    # Step budget for the retrieval continuation above: 2 = at most one
    # read tool call + one final answer. Bounds the latency/cost the
    # critique can add.
    "RAG_CRITIQUE_MAX_STEPS": int(os.environ.get("RAG_CRITIQUE_MAX_STEPS", "2")),
    # Programmatic abstention gate (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.1).
    # When True, a turn that ATTEMPTED retrieval but surfaced no evidence
    # (a semantic search returned zero matches and no other read tool
    # succeeded) and did not already abstain has its answer replaced with
    # an honest "couldn't find it" — a deterministic backstop against
    # hallucinating from no grounding. An empty STRUCTURED result (no
    # overdue tasks) counts as evidence ("the answer is zero"), so the
    # gate does NOT fire on it. Scoped to fresh workspace queries: skipped
    # when seed_sources or prior_turns are present (thread/note Q&A and
    # multi-turn carry their own grounding). Buffers the answer (TTFT cost
    # like self-critique) — off by default; an A/B lever measured by the
    # `abstention_correct` eval metric.
    "RAG_ABSTENTION_GATE": (os.environ.get("RAG_ABSTENTION_GATE", "false").lower() == "true"),
    # Per-context tool subsetting (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.5).
    # When True, peripheral tool families (GitHub PRs, calendar, todos,
    # me-scoped) are dropped from the model's declared tool list for a
    # query that shows no keyword signal for them — shrinking the ~50-tool
    # surface (and prompt) to the relevant slice. Core task/note/chat/
    # project/analytics tools are NEVER dropped. Honest framing: this is a
    # SURFACE / COST / LATENCY reduction with a *hypothesized*
    # tool-selection benefit; the offline suite confirms no-regression
    # (no case needs a peripheral family) but cannot show the quality win
    # — validate that on production tool-selection via the F2 judge
    # sampler. Limitation: the decision is made ONCE from the raw query,
    # one-shot, with no mid-loop re-expansion — so a query that needs a
    # family it didn't signal (e.g. "prep for next week" needing the
    # calendar without a calendar keyword) can't reach it. Conservative
    # keep-direction mitigates; off by default, opt-in.
    "RAG_TOOL_SUBSETTING": (os.environ.get("RAG_TOOL_SUBSETTING", "false").lower() == "true"),
    # Quality round 2 — collapse MIRROR results (a project's PM channel,
    # a thread inheriting its channel title, a milestone's backing task,
    # a DM titled after the person): keep only the highest-ranked row
    # per normalized title across entity types + one surface per chat
    # channel per title. Built when a STALE local index (pre-subfield
    # mapping — see agent_eval's index-drift preflight) made mirrors
    # crowd the top-N ("Q2 Roadmap · …" three times in one top-5).
    # **Default OFF — measured on a healthy index the retrieval A/B
    # REGRESSED (66-case suite: pass 64→61, recall_at_n 0.967→0.924,
    # mrr 0.858→0.847): with proper lexical subfields the mirrors rank
    # sanely and the collapse removes legitimately-useful rows.** Kept
    # as an opt-in lever for typeahead-UX experiments (three identical
    # rows in the Cmd-K overlay is still ugly); re-A/B before flipping.
    "RAG_COLLAPSE_MIRROR_RESULTS": (
        os.environ.get("RAG_COLLAPSE_MIRROR_RESULTS", "false").lower() == "true"
    ),
    # F2 — online judge sampling (SPOTLIGHT_QUALITY_ARCHITECTURE.md §F2).
    # Fraction (0.0–1.0) of completed agent runs the `agent_judge_sample`
    # cron command scores with the LLM judge, so production faithfulness /
    # citation / completeness can be trended vs the fixed offline suite.
    # **Default 0.1 (ENABLED)** — this is the data-collection surface the
    # built-but-OFF levers (critique, tool-subsetting, per-class fusion) need
    # for a real verdict; the offline suite can't see their payoff. Each judged
    # run costs ~1 LLM call and the command caps cost per pass via `--limit`,
    # so 10% is a low, bounded spend; set 0.0 to disable. Sampling is
    # deterministic by run_id hash, so the effective rate matches this value
    # regardless of how often the cron fires. Runs OFF the user request path —
    # it does nothing until a scheduler actually invokes the command:
    #     0 * * * *  cd /app/backend_django && python manage.py agent_judge_sample
    # Trend / drift: `agent_judge_sample --report [--alert]` (see Q0.5).
    "RAG_JUDGE_SAMPLE_RATE": float(os.environ.get("RAG_JUDGE_SAMPLE_RATE", "0.1")),
    # C1 near-real-time conversation memory (§4.7 / Q2.3). When True, a run
    # saved as `done` is immediately indexed into the per-user conversation
    # lane (`ingestion.ingest_conversation_run`) instead of waiting up to 10
    # minutes for the incremental reindex cron — so "what did we just discuss
    # about X?" works seconds after the answer, even in a fresh session.
    # **Default true**: the hook runs after the stream's last byte (zero
    # user-visible latency, ~1 embed call), is best-effort (failure only
    # logs; the run stays `done`), and the cron remains the backstop — the
    # RagChunk hash-diff makes the overlap a no-op. Set false to fall back
    # to cron-only indexing (e.g. to shed embed calls from web workers).
    "RAG_CONVERSATION_INDEX_ON_COMPLETE": (
        os.environ.get("RAG_CONVERSATION_INDEX_ON_COMPLETE", "true").lower() == "true"
    ),
    # Q0.4 — tool-selection north-star (SPOTLIGHT_QUALITY_ARCHITECTURE.md §4.5,
    # roadmap §1: ">=0.90"). The agent_eval harness REPORTS the aggregate
    # continuous tool-selection scalars (tool_recall / tool_excl_ok) against
    # this floor on every run, turning the previously-orphaned scalar
    # ("measures but nothing gates on it") into a tracked metric with a named
    # target. Enforcement (exit 1 on a miss) is opt-in via `agent_eval
    # --metric-gate` — observe-only by default, because the fixture gold for
    # the multi-tool cases is still being validated and enforcing-by-default
    # would regress a suite the team runs green. Per-case tool gold stays
    # non-gating (path-sensitive); only the aggregate is checked.
    "RAG_TOOL_SELECTION_NORTH_STAR": float(os.environ.get("RAG_TOOL_SELECTION_NORTH_STAR", "0.90")),
    # Q0.5 — F2 drift alert threshold (SPOTLIGHT_QUALITY_ARCHITECTURE.md §F2:
    # "sample N%, score async, alert on regression"). `agent_judge_sample
    # --report` compares the recent half of the window against the prior half;
    # if any axis (faith / cite / compl) drops by more than this absolute
    # delta it flags drift, and with `--alert` exits non-zero so a cron/CI
    # wrapper can page. Default 0.05 (a 5-point drop on the 0-1 scale).
    "RAG_JUDGE_DRIFT_THRESHOLD": float(os.environ.get("RAG_JUDGE_DRIFT_THRESHOLD", "0.05")),
    # Observability for Gemini implicit-cache hit rate. When True,
    # gemini_client._log_usage emits one INFO log per `generate_step`
    # call with `prompt_tokens`, `cached_tokens`, and a cache-hit %.
    # Flip on (`LLM_LOG_USAGE_METADATA=true`) to verify that the system
    # prompt + tool declarations are being served from cache after the
    # first request of a session — Gemini 2.5+/3.x caches stable
    # prefixes of ≥1024 (Flash) / ≥4096 (Pro) tokens automatically.
    # Off by default to keep production logs quiet.
    "LLM_LOG_USAGE_METADATA": (os.environ.get("LLM_LOG_USAGE_METADATA", "false").lower() == "true"),
    # Phase 3.5 — rolling-summary multi-turn context. When True AND a
    # session has more than `SESSION_MAX_PRIOR_TURNS` prior turns, the
    # earliest turns are condensed into a single short summary that is
    # prepended to the messages alongside the last `SESSION_MAX_PRIOR_TURNS`
    # turns verbatim. Lets long conversations retain early-turn context
    # the verbatim window would otherwise drop. Costs one summary LLM
    # call per turn that triggers the summary path (i.e. only when the
    # session already has > N prior turns). Off by default.
    "RAG_SESSION_ROLLING_SUMMARY": (
        os.environ.get("RAG_SESSION_ROLLING_SUMMARY", "false").lower() == "true"
    ),
    # Phase 4.2 — re-sort source chips by citation density at end-of-turn.
    # When True, the final `sources` event (emitted just before `done`)
    # reorders chips so entities the answer actually cites surface
    # leftmost. Stable for ties (preserves tool-emission order).
    # Default True — clean UX win, low risk. Flip to False if the chip
    # reshuffle at done-time turns out to be jarring.
    "RAG_RANK_SOURCES_BY_CITATION": (
        os.environ.get("RAG_RANK_SOURCES_BY_CITATION", "true").lower() == "true"
    ),
    # Phase 5.1 — L2 Redis cache for query-side embeddings. Sits BEHIND
    # the existing per-worker LRU (L1) in `embeddings/__init__.py`, so
    # the typeahead hot path keeps its zero-network L1 hits AND a
    # cross-worker / post-restart hit also skips the embedding API.
    # Key = (model_name, sha256(text)); value = the float vector.
    # TTL in seconds — set to 0 to disable L2 entirely (L1 LRU stays).
    "RAG_EMBEDDING_CACHE_TTL_S": int(os.environ.get("RAG_EMBEDDING_CACHE_TTL_S", "600")),
    # Phase 14 — live web search via Tavily.
    # Sign up at https://tavily.com to get a free API key (1 000 req/month).
    # Set TAVILY_API_KEY in .env (local) and Railway env vars (production).
    # Leave empty to disable web search — the agent will surface a clean
    # error rather than crashing when the key is absent.
    "TAVILY_API_KEY": os.environ.get("TAVILY_API_KEY", ""),
    # User-selectable LLM provider/model catalog — what the Settings →
    # Spotlight → AI Model picker offers, and the allowlist a saved
    # preference is validated against.
    #
    # Populated at the bottom of this file from `apis/llm_models.yaml`,
    # which is THE file to edit when a provider ships a new model (it
    # carries the per-model daily caps too — see the note on
    # TIER_QUOTAS). Left as a placeholder here so the SEARCH_ENGINE
    # literal still reads as the complete key set.
    #
    # When a user's saved model leaves the catalog — the routine outcome
    # of a refresh — `resolve_user_choice` in llm/choice.py resolves them
    # to THAT PROVIDER's default, deliberately not the global one: the
    # global default is Gemini, so anything else would move every Claude
    # and GPT user onto Gemini without them noticing.
    "MODEL_CATALOG": [],
    # Quotas by subscription tier — free / core / pro / max / enterprise
    # — resolved from the user's *effective* tier (best of
    # `CustomUser.tier` and the `plan` of every team they belong to)
    # by `origin.search_engine.quota`.
    #
    # Daily quotas (reset at UTC midnight):
    #   - `llm_ask_daily`: total agent asks per day (counted on first
    #     answer_delta).
    #   - `web_search_daily`: Tavily searches per day (counted on
    #     successful tool execution).
    #   - `model_daily[<model>]`: per-model asks per day. A model
    #     missing from a tier's dict is treated as unlimited for that
    #     tier. NOT written here — derived per class from
    #     `apis/llm_models.yaml`, which is what makes that "missing =
    #     unlimited" rule un-trippable when models change.
    # Monthly quotas (UTC calendar month; creations counted — deleting
    # a resource does not refund quota):
    #   - `task_create_monthly`: TaskMaster rows created per month.
    #   - `note_create_monthly`: notes created per month (personal +
    #     task + chat notes share one cap).
    # Other dimensions:
    #   - `message_retention_days`: chat history window visible to the
    #     user (older messages are hidden, never deleted — upgrading
    #     restores them).
    #   - `upload_max_mb`: per-file attachment size ceiling.
    # A limit value of `None` (or a missing key) means unlimited.
    # All dimensions are LIVE. Tune per environment without a deploy
    # via the TIER_QUOTAS_JSON env override below; canonical rationale
    # for the numbers: genos-docs operations/SUBSCRIPTION_TIERS.md.
    "TIER_QUOTAS": {
        # `model_daily` is deliberately EMPTY in every tier below — it is
        # filled from `apis/llm_models.yaml` at the bottom of this file.
        # A model missing from `model_daily` is UNLIMITED (not zero), so
        # under the old hand-written table adding a catalog rung and
        # forgetting one of four tiers silently uncapped a premium model.
        # Deriving it per class from the catalog makes that unexpressible.
        # Everything else here — the per-tier totals — stays hand-set.
        #
        # UX-pillar capability keys (agent_tool_level, max_effort,
        # auto_effort, agent_memory, agent_history_retention_days,
        # integrations, digest_cadence) carry the LIVE experience
        # ladder — tiers sell capability, volume caps are the fair-use
        # footer. Rationale and target table: genos-docs
        # operations/UX_TIER_MODEL_PLAN.md. A MISSING capability key
        # resolves permissive (see quota.py) so a TIER_QUOTAS_JSON
        # override that predates a key can't silently downgrade anyone
        # — which also means a rollback of ONE pillar is "restore that
        # key to its permissive value", not a revert.
        #
        # Free reads as: Genos ANSWERS (drafts writes for pasting),
        # thinks at the default depth, remembers only the live
        # conversation, sees only the workspace.
        "free": {
            "llm_ask_daily": 20,
            "web_search_daily": 10,
            "model_daily": {},  # filled from llm_models.yaml (see below)
            "task_create_monthly": 50,
            "note_create_monthly": 50,
            "message_retention_days": 180,
            "upload_max_mb": 5,
            "agent_tool_level": "read",
            "max_effort": "low",  # = DEFAULT_EFFORT since api #204, so no felt change
            "auto_effort": False,
            "agent_memory": "none",
            "agent_history_retention_days": 30,
            "integrations": [],
            "digest_cadence": None,
        },
        # Paid-tier LLM caps are set by a value-based X/Y/Z tiering model,
        # not a profit gate — genos-docs/operations/LLM_TIER_COST_OPTIMIZATION.md
        # supersedes the old "worst-case COGS <= 2-3x price" rule in
        # SUBSCRIPTION_TIERS.md §1. We're pre-revenue-scale: a deficit is
        # accepted deliberately to win adoption.
        #   X - cost floor: a bounded subsidy, not a ceiling. Premium
        #     models stay single-digit/day per model (they're the
        #     ~JPY60-70/ask outliers) so no single user's worst-case blast
        #     radius is catastrophic; flash is ~free so it can be the
        #     generous headline number.
        #   Y - value fence: the metric is asks/day + premium-model access.
        #     Every LLM dimension steps up by MORE than the price does, so
        #     each upgrade reads as better value per yen.
        #   Z - market anchor: core/pro undercut ChatGPT Plus / Claude Pro
        #     (~$20 / ~JPY3,000); max sits above them as the power-user
        #     anchor that makes pro the default buy (Good-Better-Best).
        #
        # Per-ask cost classes (FX JPY150/USD, LLM_TIER_COST_OPTIMIZATION §3):
        #   flash-class ~JPY1-2  gemini-3.5-flash, claude-haiku-4-5, gpt-5.6-luna
        #   mid-class   ~JPY10-18 gemini-3.1-pro-preview, claude-sonnet-4-6,
        #                         gpt-5.6-terra
        #   premium     ~JPY60-70 claude-opus-4-7, claude-opus-4-8, gpt-5.6-sol
        # So the mid and premium caps are the real subsidy lever, not
        # `llm_ask_daily`.
        #
        # IMPORTANT — why per-model mid caps SHRANK while the tier got
        # more generous: there are now THREE mid rungs and THREE premium
        # rungs instead of two and one. Worst-case-at-cap is "fill the
        # daily total with the priciest models still allowed", so holding
        # the per-model number constant while tripling the model count
        # would triple the premium blast radius. The per-model caps below
        # are sized so the CLASS budget (cap x number of rungs) lands
        # where the tier intends. Ladder ratios and the resulting
        # worst-case multiples:
        #   dimension        core    pro     max    core->pro  pro->max
        #   llm_ask_daily     100    250     500      2.5x       2.0x
        #   mid   (each)       12     25      50      2.08x      2.0x
        #   premium (each)      2      4      10      2.0x       2.5x
        #   price          JPY1200 JPY2500 JPY4900    2.08x      1.96x
        #   worst-case/mo   ~26.2k  ~62.2k ~135.6k
        #   ratio to price   21.8x   24.9x   27.7x
        # All three sit inside the ~20-29x band the current pro/max caps
        # already run at, i.e. the accepted subsidy envelope is unchanged
        # in shape — it is not widened by adding a tier or a provider.
        #
        # core = the entry paid plan (JPY1,200 — the price pro used to
        # be). Limits are close to the old pro tier, trimmed at the mid
        # class so there is real headroom to sell pro into.
        # Core reads as: Genos ACTS (single writes, with approval),
        # thinks thoroughly, remembers your history, sees web +
        # Calendar.
        "core": {
            "llm_ask_daily": 100,
            "web_search_daily": 25,
            "model_daily": {},  # filled from llm_models.yaml (see below)
            "task_create_monthly": 200,
            "note_create_monthly": 200,
            "message_retention_days": 365,
            "upload_max_mb": 25,
            "agent_tool_level": "act",
            "max_effort": "medium",
            "auto_effort": False,
            "agent_memory": "own",
            "agent_history_retention_days": 180,
            "integrations": ["web", "google_calendar"],
            "digest_cadence": None,
        },
        # Pro reads as: Genos ORGANIZES (composite writes — a milestone
        # + task tree in one approval), deep reasoning + adaptive
        # effort, team memory, + GitHub, weekly digest.
        "pro": {
            "llm_ask_daily": 250,
            "web_search_daily": 60,
            "model_daily": {},  # filled from llm_models.yaml (see below)
            "task_create_monthly": 500,
            "note_create_monthly": 500,
            "message_retention_days": None,  # unlimited from pro up
            "upload_max_mb": 50,
            "agent_tool_level": "organize",
            "max_effort": "high",
            "auto_effort": True,
            "agent_memory": "team",
            "agent_history_retention_days": 365,
            "integrations": ["web", "google_calendar", "github"],
            "digest_cadence": "weekly",
        },
        # max = 2x pro on the headline totals for ~1.96x the price, and
        # 2.5x on the premium caps — the deliberate value > price gap is
        # what makes max the anchor that sells pro. A max tier that only
        # matched the price ratio would be a dominated upgrade nobody buys.
        "max": {
            "llm_ask_daily": 500,
            "web_search_daily": 150,
            "model_daily": {},  # filled from llm_models.yaml (see below)
            "task_create_monthly": None,
            "note_create_monthly": None,
            "message_retention_days": None,  # unlimited from pro up
            "upload_max_mb": 100,
            "agent_tool_level": "organize",
            "max_effort": "high",
            "auto_effort": True,
            "agent_memory": "team",
            "agent_history_retention_days": None,
            "integrations": ["web", "google_calendar", "github"],
            "digest_cadence": "daily",
        },
        # Contact-sales tier: everything unlimited except an absolute
        # per-file ceiling. Set manually via `feature_access set-tier`
        # / `set-team-plan` — never sold self-serve.
        "enterprise": {
            "llm_ask_daily": None,
            "web_search_daily": None,
            "model_daily": {},
            "task_create_monthly": None,
            "note_create_monthly": None,
            "message_retention_days": None,
            "upload_max_mb": 200,
            "agent_tool_level": "organize",
            "max_effort": "high",
            "auto_effort": True,
            "agent_memory": "team",
            "agent_history_retention_days": None,
            "integrations": ["web", "google_calendar", "github"],
            "digest_cadence": "daily",
        },
    },
}

# --- LLM model catalog (apis/llm_models.yaml) -------------------------
# The single file to edit when a provider ships a new model. It supplies
# BOTH the picker catalog and the per-model daily caps, because those two
# have to move together: a model absent from `model_daily` is UNLIMITED,
# so a catalog-only edit is a silent uncapping. Caps are declared per
# CLASS (light / middle / highend) there, so a swapped model inherits its
# predecessor's cap automatically.
#
# Loads eagerly and raises on any problem — a bad catalog must not boot.
# Override the path with LLM_MODELS_YAML (tests, or an ops experiment
# with a different lineup).
_llm_catalog = load_llm_catalog(
    os.environ.get("LLM_MODELS_YAML") or (BASE_DIR / "apis" / "llm_models.yaml")
)
SEARCH_ENGINE["MODEL_CATALOG"] = _llm_catalog.catalog
# Exposed whole (not just the catalog list) for per-model capability
# flags — llm/claude_client.py asks it whether a model accepts
# `temperature`. Top-level rather than inside SEARCH_ENGINE because it's
# an object, and TIER_QUOTAS_JSON-style dict overrides shouldn't be able
# to clobber it into something without those methods.
LLM_CATALOG = _llm_catalog

# The credit policy — the COMMERCIAL layer (credit unit, entitlements,
# internal ceilings), separate from the technical rate card above
# because the two change for different reasons on different schedules.
# Same posture as LLM_CATALOG: eager, boot-fatal, object at top level
# so env-dict overrides can't clobber it, path overridable for tests.
# Shadow-only at this stage: nothing here is enforced against a
# customer; `close_request` stamps its versions onto every rollup.
CREDIT_POLICY = load_credit_policy(
    os.environ.get("CREDIT_POLICY_YAML") or (BASE_DIR / "apis" / "credit_policy.yaml")
)

# Tier names must agree in both directions: a tier here with no caps in
# the YAML would run uncapped, and a tier only in the YAML is a typo that
# would otherwise sit unnoticed.
_quota_tiers = set(SEARCH_ENGINE["TIER_QUOTAS"])
_capped_tiers = set(_llm_catalog.model_daily)
if not _capped_tiers <= _quota_tiers:
    raise ValueError(
        f"llm_models.yaml tier_caps names unknown tier(s) "
        f"{sorted(_capped_tiers - _quota_tiers)}; TIER_QUOTAS has {sorted(_quota_tiers)}"
    )
for _tier, _cfg in SEARCH_ENGINE["TIER_QUOTAS"].items():
    # Absent from the YAML == declared `unlimited` there (enterprise).
    _cfg["model_daily"] = _llm_catalog.model_daily.get(_tier, {})

# Optional full-replace override for the tier quota table, so ops can
# tune limits per environment (or tests can rig tiny ones) without a
# code change. Value = a JSON object with the same shape as the
# default above. Invalid JSON fails loud at boot — better than
# silently running with default limits.
#
# ⚠️ FULL replace, and it runs AFTER the YAML injection above — so an
# override that omits `model_daily` uncaps every model for that tier.
# The YAML's structural guarantee does not extend through this path.
_tier_quotas_json = os.environ.get("TIER_QUOTAS_JSON", "")
if _tier_quotas_json:
    SEARCH_ENGINE["TIER_QUOTAS"] = json.loads(_tier_quotas_json)

# When a user's chosen model has exhausted its per-model daily cap
# (`model_daily`) but the umbrella `llm_ask_daily` still has headroom,
# fall back to the next-cheaper same-provider model that has room instead
# of returning 429. Dark-shipped OFF: flipping it silently changes which
# model answers a paid user's ask, so it stays a deliberate ops toggle.
# The umbrella `llm_ask_daily` gate is unaffected (no model swap can beat
# a total-ask cap). See origin.search_engine.agent_views._resolve_quota_fallback.
SEARCH_ENGINE["MODEL_QUOTA_FALLBACK"] = (
    os.environ.get("MODEL_QUOTA_FALLBACK", "false").lower() == "true"
)

# Effort levels: users pick provider + low/medium/high instead of a
# model; (provider, effort) resolves through llm_models.yaml `efforts`
# (synthesis model = the provider's rung, loop params from the profile)
# and sub-process calls (rewrite/rerank/summaries) pin to the
# `subprocesses` rungs. Dark-shipped OFF. The flip is a provable no-op
# for users with no saved preference — the medium profile is pinned
# byte-identical to today's env defaults by
# test_llm_catalog_yaml.test_MEDIUM_INVARIANT_* — but it DOES change
# sub-process models for everyone (rewrite/rerank move to the light
# rung), so the flip is gated on the eval comparison in
# genos-docs operations/EFFORT_LEVELS.md.
SEARCH_ENGINE["AGENT_EFFORT_LEVELS"] = (
    os.environ.get("AGENT_EFFORT_LEVELS", "false").lower() == "true"
)

# Adaptive effort (UX tier model §5.3): a saved "auto" effort routes
# each ask through a rung-0 classification call (low|medium|high),
# then clamps to the tier's max_effort. Removes a config chore rather
# than adding a control — the premium experience is Genos choosing per
# question. Dark-shipped OFF; with the flag off a saved "auto" resolves
# like an unset preference (DEFAULT_EFFORT), so rollback is safe.
# Router cost must be measured before flipping (AGENT_COST_OPTIMIZATION
# has the method); it fails open to "medium" on any error or garbage.
SEARCH_ENGINE["AGENT_AUTO_EFFORT"] = os.environ.get("AGENT_AUTO_EFFORT", "false").lower() == "true"

# Per-effort thinking budgets (llm_models.yaml `efforts.*.thinking_budget`)
# applied to the agent loop's Gemini calls. Separate from
# AGENT_EFFORT_LEVELS so it can flip — and roll back — without touching
# the effort system. Thinking bills at the OUTPUT rate; the 2026-07-26
# anatomy run measured 1,323 thought tokens/request at medium (~12% of
# request cost) plus the time-to-first-token they take to produce.
# Requires AGENT_EFFORT_LEVELS (no profile = no budget to read).
SEARCH_ENGINE["AGENT_THINKING_BUDGETS"] = (
    os.environ.get("AGENT_THINKING_BUDGETS", "false").lower() == "true"
)

# Two-tier agent loop: planning steps on the effort profile's
# `loop_rung` model, synthesis on the effort's own rung, via the B3
# discard-and-rerun split. Loop calls are 99%+ of request cost and most
# steps are tool selection — at medium a flash-lite planning call costs
# ~$0.006 vs ~$0.028 on 3.6-flash. Requires AGENT_EFFORT_LEVELS;
# RAG_PLANNING_MODEL still wins as the no-deploy operator override.
SEARCH_ENGINE["AGENT_TWO_TIER_LOOP"] = (
    os.environ.get("AGENT_TWO_TIER_LOOP", "false").lower() == "true"
)

# Claude prompt caching (LLM_TIER_COST_OPTIMIZATION.md §8.2). Anthropic
# does NOT cache automatically — a cache_control breakpoint must mark
# the stable prefix. We mark the TOOL DECLARATIONS block (~13k tokens,
# identical on every agent call by design — declarations never vary per
# effort/request precisely so caches like this one hold). Cached reads
# bill ~0.1x and prefill faster on steps 2+ of every ask. Default ON:
# caching cannot change sampled output, only cost/latency; this env var
# is the kill-switch if the backend ever rejects the parameter.
# Registry-generated system-prompt sections (write-tool list + tool
# directory) instead of the hand-maintained copies that had drifted.
# Model-visible (the prompt string changes), so dark-shipped OFF and
# flipped only after cases.yaml + agent-trajectory-diff pass — see
# origin/search_engine/agent/prompts.py `agent_system_prompt()`.
SEARCH_ENGINE["AGENT_CHEATSHEET_FROM_REGISTRY"] = (
    os.environ.get("AGENT_CHEATSHEET_FROM_REGISTRY", "false").lower() == "true"
)

SEARCH_ENGINE["CLAUDE_PROMPT_CACHE"] = (
    os.environ.get("CLAUDE_PROMPT_CACHE", "true").lower() == "true"
)

# Explicit Gemini context cache for the agent's static prefix (system
# prompt + tool declarations). Implicit caching is best-effort and the
# 2026-07-26 anatomy run measured it missing on ~half of medium's loop
# calls — those misses were roughly half of a medium request's cost.
# The explicit cache guarantees the prefix bills at the cached rate on
# every step. Fail-open by construction (any cache failure sends the
# full prefix exactly as today), dark until the eval A/B clears it.
# See origin/search_engine/llm/gemini_cache.py.
SEARCH_ENGINE["GEMINI_EXPLICIT_CACHE"] = (
    os.environ.get("GEMINI_EXPLICIT_CACHE", "false").lower() == "true"
)
SEARCH_ENGINE["GEMINI_EXPLICIT_CACHE_TTL_S"] = int(
    os.environ.get("GEMINI_EXPLICIT_CACHE_TTL_S", "3600")
)

# --- Internal AI cost meter (Phase 0) ---
# Writes the `AiSpendEvent` / `AiRequestCost` accounting ledger: one row
# per paid provider call, plus a per-request rollup. Pure observation —
# it never changes which model answers, how many steps run, or what a
# user is allowed to do. Enforcement is a separate, later flag.
#
# Default OFF so the tables land and the code deploys before anything
# writes, per the project's dark-ship convention. Flip it on right after
# deploy: the meter's whole purpose is to replace per-ask cost estimates
# that currently span an order of magnitude, and it collects nothing
# while off.
#
# Declared HERE rather than read with a bare `.get(..., default)`
# because AGENT_COLLECT_METRICS did that and became unsettable without
# a code edit — its docstring still claims an operator can flip it.
SEARCH_ENGINE["AI_COST_METER"] = os.environ.get("AI_COST_METER", "false").lower() == "true"

# Shadow credits: quote + balance snapshot at request start, a posted
# ledger charge at close. WRITES ONLY — nothing is enforced, no user
# ever sees a number, and the old ask limits stay authoritative
# (Phase 1 of the metering strategy). Requires AI_COST_METER; without
# the meter there is no rollup to derive a charge from.
#
# Off by default like every other control here: flipping it on is the
# start of shadow-mode data collection, which is a deliberate act.
# Making credits AUTHORITATIVE is a Phase 2 decision and deliberately
# has no flag yet — it should not be one typo away.
SEARCH_ENGINE["AI_CREDITS_SHADOW"] = os.environ.get("AI_CREDITS_SHADOW", "false").lower() == "true"

# PHASE 2 — make credits the CUSTOMER'S LIMIT, replacing the daily ask
# count. Requires AI_CREDITS_SHADOW (without a ledger being written, a
# balance only ever goes down by the monthly grant and every user reads
# as full forever — enforcing on a ledger nobody writes to is worse
# than not enforcing).
#
# What flipping this changes:
#   * the ask + both summary surfaces gate on the credit BALANCE vs the
#     request's quoted maximum, not on `llm_ask_daily`;
#   * per-model daily caps and the web-search daily cap stop applying —
#     both are cost-shaping devices that credits subsume, and enforcing
#     them alongside credits would refuse requests the user has paid for;
#   * Free keeps a quiet daily circuit breaker as ABUSE protection only
#     (V2 §4.3) — never presented as a plan limit;
#   * `/agent/features/` starts returning a `credits` block, which is
#     what makes the frontend render credit rows instead of ask counts.
#
# Ships OFF. Flipping it is a commercial act — it changes what a
# customer is allowed to do — and the strategy is explicit that it
# should follow measured evidence, not precede it.
SEARCH_ENGINE["AI_CREDITS_AUTHORITATIVE"] = (
    os.environ.get("AI_CREDITS_AUTHORITATIVE", "false").lower() == "true"
)

# Graded actions for the per-account monthly yen ceilings (the values
# live in credit_policy.yaml `monthly_ceiling_jpy`). BOTH default off:
# over the ceiling always logs a WARNING, and these escalate it.
#
#   ROUTE_CHEAPEST — serve the cheapest same-provider model with quota
#     headroom instead (the user keeps working, on our cheapest metal).
#   PAUSE — 429 new asks with a money-free message. The strongest
#     lever, for genuine abuse only: the strategy is explicit that
#     blocking a real early user costs more than their spend does, so
#     flip this only after a human has read `ai_cost_report --by-user`.
SEARCH_ENGINE["AI_CEILING_ROUTE_CHEAPEST"] = (
    os.environ.get("AI_CEILING_ROUTE_CHEAPEST", "false").lower() == "true"
)
SEARCH_ENGINE["AI_CEILING_PAUSE"] = os.environ.get("AI_CEILING_PAUSE", "false").lower() == "true"

# Free-tier daily ask circuit breaker (V2 §4.3) — OPT-IN, off by
# default (product decision 2026-07-28): with credits authoritative a
# user with balance left must be able to spend it, so the only
# customer-facing stop is the mid-run credits-exhausted stop. Flip this
# only for active abuse (scripted signup farms); the monthly cost
# ceilings above remain the financial backstop regardless.
SEARCH_ENGINE["AI_FREE_DAILY_BREAKER"] = (
    os.environ.get("AI_FREE_DAILY_BREAKER", "false").lower() == "true"
)

# The cost-benchmark regression threshold, in percent: `ai_credit_benchmark
# --check-baseline` exits non-zero when the fixed suite's TOKEN total
# exceeds the stored baseline by more than this. Tokens, not yen — a
# price change must never read as an engineering regression.
SEARCH_ENGINE["AI_BENCHMARK_REGRESSION_PCT"] = float(
    os.environ.get("AI_BENCHMARK_REGRESSION_PCT") or "25"
)

# Per-workspace (team) monthly ceiling in YEN — alert-only, opt-in.
# 0 = off. A team over the line logs a WARNING naming the team; there
# is deliberately no blocking lever here, because pausing N users over
# one member's spend is a human decision, not a threshold's.
SEARCH_ENGINE["AI_TEAM_MONTHLY_CEILING_USD"] = float(
    os.environ.get("AI_TEAM_MONTHLY_CEILING_USD") or "0"
)
if os.environ.get("AI_TEAM_MONTHLY_CEILING_JPY") and not os.environ.get(
    "AI_TEAM_MONTHLY_CEILING_USD"
):
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "AI_TEAM_MONTHLY_CEILING_JPY is set but team ceilings are now "
        "denominated in USD. Set AI_TEAM_MONTHLY_CEILING_USD instead."
    )

# Monthly AI budget in YEN, for `ai_cost_report --alert`. The command
# pro-rates it to the reporting window and logs at ERROR when spend is
# over — which fails the cron run via CronCommand's tripwire.
#
# 0 (the default) means NO budget is configured and nothing is checked.
# Deliberately opt-in: a threshold guessed before any real measurement
# exists would either cry wolf on day one or never fire at all.
#
# This is the only cross-provider budget alarm that can exist here.
# A GCP billing budget is structurally blind to Anthropic and OpenAI,
# which bill outside GCP entirely.
#
# `or "0"` rather than a get() default — docker-compose passes optional
# vars as `${VAR:-}`, so the key is always PRESENT and possibly empty,
# and float("") raises at import (see the note at the top of this file).
SEARCH_ENGINE["AI_MONTHLY_BUDGET_JPY"] = float(os.environ.get("AI_MONTHLY_BUDGET_JPY") or "0")

# --- AI safety ceilings (Phase 0) ---
# Three controls, deliberately at three different strengths. All fail
# OPEN: a check that cannot run must never block a paying user.
#
# 1. PER-REQUEST CEILING — the only one that BLOCKS. Milli-yen; 0 = off.
#    Checked between agent loop steps against this request's accumulated
#    spend, so it bounds a runaway loop — the pathological case a per-user
#    daily cap cannot catch, because a single request can burn a day's
#    budget faster than any daily check runs.
#
#    It is ALSO the number quoted onto AiRequestCost.quoted_max_jpy_milli
#    before the request starts, which is what makes "the charge never
#    exceeds the quote, and we absorb the excess" enforceable rather than
#    aspirational.
#
#    Not instant: an in-flight model call finishes, so real spend can
#    exceed this by one call. Bounded, and the excess is ours.
SEARCH_ENGINE["AI_REQUEST_MAX_JPY_MILLI"] = int(os.environ.get("AI_REQUEST_MAX_JPY_MILLI") or "0")
#    USD-denominated twin, and the one to prefer — the cost system's base
#    unit is USD because that is what providers invoice (see
#    `search_engine/money.py`). The yen variable above still works and
#    still bounds the loop; this one is what the USD quote/absorb columns
#    are written from. Both 0 = no per-request ceiling.
SEARCH_ENGINE["AI_REQUEST_MAX_USD_MICRO"] = int(os.environ.get("AI_REQUEST_MAX_USD_MICRO") or "0")
# 2. PER-USER DAILY ALERT — observation only, never blocks. USD; 0 = off.
#    Logs a WARNING (not ERROR — that would red the cron) naming the user
#    when their day's ledger spend crosses this. Deliberately not
#    enforcing: the strategy doc is explicit that blocking an early user
#    costs more than the spend does, and at this stage a founder learning
#    why someone is expensive beats a wall they hit silently.
#
#    Costs one aggregate query per ask, and ONLY when configured — 0
#    short-circuits before touching the DB.
#    Reads the legacy AI_USER_DAILY_ALERT_JPY only as a name to fail
#    loudly on: an operator who still has the yen variable set would
#    otherwise silently lose their alert when the code switched to USD.
SEARCH_ENGINE["AI_USER_DAILY_ALERT_USD"] = float(os.environ.get("AI_USER_DAILY_ALERT_USD") or "0")
if os.environ.get("AI_USER_DAILY_ALERT_JPY") and not os.environ.get("AI_USER_DAILY_ALERT_USD"):
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "AI_USER_DAILY_ALERT_JPY is set but the per-user spend alert is now "
        "denominated in USD (the cost system's base currency). Set "
        "AI_USER_DAILY_ALERT_USD instead — silently ignoring the old "
        "variable would drop the alert without anyone noticing."
    )
# 3. KILL SWITCH — refuses new agent asks outright, for a provider
#    incident or a runaway we have not diagnosed yet. In-flight runs
#    finish. This is the "stop everything" lever that AGENT_DISABLED_TOOLS
#    (per-tool) and the model pins (per-model) cannot provide.
SEARCH_ENGINE["AI_AGENT_KILL_SWITCH"] = (
    os.environ.get("AI_AGENT_KILL_SWITCH", "false").lower() == "true"
)

# --- Email ---
# Dev default: print emails to the runserver console so engineers don't
# need credentials locally. In production, send via Resend's HTTPS API
# (django-anymail) — Railway blocks/filters outbound SMTP, so SMTP to
# Gmail times out from the deployed container. To enable:
#   EMAIL_BACKEND=anymail.backends.resend.EmailBackend
#   RESEND_API_KEY=re_xxx                 (from resend.com/api-keys)
#   DEFAULT_FROM_EMAIL=Genos <noreply@your-verified-domain>
# Sender domain must be verified at resend.com/domains, or use
# `onboarding@resend.dev` for self-testing (only delivers to the
# Resend account owner's verified address).
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Genos <noreply@example.com>")

ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY", ""),
    # Verifies the Resend tracking webhook (bounce/complaint →
    # suppression list). Svix signing secret from the webhook's settings
    # page at resend.com/webhooks; empty = webhook posts are rejected,
    # which is the safe default.
    "RESEND_SIGNING_SECRET": os.environ.get("ANYMAIL_RESEND_SIGNING_SECRET", ""),
}

# Dark-ship flag for the NOTIFICATION email channel (the outbox enqueue in
# `email_enqueue.py` plus the `email_notify_tick` / `email_digest` crons).
# The transactional mails (verification, password reset, team invite, ops
# report) are NOT gated by this — they must always work. Flip to true in
# prod only once bounce/complaint suppression is live: the notification
# channel shares the transactional mails' Resend domain reputation.
EMAIL_NOTIFICATIONS_ENABLED = (
    os.environ.get("EMAIL_NOTIFICATIONS_ENABLED", "false").lower() == "true"
)

# Coalescer tuning (email_notify_tick). AWAY = a user is emailed only
# when their oldest pending outbox row is at least this old (email is for
# the person who LEFT — anyone active gets the in-app feed and push).
# COOLDOWN = minimum minutes between two notification emails to the same
# user. Tune in staging before prod; the cron's --away-minutes /
# --cooldown-minutes args override per-run.
EMAIL_NOTIFY_AWAY_MINUTES = int(os.environ.get("EMAIL_NOTIFY_AWAY_MINUTES", "10"))
EMAIL_NOTIFY_COOLDOWN_MINUTES = int(os.environ.get("EMAIL_NOTIFY_COOLDOWN_MINUTES", "30"))

# Public origin used to build absolute URLs in outgoing emails (e.g.
# password-reset links). Default matches the dockerised dev frontend
# (see docker/docker-compose.yml, react service on :3000). Override in
# deployed environments to the actual frontend host.
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:3000")

# The API's OWN public origin — for links that must hit Django directly
# (the anonymous unsubscribe endpoints), distinct from FRONTEND_BASE_URL.
# Empty (the default) means unsubscribe links/headers are OMITTED from
# outgoing email rather than emitted broken; set it in any deployed env.
# ⚠️ Unsubscribe tokens are signed with SECRET_KEY — every service that
# sends notification email (backend-django + the email crons) must share
# the same SECRET_KEY or footer links minted by one 400 at the other.
API_PUBLIC_BASE_URL = os.environ.get("API_PUBLIC_BASE_URL", "")


# --- Stripe billing (self-serve subscription tiers) ---
# Entirely optional: with SECRET_KEY unset the billing endpoints report
# {enabled: false} and the frontend keeps its "coming soon" placeholder —
# the tier system works without Stripe (ops set tiers via
# `feature_access`). A plan is purchasable only when its price id is
# set. WEBHOOK_SECRET is required for the webhook endpoint to accept
# events at all (unverified events are never processed).
# `enterprise` is deliberately absent — contact-sales only.
def _stripe_prices_by_currency() -> dict[str, dict[str, str]]:
    """Parse STRIPE_PRICES_BY_CURRENCY. Invalid JSON fails LOUD at boot.

    Same posture as TIER_QUOTAS_JSON above: silently falling back to
    "no other currencies" would take a working pricing page down to one
    currency with nothing in the logs to say why.
    """
    raw = os.environ.get("STRIPE_PRICES_BY_CURRENCY", "").strip()
    if not raw:
        return {}
    from django.core.exceptions import ImproperlyConfigured

    try:
        parsed = json.loads(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f"STRIPE_PRICES_BY_CURRENCY is not valid JSON: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ImproperlyConfigured(
            'STRIPE_PRICES_BY_CURRENCY must be {"usd": {"core": "price_..."}}'
        )
    out: dict[str, dict[str, str]] = {}
    for code, plans in parsed.items():
        if not isinstance(plans, dict):
            raise ImproperlyConfigured(
                f"STRIPE_PRICES_BY_CURRENCY[{code!r}] must be a plan -> price id map"
            )
        out[str(code).lower()] = {str(k): str(v) for k, v in plans.items() if v}
    return out


STRIPE = {
    "SECRET_KEY": os.environ.get("STRIPE_SECRET_KEY", ""),
    "WEBHOOK_SECRET": os.environ.get("STRIPE_WEBHOOK_SECRET", ""),
    # The currency PRICE_CORE/PRO/MAX below are denominated in — the one
    # a buyer gets when we have nothing better to go on.
    "DEFAULT_CURRENCY": os.environ.get("STRIPE_DEFAULT_CURRENCY", "jpy").lower(),
    # CURRENT prices in the DEFAULT currency — what a new checkout is
    # sold at. core JPY1,200 / pro JPY2,500 / max JPY4,900 per user/month.
    "PRICE_CORE": os.environ.get("STRIPE_PRICE_CORE", ""),
    "PRICE_PRO": os.environ.get("STRIPE_PRICE_PRO", ""),
    "PRICE_MAX": os.environ.get("STRIPE_PRICE_MAX", ""),
    # Prices in OTHER currencies: {"usd": {"core": "price_...", ...}, ...}
    #
    # Explicit per currency, never converted. `$9` and `¥1,200` are both
    # deliberate round numbers chosen to read well locally; neither is
    # the other one times an exchange rate. Converting would advertise
    # ¥1,847/month and move it every time the market did.
    #
    # This is the one place the cost system's "USD base, convert for
    # display" rule does NOT apply — see origin/search_engine/money.py.
    #
    # A plan missing from a currency is simply not offered to buyers in
    # it, rather than offered and failing at checkout.
    "PRICES_BY_CURRENCY": _stripe_prices_by_currency(),
    # GRANDFATHERED prices — comma-separated `price_...` ids that still
    # resolve to a plan on incoming subscription events but are never
    # offered at checkout.
    #
    # Stripe never repoints an existing subscription at a new price
    # object, so when pro was repriced JPY1,200 -> JPY2,500 (and max
    # JPY2,500 -> JPY4,900) every existing subscriber kept renewing on
    # the OLD price id. Without these, each renewal would arrive with an
    # id `plan_for_price` no longer recognises, log "unmapped price",
    # and silently leave the tier unchanged (eventually dropping the
    # user to free). Put the pre-repricing ids here — one per mode, test
    # and live ids differ.
    #
    # Note the old pro price (JPY1,200) is numerically today's CORE
    # price but is deliberately mapped to `pro`: grandfathered
    # subscribers keep the plan and limits they bought, not the plan
    # that now costs what they pay.
    "PRICE_PRO_LEGACY": os.environ.get("STRIPE_PRICE_PRO_LEGACY", ""),
    "PRICE_MAX_LEGACY": os.environ.get("STRIPE_PRICE_MAX_LEGACY", ""),
    # Stripe Tax on checkout sessions. Leave off until the account's
    # tax settings (origin address, registrations) are configured in
    # the dashboard — Stripe rejects session creation otherwise.
    "AUTOMATIC_TAX": os.environ.get("STRIPE_AUTOMATIC_TAX", "false").lower() == "true",
    # Require a terms-of-service checkbox on checkout (links to the
    # /legal page — cancellation/refund policy). Leave off until the
    # account's terms-of-service URL is set in the dashboard (Settings
    # → Business → Public details) — Stripe rejects session creation
    # otherwise, exactly like AUTOMATIC_TAX above.
    "TOS_CONSENT": os.environ.get("STRIPE_TOS_CONSENT", "false").lower() == "true",
}

# How long a password-reset URL is valid for, in minutes. Short enough
# that a leaked link is unlikely to still work, long enough that users
# can finish reading the email and clicking.
PASSWORD_RESET_TOKEN_EXPIRY_MINUTES = int(
    os.environ.get("PASSWORD_RESET_TOKEN_EXPIRY_MINUTES", "60")
)

# How long an email-verification URL is valid for, in minutes. Longer
# than password-reset because the user just opened their inbox at signup
# and the cost of expiry is mild (they request a resend).
EMAIL_VERIFICATION_TOKEN_EXPIRY_MINUTES = int(
    os.environ.get("EMAIL_VERIFICATION_TOKEN_EXPIRY_MINUTES", "1440")
)

# How long a team-invite URL is valid for, in minutes. Default 7 days —
# generous since the invitee may not check their inbox right away and an
# invite is lower-risk than a password-reset link.
TEAM_INVITE_TOKEN_EXPIRY_MINUTES = int(os.environ.get("TEAM_INVITE_TOKEN_EXPIRY_MINUTES", "10080"))

# --- OAuth (Google, GitHub) ---
# Fernet key used to encrypt third-party access / refresh tokens at
# rest in the ConnectedAccount table. Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Required in production. In dev it can be left empty as long as you
# don't exercise OAuth flows — the crypto helper raises a clear error
# only when actually used (see origin/services/crypto.py).
OAUTH_TOKEN_ENCRYPTION_KEY = os.environ.get("OAUTH_TOKEN_ENCRYPTION_KEY", "")

# Per-provider OAuth client credentials. Empty defaults so the rest of
# Django still imports cleanly when these aren't configured yet; the
# OAuth views check for them and 503 with a helpful message.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", "")
GITHUB_OAUTH_CLIENT_ID = os.environ.get("GITHUB_OAUTH_CLIENT_ID", "")
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get("GITHUB_OAUTH_CLIENT_SECRET", "")

# Shared secret for GitHub repo webhook payload verification. Generate
# any random string (e.g. `openssl rand -hex 32`), set the SAME value
# both here AND in the GitHub repo's Webhook settings (under "Secret")
# so the signed payload's `X-Hub-Signature-256` header validates.
# When empty, the webhook endpoint rejects all incoming requests.
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET", "")

# Public-facing URL of THIS backend, used to build OAuth callback URLs
# that match what's registered in the Google / GitHub OAuth app config.
# Defaults to the dockerised dev Django port (see docker/docker-compose.yml;
# 8889 is Flask's websocket, 8890 is Django REST — confirmed by
# `python manage.py runserver 127.0.0.1:8890` in docs/setup.sh).
BACKEND_BASE_URL = os.environ.get("BACKEND_BASE_URL", "http://localhost:8890")
