# Generated by Django 5.2.15 on 2026-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0013_agentrunjudgement_prose_faithfulness'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
