# Generated by Django 5.2.16 on 2026-07-24 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0014_agentrun_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstep',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AgentLlmCall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('step_index', models.IntegerField(default=0)),
                ('purpose', models.CharField(blank=True, default='', max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('latency_ms', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('cache_write_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('thought_tokens', models.IntegerField(default=0)),
                ('tool_prompt_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='search_engine.agentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['team_id', '-created_at'], name='se_llmcall_team_created_idx'), models.Index(fields=['run'], name='se_llmcall_run_idx')],
            },
        ),
    ]
