# Generated by Django 5.2.16 on 2026-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0015_agentstep_latency_ms_agentllmcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequestCost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('team_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('surface', models.CharField(blank=True, default='', max_length=32)),
                ('plan', models.CharField(blank=True, default='', max_length=32)),
                ('effort', models.CharField(blank=True, default='', max_length=16)),
                ('result', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('quoted_max_jpy_milli', models.BigIntegerField(default=0)),
                ('computed_jpy_milli', models.BigIntegerField(default=0)),
                ('computed_usd_micro', models.BigIntegerField(default=0)),
                ('charged_jpy_milli', models.BigIntegerField(default=0)),
                ('absorbed_jpy_milli', models.BigIntegerField(default=0)),
                ('shadow_credits_milli', models.BigIntegerField(default=0)),
                ('credit_policy_version', models.CharField(blank=True, default='', max_length=32)),
                ('rate_card_version', models.CharField(blank=True, default='', max_length=64)),
                ('call_count', models.IntegerField(default=0)),
                ('has_unpriced', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', '-started_at'], name='se_reqcost_user_started_idx'), models.Index(fields=['surface', '-started_at'], name='se_reqcost_surface_idx')],
            },
        ),
        migrations.CreateModel(
            name='AiSpendEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True)),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('team_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('surface', models.CharField(blank=True, default='', max_length=32)),
                ('purpose', models.CharField(blank=True, default='', max_length=32)),
                ('plan', models.CharField(blank=True, default='', max_length=32)),
                ('effort', models.CharField(blank=True, default='', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('cache_write_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('thought_tokens', models.IntegerField(default=0)),
                ('tool_prompt_tokens', models.IntegerField(default=0)),
                ('unit_kind', models.CharField(blank=True, default='', max_length=16)),
                ('units', models.IntegerField(default=0)),
                ('cost_usd_micro', models.BigIntegerField(default=0)),
                ('cost_jpy_milli', models.BigIntegerField(default=0)),
                ('cost_basis', models.CharField(blank=True, db_index=True, default='priced', max_length=16)),
                ('rate_card_version', models.CharField(blank=True, default='', max_length=64)),
                ('fx_jpy_per_usd', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['request_id'], name='se_spend_request_idx'), models.Index(fields=['user_id', '-created_at'], name='se_spend_user_created_idx'), models.Index(fields=['provider', '-created_at'], name='se_spend_provider_idx')],
            },
        ),
    ]
