# Generated by Django 5.2.16 on 2026-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0016_airequestcost_aispendevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aispendevent',
            name='billable_units',
            field=models.BigIntegerField(default=0),
        ),
    ]
