# Generated by Django 5.2.16 on 2026-07-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0017_ai_spend_billable_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestcost',
            name='eligible_jpy_milli',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='plan_entitlement_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='airequestcost',
            name='credit_policy_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
