# Generated by Django 5.2.16 on 2026-07-26 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0018_ai_request_cost_eligible_and_policy_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCreditEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('team_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('entry_type', models.CharField(max_length=16)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('credits_milli', models.BigIntegerField()),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('plan', models.CharField(blank=True, default='', max_length=32)),
                ('credit_policy_version', models.CharField(blank=True, default='', max_length=64)),
                ('plan_entitlement_version', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('actor', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'period'], name='se_credit_user_period_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entry_type', 'charge')), fields=('request_id',), name='uq_credit_charge_per_request'), models.UniqueConstraint(condition=models.Q(('entry_type', 'grant'), ('kind', 'monthly')), fields=('user_id', 'period', 'plan'), name='uq_credit_monthly_grant')],
            },
        ),
    ]
