# Generated by Django 5.2.16 on 2026-07-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0019_aicreditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestcost',
            name='balance_before_milli',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='quoted_max_credits_milli',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='would_have_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
