# Generated by Django 5.2.16 on 2026-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0020_ai_request_cost_shadow_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='rolling_summary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='rolling_summary_through',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
