# Generated by Django 5.2.16 on 2026-07-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0021_agentsession_rolling_summary_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestcost',
            name='absorbed_usd_micro',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='charged_usd_micro',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='eligible_usd_micro',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestcost',
            name='quoted_max_usd_micro',
            field=models.BigIntegerField(default=0),
        ),
    ]
