# Generated by Django 5.2.16 on 2026-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0022_airequestcost_absorbed_usd_micro_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aicreditentry',
            index=models.Index(fields=['user_id', 'kind', 'period'], name='se_credit_user_kind_idx'),
        ),
    ]
