# Generated by Django 5.2.16 on 2026-08-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0023_credit_user_kind_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicreditentry',
            name='external_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='aicreditentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'grant'), ('external_ref__isnull', False)), fields=('external_ref',), name='uq_credit_grant_per_external_ref'),
        ),
    ]
