# Generated by Django 5.2.16 on 2026-08-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0024_credit_entry_external_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
